### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JuliaVasconcelos234** [WhiskeySockets/Baileys#1020]
having this problem using baileys, Mysql e Mongo db

Disconnect error details: TypeError: Cannot read properties of undefined (reading 'replaceOne')
at writeData (C:\Users\pc\Documents\Tellegroup\baileys\intechcrm-new-whatsapp\src\api\helper\mongoAuthState.js:62:27)

**Comment by DikaArdnt** [comment]
> having this problem using baileys, Mysql e Mongo db
> 
> Disconnect error details: TypeError: Cannot read properties of undefined (reading 'replaceOne') at writeData (C:\Users\pc\Documents\baileys\whatsapp\src\api\helper\mongoAuthState.js:62:27)

Isn't that a problem you should solve yourself? it's not a bug from baileys
