### ISSUE TITLE
websocket not connect

### ISSUE THREAD

**Issue by utqinadhif** [WhiskeySockets/Baileys#1021]
{"level":30,"time":"2024-08-27T07:04:43.596Z","pid":86,"hostname":"8b4f499c0082","class":"baileys","trace":"Error: WebSocket Error ()\n    at WebSocketClient.<anonymous> (/usr/src/app/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:617:17)\n    at WebSocketClient.emit (node:events:519:28)\n    at WebSocket.<anonymous> (/usr/src/app/node_modules/@whiskeysockets/baileys/lib/Socket/Client/web-socket-client.js:46:100)\n    at WebSocket.emit (node:events:519:28)\n    at emitErrorAndClose (/usr/src/app/node_modules/ws/lib/websocket.js:1041:13)\n    at ClientRequest.<anonymous> (/usr/src/app/node_modules/ws/lib/websocket.js:881:5)\n    at ClientRequest.emit (node:events:519:28)\n    at emitErrorEvent (node:_http_client:108:11)\n    at TLSSocket.socketErrorListener (node:_http_client:511:5)\n    at TLSSocket.emit (node:events:519:28)","msg":"connection errored"}

**Comment by hendranata** [comment]
same issue. any solution?

**Comment by samosxin** [comment]
me too

**Comment by utqinadhif** [comment]
I have change my backend from baileys to wawebjs for now, i still wait for fix,

**Comment by bobslavtriev** [comment]
Problem in your code, use it correctly as stated in the documentation.

**Comment by utqinadhif** [comment]
This problem does not occur at the beginning and does not occur continuously. but it definitely happens at unpredictable times.

**Comment by samosxin** [comment]
I use demo，  run <yarn example>, but ' error: Error: WebSocket Error (Opening handshake has timed out) ', Do I need to change any configuration information？？？

**Comment by samosxin** [comment]
help me
