### ISSUE TITLE
[BUG] bad-request in sock.profilePictureUrl 

### ISSUE THREAD

**Issue by adithyan-hermit** [WhiskeySockets/Baileys#1024]
**Describe the bug**

**To Reproduce**
1. Created a new connection
2. Closed & used saved credentials to log back in
3. Etc.

**Expected behavior**

**Environment (please complete the following information):**
 - Is this on a server? Yes
 - What do your `connectOptions` look like? Normal 
 - Do you have multiple clients on the same IP? No
 - Are you using a proxy? no

**Additional context**

Error: bad-request
    at assertNodeErrorFree (/root/hermit-bot/node_modules/@WhiskeySockets/baileys/lib/WABinary/generic-utils.js:56:15)
    at query (/root/hermit-bot/node_modules/@WhiskeySockets/baileys/lib/Socket/socket.js:145:48)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.profilePictureUrl (/root/hermit-bot/node_modules/@WhiskeySockets/baileys/lib/Socket/chats.js:442:24) {
  data: 400,
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 500,
    payload: {
      statusCode: 500,
      error: 'Internal Server Error',
      message: 'An internal server error occurred'
    },
    headers: {}
  }
}

**Comment by adithyan-hermit** [comment]
> This error occurs when the account does not have a profile picture. In this case, I recommend catching the error and either returning `false` or generating a thumbnail for the user.
> 
> See example what i use:
> 
> ```js
> async get_avatar(){
>         const ppUrl = await this.WASocket.profilePictureUrl(this.WASocket.user?.id ?? '').then((ppUrl) => ppUrl)
>             .catch((ex) => {
>                 return random_avatar_byname(this.WASocket.user?.name);
>             });
>         return ppUrl;
>     }
>    
> ```

Ya but it's only working when get my own jid profile not working of others jid. (Who has profile)

**Comment by Rippanteq7** [comment]
Use latest version of baileys, it should have been fixed in #901

**Comment by adithyan-hermit** [comment]
> Use latest version of baileys, it should have been fixed in #901

Already using baileys 6.7.7

**Comment by benaysuman** [comment]
I have the same issue, not with all profile pictures but alot give back an error. The error is different from the error that it gives when there is no profile picture.

**Comment by Yaniv101** [comment]
Hi, 
same issue, cant get my own account profile image
