### ISSUE TITLE
How to send reactions to WhatsApp status?

### ISSUE THREAD

**Issue by RullDev** [WhiskeySockets/Baileys#1029]
If there is a code please let me know.

**Comment by Akkun3704** [comment]
Just send react message like usual and add options statusJidList

**Comment by RullDev** [comment]
> Just send react message like usual and add options statusJidList

I don't understand, try giving me an example code

**Comment by joweste** [comment]
> > Just send react message like usual and add options statusJidList
> 
> I don't understand, try giving me an example code

const reactionMessage = {
        react: {
          text: 'teste,
          key: your_messsage_key,
        },
      };
      await client.sendMessage(jid, reactionMessage);

**Comment by DannOfficial** [comment]
await client.sendMessage(jid, { react: { text: "", // emoji key: "" // key (m.key) }, { statusJidList: [] })

**Comment by KichuExe** [comment]
> await client.sendMessage(jid, { react: { text: "", // emoji key: "" // key (m.key) }, { statusJidList: [] })

How to reply a message to status?

**Comment by AstroX11** [comment]
**How to Automatically React to a WhatsApp Status**

```javascript
await conn.sendMessage(
message.key.remoteJid,
{ react: { key: message.key, text: '💚' } },
{ statusJidList: [message.key.participant, conn.user.id] }
				);
```

**Comment by KichuExe** [comment]
> **How to Automatically React to a WhatsApp Status**
> 
> ```js
> await conn.sendMessage(
> message.key.remoteJid,
> { react: { key: message.key, text: '💚' } },
> { statusJidList: [message.key.participant, conn.user.id] }
> 				);
> ```

Not this message reply

**Comment by AstroX11** [comment]
> > **How to Automatically React to a WhatsApp Status**
> > ```js
> > await conn.sendMessage(
> > message.key.remoteJid,
> > { react: { key: message.key, text: '💚' } },
> > { statusJidList: [message.key.participant, conn.user.id] }
> > 				);
> > ```
> 
> Not this message reply

?

**Comment by KichuExe** [comment]
> > > **How to Automatically React to a WhatsApp Status**
> > > ```js
> > > await conn.sendMessage(
> > > message.key.remoteJid,
> > > { react: { key: message.key, text: '💚' } },
> > > { statusJidList: [message.key.participant, conn.user.id] }
> > > 				);
> > > ```
> > 
> > 
> > Not this message reply
> 
> ?

I mean like "Hey buddy nice status" how to send text messages??

**Comment by KichuExe** [comment]
> **How to Automatically React to a WhatsApp Status**
> 
> ```js
> await conn.sendMessage(
> message.key.remoteJid,
> { react: { key: message.key, text: '💚' } },
> { statusJidList: [message.key.participant, conn.user.id] }
> 				);
> ```

```EKEYTYPE: The key argument has to be of type `string` or `number`. Found: `undefined`
     at NodeCache._error (/node_modules/node-cache/lib/node_cache.js:762:17)
     at NodeCache._isInvalidKey (/node_modules/node-cache/lib/node_cache.js:668:23)
     at NodeCache.get (/node_modules/node-cache/lib/node_cache.js:362:25)
     at getUSyncDevices (/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:125:50)
     at /node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:321:53
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
     at async Object.transaction (/node_modules/@whiskeysockets/baileys/lib/Utils/auth-utils.js:135:26)
     at async relayMessage (/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:287:9)
     at async Object.sendMessage (/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:662:17)
     at async whatsappController (/lib/whatsappController.js:13:9) {
   errorcode: 'EKEYTYPE',
   data: { type: 'undefined' }
 }```

How to fix this error?

**Comment by anonphoenix007** [comment]
> > **How to Automatically React to a WhatsApp Status**
> > 
> > ```js
> > await conn.sendMessage(
> > message.key.remoteJid,
> > { react: { key: message.key, text: '💚' } },
> > { statusJidList: [message.key.participant, conn.user.id] }
> > 				);
> > ```
> 
> ```EKEYTYPE: The key argument has to be of type `string` or `number`. Found: `undefined`
>      at NodeCache._error (/node_modules/node-cache/lib/node_cache.js:762:17)
>      at NodeCache._isInvalidKey (/node_modules/node-cache/lib/node_cache.js:668:23)
>      at NodeCache.get (/node_modules/node-cache/lib/node_cache.js:362:25)
>      at getUSyncDevices (/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:125:50)
>      at /node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:321:53
>      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>      at async Object.transaction (/node_modules/@whiskeysockets/baileys/lib/Utils/auth-utils.js:135:26)
>      at async relayMessage (/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:287:9)
>      at async Object.sendMessage (/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:662:17)
>      at async whatsappController (/lib/whatsappController.js:13:9) {
>    errorcode: 'EKEYTYPE',
>    data: { type: 'undefined' }
>  }```
> 
> How to fix this error?

Implement on your side bro
code structures are different, you probably need to change yours to m.key and m.key.participant
