### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by arc1887** [WhiskeySockets/Baileys#1037]
TypeError: Cannot read properties of undefined (reading 'toString')
    at getStream (/data/data/com.termux/files/home/tet/node_modules/@whiskeysockets/baileys/lib/Utils/messages-media.js:280:18)
    at encryptedStream (/data/data/com.termux/files/home/tet/node_modules/@whiskeysockets/baileys/lib/Utils/messages-media.js:325:58)
    at prepareWAMessageMedia (/data/data/com.termux/files/home/tet/node_modules/@whiskeysockets/baileys/lib/Utils/messages.js:113:152)
    at generateWAMessageContent (/data/data/com.termux/files/home/tet/node_modules/@whiskeysockets/baileys/lib/Utils/messages.js:415:53)
    at generateWAMessage (/data/data/com.termux/files/home/tet/node_modules/@whiskeysockets/baileys/lib/Utils/messages.js:507:102)
    at Object.sendMessage (/data/data/com.termux/files/home/tet/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:621:69)
    at baseoriasep (/data/data/com.termux/files/home/tet/case.js:330:20)

**Comment by Akkun3704** [comment]
What are you doing?

**Comment by JustSoursop** [comment]
User code error. 
It shouldn't on issue. 

Check your code correctly `/data/data/com.termux/files/home/tet/case.js:330`
