### ISSUE TITLE
404,myAppStateKeyId not present

### ISSUE THREAD

**Issue by anonphoenix007** [WhiskeySockets/Baileys#1046]
Error: myAppStateKey ("ID here") not present
    at encodeSyncdPatch (/root/wabot/ANTIBUG/node_modules/@whiskeysockets/baileys/lib/Utils/chat-utils.js:105:15)
    at async /root/wabot/ANTIBUG/node_modules/@whiskeysockets/baileys/lib/Socket/chats.js:555:32
    at async Object.transaction (/root/wabot/ANTIBUG/node_modules/@whiskeysockets/baileys/lib/Utils/auth-utils.js:136:26)
    at async /root/wabot/ANTIBUG/node_modules/@whiskeysockets/baileys/lib/Socket/chats.js:550:13
    at async /root/wabot/ANTIBUG/node_modules/@whiskeysockets/baileys/lib/Utils/make-mutex.js:18:36 {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 404,
    payload: {
      statusCode: 404,
      error: 'Not Found',
      message: 'myAppStateKey ("ID here") not present'
    },
    headers: {}
  }
}

I get the above error whenever I try to use the chatModify function ,I checked my credentials file and there's a myAppStateKey present but I don't understand why it's not working for me.
The below code is the one I tried to use to modify the chat

await Taira.chatModify({ delete: true, lastMessages: [{ key: m.key, messageTimestamp: m.messageTimestamp }] }, m.sender);

**Comment by anonphoenix007** [comment]
@PurpShell

**Comment by bobslavtriev** [comment]
Are you using shouldIgnoreJid?

**Comment by anonphoenix007** [comment]
> Are you using shouldIgnoreJid?

I'm not 🤔

**Comment by ImPedro29** [comment]
> > Are you using shouldIgnoreJid?
> 
> I'm not 🤔

It solved?

**Comment by AstroX11** [comment]
> Error: myAppStateKey ("ID here") not present at encodeSyncdPatch (/root/wabot/ANTIBUG/node_modules/@whiskeysockets/baileys/lib/Utils/chat-utils.js:105:15) at async /root/wabot/ANTIBUG/node_modules/@whiskeysockets/baileys/lib/Socket/chats.js:555:32 at async Object.transaction (/root/wabot/ANTIBUG/node_modules/@whiskeysockets/baileys/lib/Utils/auth-utils.js:136:26) at async /root/wabot/ANTIBUG/node_modules/@whiskeysockets/baileys/lib/Socket/chats.js:550:13 at async /root/wabot/ANTIBUG/node_modules/@whiskeysockets/baileys/lib/Utils/make-mutex.js:18:36 { data: null, isBoom: true, isServer: false, output: { statusCode: 404, payload: { statusCode: 404, error: 'Not Found', message: 'myAppStateKey ("ID here") not present' }, headers: {} } }
> 
> I get the above error whenever I try to use the chatModify function ,I checked my credentials file and there's a myAppStateKey present but I don't understand why it's not working for me. The below code is the one I tried to use to modify the chat
> 
> await Taira.chatModify({ delete: true, lastMessages: [{ key: m.key, messageTimestamp: m.messageTimestamp }] }, m.sender);

You remove all the `app-state-key` from your authentication, this isn't a baileys issue it's you and your code

**Comment by ImPedro29** [comment]
> > > Error: myAppStateKey ("ID here") not present at encodeSyncdPatch (/root/wabot/ANTIBUG/node_modules/@whiskeysockets/baileys/lib/Utils/chat-utils.js:105:15) at async /root/wabot/ANTIBUG/node_modules/@whiskeysockets/baileys/lib/Socket/chats.js:555:32 at async Object.transaction (/root/wabot/ANTIBUG/node_modules/@whiskeysockets/baileys/lib/Utils/auth-utils.js:136:26) at async /root/wabot/ANTIBUG/node_modules/@whiskeysockets/baileys/lib/Socket/chats.js:550:13 at async /root/wabot/ANTIBUG/node_modules/@whiskeysockets/baileys/lib/Utils/make-mutex.js:18:36 { data: null, isBoom: true, isServer: false, output: { statusCode: 404, payload: { statusCode: 404, error: 'Not Found', message: 'myAppStateKey ("ID here") not present' }, headers: {} } }
> > > I get the above error whenever I try to use the chatModify function ,I checked my credentials file and there's a myAppStateKey present but I don't understand why it's not working for me. The below code is the one I tried to use to modify the chat
> > > await Taira.chatModify({ delete: true, lastMessages: [{ key: m.key, messageTimestamp: m.messageTimestamp }] }, m.sender);
> > 
> > 
> > You remove all the `app-state-key` from your authentication, this isn't a baileys issue it's you and your code
> 
> I have fixed this ages ago,thanks regardless

Good to know, its happening on third party code, thx 👍

**Comment by anonphoenix007** [comment]
> > > > Error: myAppStateKey ("ID here") not present at encodeSyncdPatch (/root/wabot/ANTIBUG/node_modules/@whiskeysockets/baileys/lib/Utils/chat-utils.js:105:15) at async /root/wabot/ANTIBUG/node_modules/@whiskeysockets/baileys/lib/Socket/chats.js:555:32 at async Object.transaction (/root/wabot/ANTIBUG/node_modules/@whiskeysockets/baileys/lib/Utils/auth-utils.js:136:26) at async /root/wabot/ANTIBUG/node_modules/@whiskeysockets/baileys/lib/Socket/chats.js:550:13 at async /root/wabot/ANTIBUG/node_modules/@whiskeysockets/baileys/lib/Utils/make-mutex.js:18:36 { data: null, isBoom: true, isServer: false, output: { statusCode: 404, payload: { statusCode: 404, error: 'Not Found', message: 'myAppStateKey ("ID here") not present' }, headers: {} } }
> > > > I get the above error whenever I try to use the chatModify function ,I checked my credentials file and there's a myAppStateKey present but I don't understand why it's not working for me. The below code is the one I tried to use to modify the chat
> > > > await Taira.chatModify({ delete: true, lastMessages: [{ key: m.key, messageTimestamp: m.messageTimestamp }] }, m.sender);
> > > 
> > > 
> > > You remove all the `app-state-key` from your authentication, this isn't a baileys issue it's you and your code
> > 
> > I have fixed this ages ago,thanks regardless
> 
> Good to know, its happening on third party code, thx 👍 

the error only occur when you don't pair or scan qr on terminal, because the app-state keys will not be present,it all depends your method of connecting to WhatsApp socket,
