### ISSUE TITLE
[BUG] SETPROFILE

### ISSUE THREAD

**Issue by rasssya76** [WhiskeySockets/Baileys#1047]
Info, bro, setppbot/setppgc doesn't work, I tried to evaluate this but it didn't work
=> conn.query({
        tag: "iq",
        attrs: {
          to: global.nomorbot,
          type: "set",
          xmlns: "w:profile:picture"
        },
        content: [{
          tag: "picture",
          attrs: {
            type: "image"
          },
          content: await m.quoted.download()
        }]
        })

**Comment by Akkun3704** [comment]
Same issue, i got this error when i tried to send query node manually

```bash
Error: Timed Out
    at /home/ripp/bot/node_modules/baileys/lib/Utils/generics.js:145:32 {
  data: {
    stack: 'Error\n' +
      '    at promiseTimeout (/home/ripp/bot/node_modules/baileys/lib/Utils/generics.js:140:19)\n' +
      '    at waitForMessage (/home/ripp/bot/node_modules/baileys/lib/Socket/socket.js:119:53)\n' +
      '    at Object.query (/home/ripp/bot/node_modules/baileys/lib/Socket/socket.js:141:22)\n' +
      '    at Object.eval (eval at handler (/home/ripp/bot/src/plugins/owner/eval.js:24:14), <anonymous>:3:13)\n' +
      '    at async Object.handler (/home/ripp/bot/src/plugins/owner/eval.js:25:13)\n' +
      '    at async Object.onMessage (/home/ripp/bot/src/handler.js:128:7)'
  },
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 408,
    payload: {
      statusCode: 408,
      error: 'Request Time-out',
      message: 'Timed Out'
    },
    headers: {}
  }
}
```

**Comment by Akkun3704** [comment]
#1048

**Comment by ImYanXiao** [comment]
> Info, bro, setppbot/setppgc doesn't work, I tried to evaluate this but it didn't work => conn.query({ tag: "iq", attrs: { to: global.nomorbot, type: "set", xmlns: "w:profile:picture" }, content: [{ tag: "picture", attrs: { type: "image" }, content: await m.quoted.download() }] })

https://github.com/WhiskeySockets/Baileys/issues/1067#issuecomment-2396382441
