### ISSUE TITLE
[BUG] When sending message

### ISSUE THREAD

**Issue by davicolet** [WhiskeySockets/Baileys#105]
Hello, I'm having this error when trying to send messages to groups.

`Failed to decrypt message with any known session...
Session error:MessageCounterError: Key used already or never filled MessageCounterError: Key used already or never filled
    at SessionCipher.doDecryptWhisperMessage (/home/-/-/node_modules/libsignal/src/session_cipher.js:236:19)`

I've tried to rescan the session and it follows.

I'm using useMultiFileAuthState('...') as stated in the documentation

would anyone know what could be causing this?

**Comment by andresayac** [comment]
can you share with us how you initialize the socket?
https://github.com/WhiskeySockets/Baileys/blob/534b1ea778152fa77bee47da291e1f3f5c153091/Example/example.ts#L40

**Comment by davicolet** [comment]
Of course, I'm using it that way:

`socketConfig = {
    defaultQueryTimeoutMs: undefined,
    printQRInTerminal: false,
    browser: ['Dashboard WPP', '', '3.0'],
    logger: pino({
        level: 'silent',
    }),
    generateHighQualityLinkPreview: true,
}

const { state, saveCreds } = await useMultiFileAuthState('sessiondata/' + this.key + '/')
this.authState = { state: state, saveCreds: saveCreds, keys: makeCacheableSignalKeyStore(state.keys) }
this.socketConfig.auth = this.authState.state
this.instance.sock = makeWASocket(this.socketConfig)`

**Comment by andresayac** [comment]
try to modify as in the example with respect to Auth in this way has not generated me error

**Comment by Cristopher8049** [comment]
You catch the error when you are trying to send the message. For example: `await sock.sendMessage(id, { text: 'hola' });`

**Comment by davicolet** [comment]
In some whatsapp works perfectly, but in others when trying to send to groups this error occurs and ends up restarting the session:

```
Failed to decrypt message with any known session...
Session error:Error: Bad MAC Error: Bad MAC
    at Object.verifyMAC (/home/-/node_modules/libsignal/src/crypto.js:87:15)
    at SessionCipher.doDecryptWhisperMessage (/home/-/node_modules/libsignal/src/session_cipher.js:250:16)
    at async SessionCipher.decryptWithSessions (/home/-/node_modules/libsignal/src/session_cipher.js:147:29)
    at async Object.5511971032330.0 [as awaitable] (/home/-/node_modules/libsignal/src/session_cipher.js:171:28)
    at async _asyncQueueExecutor (/home/-/node_modules/libsignal/src/queue_job.js:20:29)
Failed to decrypt message with any known session...
Session error:Error: Bad MAC Error: Bad MAC
    at Object.verifyMAC (/home/-/node_modules/libsignal/src/crypto.js:87:15)
    at SessionCipher.doDecryptWhisperMessage (/home/-/node_modules/libsignal/src/session_cipher.js:250:16)
    at async SessionCipher.decryptWithSessions (/home/-/node_modules/libsignal/src/session_cipher.js:147:29)
    at async Object.5511971032330.0 [as awaitable] (/home/-/node_modules/libsignal/src/session_cipher.js:171:28)
    at async _asyncQueueExecutor (/home/-/node_modules/libsignal/src/queue_job.js:20:29)
Failed to decrypt message with any known session...
Session error:Error: Bad MAC Error: Bad MAC
    at Object.verifyMAC (/home/-/node_modules/libsignal/src/crypto.js:87:15)
    at SessionCipher.doDecryptWhisperMessage (/home/-/node_modules/libsignal/src/session_cipher.js:250:16)
    at async SessionCipher.decryptWithSessions (/home/-/node_modules/libsignal/src/session_cipher.js:147:29)
    at async Object.5511971032330.0 [as awaitable] (/home/-/node_modules/libsignal/src/session_cipher.js:171:28)
    at async _asyncQueueExecutor (/home/-/node_modules/libsignal/src/queue_job.js:20:29)
Failed to decrypt message with any known session...
Session error:Error: Bad MAC Error: Bad MAC
    at Object.verifyMAC (/home/-/node_modules/libsignal/src/crypto.js:87:15)
    at SessionCipher.doDecryptWhisperMessage (/home/-/node_modules/libsignal/src/session_cipher.js:250:16)
    at async SessionCipher.decryptWithSessions (/home/-/node_modules/libsignal/src/session_cipher.js:147:29)
    at async Object.5511971032330.0 [as awaitable] (/home/-/node_modules/libsignal/src/session_cipher.js:171:28)
    at async _asyncQueueExecutor (/home/-/node_modules/libsignal/src/queue_job.js:20:29)
Failed to decrypt message with any known session...
```

Another error occurring, I don't know if this error is causing the aforementioned one.
But some groups timed out, even whatsapp trying to fire being superadmin of the group

```
[svqlcyjduprwkm] ERRO AO ENVIAR MENSAGEM NO GRUPO -> 1203...@g.us Error: Timed Out
    at /home/-/node_modules/@whiskeysockets/baileys/lib/Utils/generics.js:159:32
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7) {
  data: {
    stack: 'Error\n' +
      '    at promiseTimeout (/home/-/node_modules/@whiskeysockets/baileys/lib/Utils/generics.js:154:19)\n' +
      '    at sendRawMessage (/home/-/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:54:42)\n' +
      '    at sendNode (/home/-/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:70:16)\n' +
      '    at /home/-/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:431:19\n' +
      '    at runMicrotasks (<anonymous>)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
      '    at async Object.transaction (/home/-/node_modules/@whiskeysockets/baileys/lib/Utils/auth-utils.js:135:26)\n' +
      '    at async relayMessage (/home/-/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:276:9)\n' +
      '    at async Object.sendMessage (/home/-/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:637:17)\n' +
      '    at async /home/-/src/api/class/instance.js:986:20'
  },
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 408,
    payload: {
      statusCode: 408,
      error: 'Request Time-out',
      message: 'Timed Out'
    },
    headers: {}
  }
}
```

**Comment by davigasperin** [comment]
I'm facing the same problem, any solution yet?

**Comment by lanaparadinha** [comment]
I have same error...
Error: Timed Out
    at /home/deploy/whats/backend/node_modules/@whiskeysockets/baileys/lib/Utils/generics.js:136:32 {
  data: {
    stack: 'Error\n' +
      '    at promiseTimeout (/home/deploy/whats/backend/node_modules/@whiskeysockets/baileys/lib/Utils/generics.js:131:19)\n' +
      '    at waitForMessage (/home/deploy/whats/backend/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:114:53)\n' +
      '    at query (/home/deploy/whats/backend/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:136:22)\n' +
      '    at groupQuery (/home/deploy/whats/backend/node_modules/@whiskeysockets/baileys/lib/Socket/groups.js:12:55)\n' +
      '    at groupMetadata (/home/deploy/whats/backend/node_modules/@whiskeysockets/baileys/lib/Socket/groups.js:22:30)\n' +
      '    at /home/deploy/whats/backend/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:288:47\n' +
      '    at /home/deploy/whats/backend/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:291:23\n' +
      '    at Object.transaction (/home/deploy/whats/backend/node_modules/@whiskeysockets/baileys/lib/Utils/auth-utils.js:136:32)\n' +
      '    at relayMessage (/home/deploy/whats/backend/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:278:30)\n' +
      '    at Object.sendMessage (/home/deploy/whats/backend/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:648:23)\n' +
      '    at async SendWhatsAppMessage (/home/deploy/whats/backend/dist/services/WbotServices/SendWhatsAppMessage.js:58:29)\n' +
      '    at async store (/home/deploy/whats/backend/dist/controllers/MessageController.js:54:9)'
  },
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 408,
    payload: {
      statusCode: 408,
      error: 'Request Time-out',
      message: 'Timed Out'
    },
    headers: {}
  }


**OBS:** My project create in database 2 contacts, one contacts with "-" another Contacts whitout "-"
See:

whats=# select * from "Contacts" where name like 'Amap%';
  id   |       name       |         number          |               profilePicUrl                |         createdAt          |         updatedAt          | email | isGroup | companyId
-------+------------------+-------------------------+--------------------------------------------+----------------------------+----------------------------+-------+---------+----------
  1757 | Amapxxxxxxx | 5537###-xxx103 | https://xxxxxxx/nopicture.png | 2023-01-19 23:59:33.42+01  | 2023-01-19 23:59:33.42+01  |       | t       |         2
 17495 | Amapxxxxxxx  | 5537###xxx103  | https://xxxxxxx/nopicture.png | 2023-07-31 18:20:41.528+02 | 2023-07-31 18:20:41.528+02 |       | t       |         2
 
 In contact whitout "-" I dont send any messages and receive error But i read all messages.
 In Contact have "-" I send messages but dont read any messages.

**Comment by jefaokpta** [comment]
Same error

**Comment by wcpumarega** [comment]
Is there a solution for this problem?

**Comment by krugerrgabriel** [comment]
Hello, guys. I'm experiencing the same error. Has anyone been able to find a solution?

```
current-app-1  | Failed to decrypt message with any known session...
current-app-1  | Session error:Error: Bad MAC Error: Bad MAC
current-app-1  |     at Object.verifyMAC (/home/node/app/node_modules/super-libsignal/src/crypto.js:87:15)
current-app-1  |     at SessionCipher.doDecryptWhisperMessage (/home/node/app/node_modules/super-libsignal/src/session_cipher.js:250:16)
current-app-1  |     at async SessionCipher.decryptWithSessions (/home/node/app/node_modules/super-libsignal/src/session_cipher.js:147:29)
current-app-1  |     at async 5545920012998:61.0 [as awaitable] (/home/node/app/node_modules/super-libsignal/src/session_cipher.js:171:28)
current-app-1  |     at async _asyncQueueExecutor (/home/node/app/node_modules/super-libsignal/src/queue_job.js:20:29)
```

**Comment by rizxyu** [comment]
> I have same error... Error: Timed Out at /home/deploy/whats/backend/node_modules/@whiskeysockets/baileys/lib/Utils/generics.js:136:32 { data: { stack: 'Error\n' + ' at promiseTimeout (/home/deploy/whats/backend/node_modules/@whiskeysockets/baileys/lib/Utils/generics.js:131:19)\n' + ' at waitForMessage (/home/deploy/whats/backend/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:114:53)\n' + ' at query (/home/deploy/whats/backend/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:136:22)\n' + ' at groupQuery (/home/deploy/whats/backend/node_modules/@whiskeysockets/baileys/lib/Socket/groups.js:12:55)\n' + ' at groupMetadata (/home/deploy/whats/backend/node_modules/@whiskeysockets/baileys/lib/Socket/groups.js:22:30)\n' + ' at /home/deploy/whats/backend/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:288:47\n' + ' at /home/deploy/whats/backend/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:291:23\n' + ' at Object.transaction (/home/deploy/whats/backend/node_modules/@whiskeysockets/baileys/lib/Utils/auth-utils.js:136:32)\n' + ' at relayMessage (/home/deploy/whats/backend/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:278:30)\n' + ' at Object.sendMessage (/home/deploy/whats/backend/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:648:23)\n' + ' at async SendWhatsAppMessage (/home/deploy/whats/backend/dist/services/WbotServices/SendWhatsAppMessage.js:58:29)\n' + ' at async store (/home/deploy/whats/backend/dist/controllers/MessageController.js:54:9)' }, isBoom: true, isServer: false, output: { statusCode: 408, payload: { statusCode: 408, error: 'Request Time-out', message: 'Timed Out' }, headers: {} }
> 
> **OBS:** My project create in database 2 contacts, one contacts with "-" another Contacts whitout "-" See:
> 
> whats=# select * from "Contacts" where name like 'Amap%'; id | name | number | profilePicUrl | createdAt | updatedAt | email | isGroup | companyId -------+------------------+-------------------------+--------------------------------------------+----------------------------+----------------------------+-------+---------+---------- 1757 | Amapxxxxxxx | 5537###-xxx103 | https://xxxxxxx/nopicture.png | 2023-01-19 23:59:33.42+01 | 2023-01-19 23:59:33.42+01 | | t | 2 17495 | Amapxxxxxxx | 5537###xxx103 | https://xxxxxxx/nopicture.png | 2023-07-31 18:20:41.528+02 | 2023-07-31 18:20:41.528+02 | | t | 2
> 
> In contact whitout "-" I dont send any messages and receive error But i read all messages. In Contact have "-" I send messages but dont read any messages.

looks like a baileys bug, I've never gotten that error code except for the 500 error code

**Comment by rayanchemin** [comment]
Using just like @davicolet configs and recurrently getting "Timed Out"
This property config **defaultQueryTimeoutMs: undefined,** was also recommended on Baileys Discord Group, but unfortnatly doesn't solve the problem.
Is it there any solution yet?

**Comment by raphaelvserafim** [comment]
I have the same error here

**Comment by ianvictor** [comment]
Também estou com o mesmo problema, alguma solução?

**Comment by FlavioCoutinhoGO** [comment]
Também estou com o mesmo problema.

**Comment by 4relial** [comment]
+1

**Comment by roysG** [comment]
+1

**Comment by izaias-nascimento** [comment]
+1

**Comment by hiagodeoliveiratv** [comment]
Bom dia, alguma solução?

**Comment by lanaparadinha** [comment]
A solução é fazer tratamento em grupos. 
Não é bug do bayleis.

The solution is make processing in groups.
not bug of bayleis.

**Comment by FlavioCoutinhoGO** [comment]
Com certeza **é um bug do Baileys**...

Esse erro fica aparecendo porque o Baileys não é capaz de lidar com algo e também não mostra como tratar isso... definitivamente não é um comportamento esperado em nenhum software.

**Comment by joaosouz4dev** [comment]
> A solução é fazer tratamento em grupos. Não é bug do bayleis.
> 
> The solution is make processing in groups. not bug of bayleis.

Qual foi a solução para você?

**Comment by PurpShell** [comment]
bad decryption errors are due to some mismanagement in our libsignal, will look into them all

**Comment by shubhamrathi97** [comment]
@PurpShell Any update on this issue ? Is there any workaround for a temporary fix?

**Comment by luizbarrosj** [comment]
tive o mesmo erro so verifiquei o jid 9999999999999999999999@g.us para 999999999999-9999999999@g.us

i had the same error so i checked the jid 9999999999999999999999@g.us to 999999999999-9999999999@g.us

**Comment by CSFelix** [comment]
👀

**Comment by andre-mr** [comment]
Wouldn't the reason be Meta managing server resources on a case-by-case basis? I have 3 bots with the exact same code and use case, one of them gives the error all day, the other occasionally and the other never.

**Comment by wilsinho8** [comment]
> Wouldn't the reason be Meta managing server resources on a case-by-case basis? I have 3 bots with the exact same code and use case, one of them gives the error all day, the other occasionally and the other never.

Same here, some connection every day i need to reconnect.. other i dont need to reconnect since January 2024.
Same code for all instances

Session error:MessageCounterError: Key used already or never filled MessageCounterError: Key used already or never filled
    at SessionCipher.doDecryptWhisperMessage (node_modules/libsignal/src/session_cipher.js:236:19)
    at SessionCipher.decryptWithSessions (node_modules/libsignal/src/session_cipher.js:147:40)
    at 5518981337208.88 [as awaitable] (node_modules/libsignal/src/session_cipher.js:171:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _asyncQueueExecutor (node_modules/libsignal/src/queue_job.js:20:29)

**Comment by andre-mr** [comment]
My concern is whether these solutions we're trying, such as using successive reconnections, disconnecting, and logging in again, might be overloading the transmissions and thereby causing Meta's server—which is trying to impose limits—to trigger a flag and ban us.

**Comment by tyagolp** [comment]
> > Wouldn't the reason be Meta managing server resources on a case-by-case basis? I have 3 bots with the exact same code and use case, one of them gives the error all day, the other occasionally and the other never.
> 
> Same here, some connections every day i need to reconnect.. with others i dont need to reconnect since January 2024. Same code for all instances
> 
> Session error:MessageCounterError: Key used already or never filled MessageCounterError: Key used already or never filled at SessionCipher.doDecryptWhisperMessage (node_modules/libsignal/src/session_cipher.js:236:19) at SessionCipher.decryptWithSessions (node_modules/libsignal/src/session_cipher.js:147:40) at 5518981337208.88 [as awaitable] (node_modules/libsignal/src/session_cipher.js:171:39) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async _asyncQueueExecutor (node_modules/libsignal/src/queue_job.js:20:29)

the exact same thing happens to me

**Comment by yvomenezes** [comment]
> > Wouldn't the reason be Meta managing server resources on a case-by-case basis? I have 3 bots with the exact same code and use case, one of them gives the error all day, the other occasionally and the other never.
> 
> Same here, some connections every day i need to reconnect.. with others i dont need to reconnect since January 2024. Same code for all instances
> 
> Session error:MessageCounterError: Key used already or never filled MessageCounterError: Key used already or never filled at SessionCipher.doDecryptWhisperMessage (node_modules/libsignal/src/session_cipher.js:236:19) at SessionCipher.decryptWithSessions (node_modules/libsignal/src/session_cipher.js:147:40) at 5518981337208.88 [as awaitable] (node_modules/libsignal/src/session_cipher.js:171:39) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async _asyncQueueExecutor (node_modules/libsignal/src/queue_job.js:20:29)

I'm experiencing the same issue.

**Comment by sergio-dd** [comment]
> > Wouldn't the reason be Meta managing server resources on a case-by-case basis? I have 3 bots with the exact same code and use case, one of them gives the error all day, the other occasionally and the other never.
> 
> Same here, some connections every day i need to reconnect.. with others i dont need to reconnect since January 2024. Same code for all instances
> 
> Session error:MessageCounterError: Key used already or never filled MessageCounterError: Key used already or never filled at SessionCipher.doDecryptWhisperMessage (node_modules/libsignal/src/session_cipher.js:236:19) at SessionCipher.decryptWithSessions (node_modules/libsignal/src/session_cipher.js:147:40) at 5518981337208.88 [as awaitable] (node_modules/libsignal/src/session_cipher.js:171:39) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async _asyncQueueExecutor (node_modules/libsignal/src/queue_job.js:20:29)

I'm experiencing the same issue.

**Comment by vguille** [comment]
I'm having the same problem, but only when I try to run inside a container, forcing a MAC address in the container temporarily solved it for me. Example: docker run --mac-address 02:42:ac:11:00:11 ...

**Comment by pxawtyy** [comment]
+1

**Comment by xxdannilinxx** [comment]
+1

**Comment by matteo4884** [comment]
Found the problem, when you connect at the same time with 2 or more devices it gives you 'bad mac' error. In my case I was using same connection at the same time with production and development. 
Solution: Delete all files saved for authentication, and never connect at the same time.

**Comment by andre-mr** [comment]
> Found the problem, when you connect at the same time with 2 or more devices it gives you 'bad mac' error. In my case I was using same connection at the same time with production and development. Solution: Delete all files saved for authentication, and never connect at the same time.

i use same account (sim card) for multiple bots, different scenarios. mycode is responsible for differentiating the types of messages received and sent. local or in another country (aws).

but they all use different auth, i authorized them using qr code, they are different devices from whatsapp connected devices list. even local dev has its own auth to avoid these conflict flags.

**Comment by matteo4884** [comment]
> > Found the problem, when you connect at the same time with 2 or more devices it gives you 'bad mac' error. In my case I was using same connection at the same time with production and development. Solution: Delete all files saved for authentication, and never connect at the same time.
> 
> i use same account (sim card) for multiple bots, different scenarios. mycode is responsible for differentiating the types of messages received and sent. local or in another country (aws).
> 
> but they all use different auth, i authorized them using qr code, they are different devices from whatsapp connected devices list. even local dev has its own auth to avoid these conflict flags.

I am quite sure that you have a issue with authentication. When there is a conflict WhatsApp blocks everything and throws 'bad Mac' error. Try reviewing your authentication code, 90% the issue is there. Probably you overwrite some important file or folder. 
How do you handle it? Can you share your code?

**Comment by andre-mr** [comment]
> > > Found the problem, when you connect at the same time with 2 or more devices it gives you 'bad mac' error. In my case I was using same connection at the same time with production and development. Solution: Delete all files saved for authentication, and never connect at the same time.
> > 
> > 
> > i use same account (sim card) for multiple bots, different scenarios. mycode is responsible for differentiating the types of messages received and sent. local or in another country (aws).
> > but they all use different auth, i authorized them using qr code, they are different devices from whatsapp connected devices list. even local dev has its own auth to avoid these conflict flags.
> 
> I am quite sure that you have a issue with authentication. When there is a conflict WhatsApp blocks everything and throws 'bad Mac' error. Try reviewing your authentication code, 90% the issue is there. Probably you overwrite some important file or folder. How do you handle it? Can you share your code?

I don't have any auth issue. I use windows for some cases and occasionally conflit error when nodejs process was not removed from memory, so I managed to kill any active process when start application. But it was a specific and ocasional case.

I have no conflit  because each instance I start is a different device authorized by qr code. each application handle its own identified messages and ignore the others.

**Comment by matteo4884** [comment]
> > > > Found the problem, when you connect at the same time with 2 or more devices it gives you 'bad mac' error. In my case I was using same connection at the same time with production and development. Solution: Delete all files saved for authentication, and never connect at the same time.
> > > 
> > > 
> > > i use same account (sim card) for multiple bots, different scenarios. mycode is responsible for differentiating the types of messages received and sent. local or in another country (aws).
> > > but they all use different auth, i authorized them using qr code, they are different devices from whatsapp connected devices list. even local dev has its own auth to avoid these conflict flags.
> > 
> > I am quite sure that you have a issue with authentication. When there is a conflict WhatsApp blocks everything and throws 'bad Mac' error. Try reviewing your authentication code, 90% the issue is there. Probably you overwrite some important file or folder. How do you handle it? Can you share your code?
> 
> I don't have any auth issue. I use windows for some cases and occasionally conflit error when nodejs process was not removed from memory, so I managed to kill any active process when start application. But it was a specific and ocasional case.
> 
> I have no conflit  because each instance I start is a different device authorized by qr code. each application handle its own identified messages and ignore the others.
> 
> Edit: reviewing post it seems this error is for node applications using multiple auth folders (multiple accounts or devices) in same application, is it right? if so, sorry I don't use it. I use useMultiFileAuthState but not using multiple locations/devices. :/

Yeah, I don't really know if this can help you, I was replying to people that has the specific error that I was mentioning.

**Comment by polvora6969** [comment]
Whatsapp Meta estará añadiendo restricciones sobre sus servidores? tengo el mismo error similar con una ruta de "node_modules\libsignal"
En consola al usar comandos no me detecta los mensajes solo en algunos grupos, en otros todo estable, en los que falla cuando quiero revisar usar comandos me arroja error 2 segundos despues en consola:
**SessionError: No sessions
    at Object.125735788363933.3 [as awaitable] (home\PolvoraBots\ADM\PolvoraBot\node_modules\libsignal\src\session_cipher.js:71:23)
    at _asyncQueueExecutor (home\PolvoraBots\ADM\PolvoraBot\node_modules\libsignal\src\queue_job.js:20:29)**
