### ISSUE TITLE
Crash while QR code are scannning

### ISSUE THREAD

**Issue by priyanshuChovatiya** [WhiskeySockets/Baileys#1058]
node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: WebSocket was closed before the connection was established
    at WebSocket.close (C:\Users\Admin\Desktop\Javascript\nodeJS\node_modules\ws\lib\websocket.js:299:7)
    at WebSocketClient.close (C:\Users\Admin\Desktop\Javascript\nodeJS\node_modules\baileys\lib\Socket\Client\web-socket-client.js:53:21)       
    at Object.end (C:\Users\Admin\Desktop\Javascript\nodeJS\node_modules\baileys\lib\Socket\socket.js:263:20)
    at EventEmitter.<anonymous> (file:///C:/Users/Admin/Desktop/Javascript/nodeJS/src/controller/whatApp.controller.js:96:39)
Emitted 'error' event on WebSocketClient instance at:
    at WebSocket.<anonymous> (C:\Users\Admin\Desktop\Javascript\nodeJS\node_modules\baileys\lib\Socket\Client\web-socket-client.js:46:100)      
    at WebSocket.emit (node:events:519:28)
    at emitErrorAndClose (C:\Users\Admin\Desktop\Javascript\nodeJS\node_modules\ws\lib\websocket.js:1041:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)|
    
    
    node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "1006".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

    
    Bug are node app crash while  the QR code are scanned.  if any one can help me to solve this.

**Comment by AnandPatel404** [comment]
can you give me a piece of code that you write

**Comment by priyanshuChovatiya** [comment]
> can you give me a piece of code that you write

Yes why not. Can you have same problem..?

**Comment by Zain-ul-din** [comment]
@spacesoft321 is it free?

**Comment by spacesoft321** [comment]
its not free , but he using same code for whatsapp api , he can send per day more than 500 marketing message on whatsapp , i dont know how its possible but his developer is good
