### ISSUE TITLE
[BUG] item-not-found 

### ISSUE THREAD

**Issue by Renlikesmoon** [WhiskeySockets/Baileys#1082]
Error: item-not-found
    at assertNodeErrorFree (/bot-wa/volks/node_modules/@whiskeysockets/baileys/lib/WABinary/generic-utils.js:56:15)
    at query (/bot-wa/volks/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:145:48)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async groupMetadata (/bot-wa/volks/node_modules/@whiskeysockets/baileys/lib/Socket/groups.js:22:24)
    at async /bot-wa/volks/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:323:41
    at async Promise.all (index 0)
    at async /bot-wa/volks/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:316:51
    at async Object.transaction (/bot-wa/volks/node_modules/@whiskeysockets/baileys/lib/Utils/auth-utils.js:136:26)
    at async relayMessage (/bot-wa/volks/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:306:9)
    at async Object.sendMessage (/bot-wa/volks/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:666:17) {
  data: 404,
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 500,
    payload: {
      statusCode: 500,
      error: 'Internal Server Error',
      message: 'An internal server error occurred'
    },
    headers: {}
  }
} unhandledRejection

**Comment by bobslavtriev** [comment]
Problem in your code!
