### ISSUE TITLE
[BUG] Internal Server Error - Some thing causing a connection lost

### ISSUE THREAD

**Issue by leonetosoft** [WhiskeySockets/Baileys#1084]
**Describe the bug**
I have only one connection with this instability.

**To Reproduce**
I don't know how to reproduce but I have logs

**Expected behavior**
Don't lost the connection

Trace:
```
{"level":10,"time":1728637928564,"pid":4009081,"hostname":"ip-172-31-18-52","name":"baileys","class":"ns","msg":"recv frame"}
{"level":10,"time":1728637928564,"pid":4009081,"hostname":"ip-172-31-18-52","name":"baileys","xml":"<stream:error >\n\t\t<ack class='receipt' type='read' id='6708391700a8a8dbec651ad5'/>\n</stream:error>","msg":"recv xml"}
{"level":50,"time":1728637928564,"pid":4009081,"hostname":"ip-172-31-18-52","name":"baileys","node":{"tag":"stream:error","attrs":{},"content":[{"tag":"ack","attrs":{"class":"receipt","type":"read","id":"6708391700a8a8dbec651ad5"}}]},"msg":"stream errored out"}
{"level":30,"time":1728637928564,"pid":4009081,"hostname":"ip-172-31-18-52","name":"baileys","trace":"Error: Stream Errored (ack)\n    at WebSocketClient.<anonymous> (/home/ubuntu/data/efs/zigchat-api-baileys/node_modules/baileys/lib/Socket/socket.js:524:13)\n    at WebSocketClient.emit (node:events:519:28)\n    at WebSocketClient.emit (node:domain:488:12)\n    at /home/ubuntu/data/efs/zigchat-api-baileys/node_modules/baileys/lib/Socket/socket.js:241:35\n    at Object.decodeFrame (/home/ubuntu/data/efs/zigchat-api-baileys/node_modules/baileys/lib/Utils/noise-handler.js:149:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","msg":"connection errored"}
{"level":10,"time":1728637928565,"pid":4009081,"hostname":"ip-172-31-18-52","name":"baileys","class":"ns","msg":"recv frame"}
{"level":10,"time":1728637928565,"pid":4009081,"hostname":"ip-172-31-18-52","name":"baileys","xml":"<xmlstreamend />","msg":"recv xml"}
{"level":10,"time":1728637928566,"pid":4009081,"hostname":"ip-172-31-18-52","name":"baileys","trace":"Error: Connection Terminated by Server\n    at WebSocketClient.<anonymous> (/home/ubuntu/data/efs/zigchat-api-baileys/node_modules/baileys/lib/Socket/socket.js:461:40)\n    at WebSocketClient.emit (node:events:519:28)\n    at WebSocketClient.emit (node:domain:488:12)\n    at /home/ubuntu/data/efs/zigchat-api-baileys/node_modules/baileys/lib/Socket/socket.js:241:35\n    at Object.decodeFrame (/home/ubuntu/data/efs/zigchat-api-baileys/node_modules/baileys/lib/Utils/noise-handler.js:149:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","msg":"connection already closed"}
{"level":10,"time":1728638224250,"pid":4009081,"hostname":"ip-172-31-18-52","name":"baileys","xml":"<presence name='CFC Grand Prix' type='available'/>","msg":"xml send"}
```

I receive this on connectio.update:
```
[11/10/2024 - 04:22:06.845]: {"connection":"close","lastDisconnect":{"error":{"data":{"tag":"stream:error","attrs":{},"content":[{"tag":"ack","attrs":{"class":"receipt","type":"read","id":"6708391700a8a8dbec651ad5"}}]},"isBoom":true,"isServer":true,"output":{"statusCode":500,"payload":{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"},"headers":{}}},"date":"2024-10-11T08:22:06.841Z"}}
```

**Comment by thereis** [comment]
Same here, stacktrace:

```
/app/node_modules/.pnpm/@whiskeysockets+baileys@6.7.8_sharp@0.33.5/node_modules/@whiskeysockets/baileys/lib/WABinary/generic-utils.js:56
        throw new boom_1.Boom(errNode.attrs.text || 'Unknown error', { data: +errNode.attrs.code });
              ^

Error: forbidden
    at assertNodeErrorFree (/app/node_modules/.pnpm/@whiskeysockets+baileys@6.7.8_sharp@0.33.5/node_modules/@whiskeysockets/baileys/lib/WABinary/generic-utils.js:56:15)
    at query (/app/node_modules/.pnpm/@whiskeysockets+baileys@6.7.8_sharp@0.33.5/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:145:48)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.groupMetadata (/app/node_modules/.pnpm/@whiskeysockets+baileys@6.7.8_sharp@0.33.5/node_modules/@whiskeysockets/baileys/lib/Socket/groups.js:22:24)
    at async WppSocketService.extractMessageInfo (/app/csbot-app/main.js:4023:30)
    at async /app/[REDACTED]/main.js:3996:33 {
  data: 403,
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 500,
    payload: {
      statusCode: 500,
      error: 'Internal Server Error',
      message: 'An internal server error occurred'
    },
    headers: {}
  }
}
```

**Comment by leonetosoft** [comment]
More logs: 
```
{"level":20,"time":1729120337504,"pid":614769,"hostname":"ip-172-31-18-52","name":"baileys","attrs":{"id":"67102050fd4b2f3b2be40c5e","recipient":"556791424695@s.whatsapp.net","type":"sender"},"messageIds":["67102050fd4b2f3b2be40c5e"],"msg":"sending receipt for messages"}
{"level":10,"time":1729120337504,"pid":614769,"hostname":"ip-172-31-18-52","name":"baileys","xml":"<receipt id='67102050fd4b2f3b2be40c5e' recipient='556791424695@s.whatsapp.net' type='sender'/>","msg":"xml send"}
{"level":20,"time":1729120337505,"pid":614769,"hostname":"ip-172-31-18-52","name":"baileys","attrs":{"id":"67102050fd4b2f3b2be40c5e","to":"556791424695@s.whatsapp.net","type":"hist_sync"},"messageIds":["67102050fd4b2f3b2be40c5e"],"msg":"sending receipt for messages"}
{"level":10,"time":1729120337505,"pid":614769,"hostname":"ip-172-31-18-52","name":"baileys","xml":"<receipt id='67102050fd4b2f3b2be40c5e' to='556791424695@s.whatsapp.net' type='hist_sync'/>","msg":"xml send"}
{"level":50,"time":1729120337506,"pid":614769,"hostname":"ip-172-31-18-52","name":"baileys","err":{"type":"TypeError","message":"Cannot read properties of undefined (reading 'id')","stack":"TypeError: Cannot read properties of undefined (reading 'id')\n    at sendMessageAck (/home/ubuntu/data/efs/zigchat-api-renato/node_modules/baileys/lib/Socket/messages-recv.js:59:27)\n    at /home/ubuntu/data/efs/zigchat-api-renato/node_modules/baileys/lib/Socket/messages-recv.js:721:27\n    at /home/ubuntu/data/efs/zigchat-api-renato/node_modules/baileys/lib/Utils/make-mutex.js:18:36"},"msg":"unexpected error in 'processing message'"}
{"level":20,"time":1729120337506,"pid":614769,"hostname":"ip-172-31-18-52","name":"baileys","recv":{"tag":"receipt","attrs":{"from":"556791511208:97@s.whatsapp.net","type":"read","id":"67102050fd4b2f3b2be40c5e","offline":"5","recipient":"556791424695@s.whatsapp.net","t":"1729110401"}},"sent":{"id":"67102050fd4b2f3b2be40c5e","to":"556791511208:97@s.whatsapp.net","class":"receipt","recipient":"556791424695@s.whatsapp.net","type":"read"},"msg":"sent ack"}
{"level":10,"time":1729120337506,"pid":614769,"hostname":"ip-172-31-18-52","name":"baileys","xml":"<ack id='67102050fd4b2f3b2be40c5e' to='556791511208:97@s.whatsapp.net' class='receipt' recipient='556791424695@s.whatsapp.net' type='read'/>","msg":"xml send"}
{"level":50,"time":1729120337512,"pid":614769,"hostname":"ip-172-31-18-52","name":"baileys","key":{"remoteJid":"556791424695:53@s.whatsapp.net","fromMe":false,"id":"671023992929a84ccfd1b1d6"},"err":{"type":"MessageCounterError","message":"Key used already or never filled","stack":"MessageCounterError: Key used already or never filled\n    at SessionCipher.doDecryptWhisperMessage (/home/ubuntu/data/efs/zigchat-api-renato/node_modules/libsignal/src/session_cipher.js:236:19)\n    at Object.556791424695.53 [as awaitable] (/home/ubuntu/data/efs/zigchat-api-renato/node_modules/libsignal/src/session_cipher.js:207:42)\n    at _asyncQueueExecutor (/home/ubuntu/data/efs/zigchat-api-renato/node_modules/libsignal/src/queue_job.js:20:29)","name":"MessageCounterError"},"msg":"failed to decrypt message"}
{"level":10,"time":1729120337620,"pid":614769,"hostname":"ip-172-31-18-52","name":"baileys","class":"ns","msg":"recv 63 bytes, total recv 63 bytes"}

```
