### ISSUE TITLE
[BUG] Timeout error in sock.updateProfilePicture

### ISSUE THREAD

**Issue by adithyan-hermit** [WhiskeySockets/Baileys#1086]
Error: Timed Out
    at /root/hermit-bot/node_modules/@WhiskeySockets/baileys/lib/Utils/generics.js:137:32 {
  data: {
    stack: 'Error\n' +
      '    at promiseTimeout (/root/hermit-bot/node_modules/@WhiskeySockets/baileys/lib/Utils/generics.js:132:19)\n' +
      '    at waitForMessage (/root/hermit-bot/node_modules/@WhiskeySockets/baileys/lib/Socket/socket.js:119:53)\n' +
      '    at Object.query (/root/hermit-bot/node_modules/@WhiskeySockets/baileys/lib/Socket/socket.js:141:22)\n' +
      '    at I.<computed> [as updateProfilePicture] (/root/hermit-bot/lib/function.js:1:310862)\n' +
      '    at async Object.function (/root/hermit-bot/plugins/>.js:48:14)\n' +
      '    at async /root/hermit-bot/lib/handler.js:1:154349'
  },
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 408,
    payload: {
      statusCode: 408,
      error: 'Request Time-out',
      message: 'Timed Out'
    },
    headers: {}
  }
}

**Comment by Skidy89** [comment]
update to 6.7.8

**Comment by M3264** [comment]
> update to 6.7.8

Works well
Thanks bro👍
