### ISSUE TITLE
[BUG] Error 403 on downloading media

### ISSUE THREAD

**Issue by Rubens-Gasparotto** [WhiskeySockets/Baileys#1094]
**Describe the bug**
Sometimes, when trying to download a message using the `downloadMediaMessage` function, it throws 403 error. I've noticed this happens mostly with PDF files.

**To Reproduce**
1. Receive a message event
3. Try to download it using the `downloadMediaMessage` function
4. Sometimes works, but other times it doesnt

**Expected behavior**
Media should download successfully

**Environment (please complete the following information):**
 - Is this on a server? Yes
 - What do your `connectOptions` look like? 
 ```typescript
 makeWASocket({
    version, // v2.3000.1015901307
    logger: pinoLogger,
    printQRInTerminal: false,
    auth: {
        creds: state.creds,
        keys: addTransactionCapability(state.keys, pinoLogger, { maxCommitRetries: 10, delayBetweenTriesMs: 250 }),
    },
    msgRetryCounterCache: new NodeCache(),
    syncFullHistory: false,
    getMessage: async (key: WAMessageKey) => {
        if (projectScope.store) {
            const msg = await projectScope.store.loadMessage(key.remoteJid!, key.id!)
            return msg?.message || undefined
        }

        return Baileys.Message.fromObject({})
    },
    shouldSyncHistoryMessage: msg => {
        console.log(`Syncing chats [${msg.progress}%] - Type: ${msg.syncType}`);

        this.session.syncing = msg.progress !== 100;

        return !!msg.syncType;
    }
});
```
 - Do you have multiple clients on the same IP? No
 - Are you using a proxy? No

**Additional context**
Console error

```
error:    Unhandled Rejection: AxiosError: Request failed with status code 403
    at settle (/home/node/app/node_modules/axios/dist/node/axios.cjs:1983:12)
    at RedirectableRequest.handleResponse (/home/node/app/node_modules/axios/dist/node/axios.cjs:3033:9)
    at RedirectableRequest.emit (node:events:519:28)
    at RedirectableRequest._processResponse (/home/node/app/node_modules/follow-redirects/index.js:398:10)
    at RedirectableRequest._onNativeResponse (/home/node/app/node_modules/follow-redirects/index.js:91:12)
    at Object.onceWrapper (node:events:634:26)
    at ClientRequest.emit (node:events:519:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:698:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:540:22)
    at Axios.request (/home/node/app/node_modules/axios/dist/node/axios.cjs:4224:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getHttpStream (/home/node/app/node_modules/@whiskeysockets/baileys/lib/Utils/messages-media.js:320:21)
    at async downloadEncryptedContent (/home/node/app/node_modules/@whiskeysockets/baileys/lib/Utils/messages-media.js:453:21)
    at async downloadMsg (/home/node/app/node_modules/@whiskeysockets/baileys/lib/Utils/messages.js:733:24)
    at async downloadMediaMessage (/home/node/app/node_modules/@whiskeysockets/baileys/lib/Utils/messages.js:693:20)
    at async MediaManagerUtil.downloadMedia (/home/node/app/api/baileys/utils/mediaManager.util.js:19:24)
    at async WatizeMessageFormatUtil.format (/home/node/app/api/baileys/utils/watize-message-format.util.js:187:45)
    at async SessionBaileysConnect.receiveMessage (/home/node/app/api/baileys/layers/base.layer.js:281:34)
```

**Comment by lucasdoctype** [comment]
Same problem

**Comment by starksemihyarar** [comment]
mr @purpshell you was said that you already looking the problem did u find a way? now problem continues with whatsapp web sent jpeg or jpg images.

ı try to send jpeg on whatsapp web different number to baileyssocket connected number ı am faced with this issue on every sent 

Iam using latest version of library : (package.json)
````
"@whiskeysockets/baileys": "^6.7.13",
````


my code snippet is below:
```
 conn.ev.on("messages.upsert", async msg => {
        // console.log("messages.upsert", util.inspect(msg, false, null, true ))
        try {
            if (msg.type === "notify") {
                // msg.messages.forEach(( _m) => {

                for (let _m of msg.messages) {
                    // MEDIA
                    let m = _m;
                    var full_file_name = null
                    const messageType = Object.keys (m.message)[0]
                    console.log("Message Paylaod Data", m)
                    if (messageType !== 'conversation') {

                        // download the message
                        try {
                            const buffer = await downloadMediaMessage(
                                m,
                                'buffer',
                                { },
                                {
                                    pino_logger,
                                    // pass this so that baileys can request a reupload of media
                                    // that has been deleted
                                    reuploadRequest:  conn.updateMediaMessage
                                }
                            )

                            const filename = "wpclientdownload_pn_" + m.key.remoteJid + "_" + m.key.id +"_"+ generateRandomString(10)
                            const extension = m.message[messageType].mimetype.split("/")
                            full_file_name = filename+'.'+extension[1].split(";")[0]
                            await writeFile(_dirname+'/public/files/'+full_file_name, buffer)

                        }catch (e) {
                            console.log("DownloadMediaMessage Error Message", e.message)
                        }
                    }
                    //#END - MEDIA

                    const message = [];
                    let from = _m.key.remoteJid.split('@');
                    let number = from[1] ?? null;

                    message.downloaded_attachment = full_file_name

                    let number_domain = !(number == "s.whatsapp.net");
                    if (number_domain == false) {
                        message.remote_id = _m.key.remoteJid;
                        message.sessionId = _device_id;
                        message.message_id = _m.key.id;
                        message.message = _m.message;
                        message.is_echo = _m.key?.fromMe;

                        sentWebHook(_device_id, message);
                    }
                // })
                }
            }

        } catch (e) { //console.log("ERROR",e)
             }
    });
```

Console logs are:

```
Message Paylaod Data {
  key: {
    remoteJid: 'xxxx@s.whatsapp.net',
    fromMe: false,
    id: '3EB0429021CCBF7EF2xxx',
    participant: undefined
  },
  messageTimestamp: 1740733355,
  pushName: '.',
  broadcast: false,
  message: Message {
    imageMessage: ImageMessage {
      interactiveAnnotations: [],
      scanLengths: [],
      annotations: [],
      url: 'https://mmg.whatsapp.net/o1/v/t62.7118-24/f2/m238/AQM9G5mMezpTJBw4_nGfqWqEuP0cbdyLhuDB_9cxNjk2xe4IxaifUqWQLEsmE70kH16A_Lys9PIrnRIMtGkkAmIzmJNibYb5k3HKT-K_GQ?ccb=9-4&oh=01_Q5AaIIQ_9u_Iz7nA-Y4GMlQA-2k54u0z4kn6_qLwVF4B9-Jc&oe=67B5FC8C&_nc_sid=e6ed6c&mms3=true',
      mimetype: 'image/jpeg',
      fileSha256: [Uint8Array],
      fileLength: [Long],
      height: 723,
      width: 1024,
      mediaKey: [Uint8Array],
      fileEncSha256: [Uint8Array],
      directPath: '/o1/v/t62.7118-24/f2/m238/AQOXGirXOO56WXHeYuLaYG0AQAwX3-J4xT8Vjw9Cqpo1bTASaZdlUMM4c0SbgxdNnQV0XcnewjCfmXcXr16xHp8IyRXPh_0FKEKxeD6xaw?ccb=9-4&oh=01_Q5AaIPA86YOetCHov46FUlddY3cxSdlZIxMR1HXe_aaHn20O&oe=67E8D285&_nc_sid=e6ed6c',
      mediaKeyTimestamp: [Long],
      jpegThumbnail: [Uint8Array],
      contextInfo: [ContextInfo],
      viewOnce: false
    },
    messageContextInfo: MessageContextInfo {
      deviceListMetadata: [DeviceListMetadata],
      deviceListMetadataVersion: 2,
      messageSecret: [Uint8Array]
    }
  }
}
DownloadMediaMessage Error Message Request failed with status code 403

```

when ı try to send photo via phone is success here is the debug log 

```
Message Paylaod Data {
  key: {
    remoteJid: 'xxxx@s.whatsapp.net',
    fromMe: false,
    id: '3AC0BE6E1CB4541xxxx',
    participant: undefined
  },
  messageTimestamp: 1740733602,
  pushName: '.',
  broadcast: false,
  message: Message {
    imageMessage: ImageMessage {
      interactiveAnnotations: [],
      scanLengths: [Array],
      annotations: [],
      url: 'https://mmg.whatsapp.net/v/t62.7118-24/26562083_1745269239538155_3811506545329627056_n.enc?ccb=11-4&oh=01_Q5AaIPS-CUhOxpXxfkUWXLG7DqaYeJ4b83eJkYDek_gOoqFZ&oe=67E8EE2F&_nc_sid=5e03e0&mms3=true',
      mimetype: 'image/jpeg',
      fileSha256: [Uint8Array],
      fileLength: [Long],
      height: 2048,
      width: 1152,
      mediaKey: [Uint8Array],
      fileEncSha256: [Uint8Array],
      directPath: '/v/t62.7118-24/26562083_1745269239538155_3811506545329627056_n.enc?ccb=11-4&oh=01_Q5AaIPS-CUhOxpXxfkUWXLG7DqaYeJ4b83eJkYDek_gOoqFZ&oe=67E8EE2F&_nc_sid=5e03e0',
      mediaKeyTimestamp: [Long],
      jpegThumbnail: [Uint8Array],
      firstScanSidecar: [Uint8Array],
      firstScanLength: 18435,
      scansSidecar: [Uint8Array],
      midQualityFileSha256: [Uint8Array]
    },
    messageContextInfo: MessageContextInfo {
      deviceListMetadata: [DeviceListMetadata],
      deviceListMetadataVersion: 2,
      messageSecret: [Uint8Array]
    }
  }
}


```

I noticed success one has ".enc" in url maybe problem related with this ı dont know. Thanks for help.
