### ISSUE TITLE
[BUG] commands that including whatsapp profile picture wont work on whatsapp business

### ISSUE THREAD

**Issue by seanopegs** [WhiskeySockets/Baileys#1100]
Error: Connection Closed
    at sendRawMessage (/home/container/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:57:19)
    at sendNode (/home/container/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:76:16)
    at query (/home/container/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:140:15)
    at /home/container/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:28:38
    at refreshMediaConn (/home/container/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:49:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.upload (/home/container/node_modules/@whiskeysockets/baileys/lib/Utils/messages-media.js:528:26)
    at async /home/container/node_modules/@whiskeysockets/baileys/lib/Utils/messages.js:122:28
    at async Promise.all (index 0)
    at async prepareWAMessageMedia (/home/container/node_modules/@whiskeysockets/baileys/lib/Utils/messages.js:120:40) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 428,
    payload: {
      statusCode: 428,
      error: 'Precondition Required',
      message: 'Connection Closed'
    },
    headers: {}
  }
}

**Comment by seanopegs** [comment]
not profile picture, just image in general

**Comment by AstroX11** [comment]
lol
