### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Fann-level-MAX** [WhiskeySockets/Baileys#1133]
**Describe the bug**
"Cannot read properties of undefined" error when trying to connect with sock.requestPairingCode() in Windows environment

**To Reproduce**
```
const { makeWASocket, Browsers, useMultiFileAuthState, DisconnectReason, fetchLatestBaileysVersion, makeCacheableSignalKeyStore } = (await import('@whiskeysockets/baileys'))
import NodeCache from 'node-cache'

const msgRetryCounterCache = new NodeCache()
const P = (await import('pino')).default({ level: 'silent' })
const log = console.log;

const { state, saveCreds } = await useMultiFileAuthState('session')
const { version, isLatest } = await fetchLatestBaileysVersion()
const sock = makeWASocket({
    auth: {
        creds: state.creds,
        keys: makeCacheableSignalKeyStore(state.keys, P)
    },
    browser: Browsers.windows,
    version,
    printQRInTerminal: false,
    defaultQueryTimeoutMs: undefined,
    msgRetryCounterCache
})

sock.ev.on('creds.update', saveCreds)

if (!sock.authState.creds.registered) {
    const code = await sock.requestPairingCode('62.........64')
    log('Your pairing code:', code)
}

sock.ev.on('connection.update', ({connection, lastDisconnect}) => {
    if (connection === 'close') {
        if (lastDisconnect?.error?.output?.statusCode !== DisconnectReason.loggedOut) {
            log('Connection closed. Restarting...')
        } else {
            log('Connection closed. You are logged out.')
        }
    } else if (connection === 'open') log('Connected successfully')
})
```

**Expected behavior**
This code is working fine in linux environment

**Environment (please complete the following information):**
 - Is this on a server?
> nope
 - What do your `connectOptions` look like? 
```
 {
    auth: {
        creds: state.creds,
        keys: makeCacheableSignalKeyStore(state.keys, P)
    },
    browser: Browsers.windows,
    version,
    printQRInTerminal: false,
    defaultQueryTimeoutMs: undefined,
    msgRetryCounterCache
}
```
 - Do you have multiple clients on the same IP?
> nope
 - Are you using a proxy?
 > nope

**Additional context**
Full log : 
> D:\fann\node_modules\@whiskeysockets\baileys\lib\Utils\generics.js:56
>     const platformType = WAProto_1.proto.DeviceProps.PlatformType[browser.toUpperCase()];
> ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎  ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎^
> 
> TypeError: Cannot read properties of undefined (reading 'toUpperCase')
>     at getPlatformId (D:\fann\node_modules\@whiskeysockets\baileys\lib\Utils\generics.js:56:75)
>     at Object.requestPairingCode (D:\fann\node_modules\@whiskeysockets\baileys\lib\Socket\socket.js:401:64)
>     at async file:///D:/fann/index.js:25:18
> 
> Node.js v20.18.0

**Comment by Fann-level-MAX** [comment]
Similar behavior happend when tried to connect with QR code

here's full error log

```
  {
    "level": 30,
    "time": "2024-11-14T02:38:46.926Z",
    "pid": 7208,
    "hostname": "NASI_GORENG",
    "class": "baileys",
    "helloMsg": {
      "clientHello": {
        "ephemeral": "mKV2p0W7fnLJmST71dPuVJ1M86DNJyKc09mPFOx2ynM="
      }
    },
    "msg": "connected to WA"
  },
  {
    "level": 30,
    "time": "2024-11-14T02:38:47.119Z",
    "pid": 7208,
    "hostname": "NASI_GORENG",
    "class": "baileys",
    "node": {
      "username": "6285866079364",
      "passive": true,
      "userAgent": {
        "platform": "WEB",
        "appVersion": {
          "primary": 2,
          "secondary": 3000,
          "tertiary": 1017531287
        },
        "osVersion": "0.1",
        "device": "Desktop",
        "osBuildNumber": "0.1",
        "releaseChannel": "RELEASE",
        "localeLanguageIso6391": "en",
        "localeCountryIso31661Alpha2": "US"
      },
      "webInfo": {
        "webSubPlatform": "WEB_BROWSER"
      },
      "connectType": "WIFI_UNKNOWN",
      "connectReason": "USER_ACTIVATED"
    },
    "msg": "logging in..."
  },
  {
    "level": 30,
    "time": "2024-11-14T02:38:49.422Z",
    "pid": 7208,
    "hostname": "NASI_GORENG",
    "class": "baileys",
    "trace": "Error: Connection Failure\n    at WebSocketClient.<anonymous> (D:\\fann\\node_modules\\@whiskeysockets\\baileys\\lib\\Socket\\socket.js:524:13)\n    at WebSocketClient.emit (node:events:519:28)\n    at D:\\fann\\node_modules\\@whiskeysockets\\baileys\\lib\\Socket\\socket.js:236:35\n    at Object.decodeFrame (D:\\fann\\node_modules\\@whiskeysockets\\baileys\\lib\\Utils\\noise-handler.js:144:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
    "msg": "connection errored"
  }
```

**Comment by Akkun3704** [comment]
> **Describe the bug** "Cannot read properties of undefined" error when trying to connect with sock.requestPairingCode() in Windows environment
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> ```
> const { makeWASocket, Browsers, useMultiFileAuthState, DisconnectReason, fetchLatestBaileysVersion, makeCacheableSignalKeyStore } = (await import('@whiskeysockets/baileys'))
> import NodeCache from 'node-cache'
> 
> const msgRetryCounterCache = new NodeCache()
> const P = (await import('pino')).default({ level: 'silent' })
> const log = console.log;
> 
> const { state, saveCreds } = await useMultiFileAuthState('session')
> const { version, isLatest } = await fetchLatestBaileysVersion()
> const sock = makeWASocket({
>     auth: {
>         creds: state.creds,
>         keys: makeCacheableSignalKeyStore(state.keys, P)
>     },
>     browser: Browsers.windows,
>     version,
>     printQRInTerminal: false,
>     defaultQueryTimeoutMs: undefined,
>     msgRetryCounterCache
> })
> 
> sock.ev.on('creds.update', saveCreds)
> 
> if (!sock.authState.creds.registered) {
>     const code = await sock.requestPairingCode('62.........64')
>     log('Your pairing code:', code)
> }
> 
> sock.ev.on('connection.update', ({connection, lastDisconnect}) => {
>     if (connection === 'close') {
>         if (lastDisconnect?.error?.output?.statusCode !== DisconnectReason.loggedOut) {
>             log('Connection closed. Restarting...')
>         } else {
>             log('Connection closed. You are logged out.')
>         }
>     } else if (connection === 'open') log('Connected successfully')
> })
> ```
> 
> **Expected behavior** This code is working fine in linux environment
> 
> **Environment (please complete the following information):**
> 
> * Is this on a server?
> 
> > nope
> 
> * What do your `connectOptions` look like?
> 
> ```
>  {
>     auth: {
>         creds: state.creds,
>         keys: makeCacheableSignalKeyStore(state.keys, P)
>     },
>     browser: Browsers.windows,
>     version,
>     printQRInTerminal: false,
>     defaultQueryTimeoutMs: undefined,
>     msgRetryCounterCache
> }
> ```
> 
> * Do you have multiple clients on the same IP?
> 
> > nope
> 
> * Are you using a proxy?
> 
> > nope
> 
> **Additional context** Full log :
> 
> > D:\fann\node_modules@whiskeysockets\baileys\lib\Utils\generics.js:56
> > const platformType = WAProto_1.proto.DeviceProps.PlatformType[browser.toUpperCase()];
> > ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎  ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎^
> > TypeError: Cannot read properties of undefined (reading 'toUpperCase')
> > at getPlatformId (D:\fann\node_modules@whiskeysockets\baileys\lib\Utils\generics.js:56:75)
> > at Object.requestPairingCode (D:\fann\node_modules@whiskeysockets\baileys\lib\Socket\socket.js:401:64)
> > at async file:///D:/fann/index.js:25:18
> > Node.js v20.18.0

You must fill in browser name in Browsers.windows

```js
browser: Browsers.windows('Chrome'),
```

**Comment by Fann-level-MAX** [comment]
> > **Describe the bug** "Cannot read properties of undefined" error when trying to connect with sock.requestPairingCode() in Windows environment
> > **To Reproduce** Steps to reproduce the behavior:
> > ```
> > const { makeWASocket, Browsers, useMultiFileAuthState, DisconnectReason, fetchLatestBaileysVersion, makeCacheableSignalKeyStore } = (await import('@whiskeysockets/baileys'))
> > import NodeCache from 'node-cache'
> > 
> > const msgRetryCounterCache = new NodeCache()
> > const P = (await import('pino')).default({ level: 'silent' })
> > const log = console.log;
> > 
> > const { state, saveCreds } = await useMultiFileAuthState('session')
> > const { version, isLatest } = await fetchLatestBaileysVersion()
> > const sock = makeWASocket({
> >     auth: {
> >         creds: state.creds,
> >         keys: makeCacheableSignalKeyStore(state.keys, P)
> >     },
> >     browser: Browsers.windows,
> >     version,
> >     printQRInTerminal: false,
> >     defaultQueryTimeoutMs: undefined,
> >     msgRetryCounterCache
> > })
> > 
> > sock.ev.on('creds.update', saveCreds)
> > 
> > if (!sock.authState.creds.registered) {
> >     const code = await sock.requestPairingCode('62.........64')
> >     log('Your pairing code:', code)
> > }
> > 
> > sock.ev.on('connection.update', ({connection, lastDisconnect}) => {
> >     if (connection === 'close') {
> >         if (lastDisconnect?.error?.output?.statusCode !== DisconnectReason.loggedOut) {
> >             log('Connection closed. Restarting...')
> >         } else {
> >             log('Connection closed. You are logged out.')
> >         }
> >     } else if (connection === 'open') log('Connected successfully')
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Expected behavior** This code is working fine in linux environment
> > **Environment (please complete the following information):**
> > 
> > * Is this on a server?
> > 
> > > nope
> > 
> > 
> > 
> > * What do your `connectOptions` look like?
> > 
> > ```
> >  {
> >     auth: {
> >         creds: state.creds,
> >         keys: makeCacheableSignalKeyStore(state.keys, P)
> >     },
> >     browser: Browsers.windows,
> >     version,
> >     printQRInTerminal: false,
> >     defaultQueryTimeoutMs: undefined,
> >     msgRetryCounterCache
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * Do you have multiple clients on the same IP?
> > 
> > > nope
> > 
> > 
> > 
> > * Are you using a proxy?
> > 
> > > nope
> > 
> > 
> > **Additional context** Full log :
> > > D:\fann\node_modules@whiskeysockets\baileys\lib\Utils\generics.js:56
> > > const platformType = WAProto_1.proto.DeviceProps.PlatformType[browser.toUpperCase()];
> > > ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎  ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎^
> > > TypeError: Cannot read properties of undefined (reading 'toUpperCase')
> > > at getPlatformId (D:\fann\node_modules@whiskeysockets\baileys\lib\Utils\generics.js:56:75)
> > > at Object.requestPairingCode (D:\fann\node_modules@whiskeysockets\baileys\lib\Socket\socket.js:401:64)
> > > at async file:///D:/fann/index.js:25:18
> > > Node.js v20.18.0
> 
> You must fill in browser name in Browsers.windows
> 
> ```js
> browser: Browsers.windows('Chrome'),
> ```

thank u so much :+1:
