### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Vortex853** [WhiskeySockets/Baileys#1145]
**Describe the bug**

**To Reproduce**

When sending a keyword to receive a response (text message), I get this error.

`2024-11-23T21:48:20: Media or text message error: TypeError: Cannot read properties of null (reading 'split')
2024-11-23T21:48:20:     at Object.get_url_extension (/www/wwwroot/waziper/waziper/common.js:488:17)
2024-11-23T21:48:20:     at Object.ext2mime (/www/wwwroot/waziper/waziper/common.js:492:24)
2024-11-23T21:48:20:     at Object.auto_send (/www/wwwroot/waziper/waziper/waziper.js:885:62)
2024-11-23T21:48:20:     at runMicrotasks (<anonymous>)
2024-11-23T21:48:20:     at processTicksAndRejections (node:internal/process/task_queues:96:5)`

**Expected behavior**

**Environment (please complete the following information):**
 - Is this on a server? yes
 - What do your `connectOptions` look like?  QR code working
 - Do you have multiple clients on the same IP? yes
 - Are you using a proxy? no

**Comment by MuhammadRestu999** [comment]
learn basic JavaScript first.
