### ISSUE TITLE
[BUG] Get Piring Code Error 405, 428

### ISSUE THREAD

**Issue by alands-offc** [WhiskeySockets/Baileys#1156]
Error:
```
~/chat-ai $ node index
Baileys version: 2,3000,1017531287 (Latest: true)
Menghasilkan pairing code...
Error saat menghasilkan pairing code: Error: Connection Closed
    at sendRawMessage (/data/data/com.termux/files/home/chat-ai/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:57:19)
    at sendNode (/data/data/com.termux/files/home/chat-ai/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:76:16)
    at Object.requestPairingCode (/data/data/com.termux/files/home/chat-ai/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:370:15)
    at async run (file:///data/data/com.termux/files/home/chat-ai/index.js:75:20) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 428,
    payload: {
      statusCode: 428,
      error: 'Precondition Required',
      message: 'Connection Closed'
    },
    headers: {}
  }
}
Koneksi terputus, alasan: 405
Memulai ulang sistem...
Baileys version: 2,3000,1017531287 (Latest: true)
Menghasilkan pairing code...
Code: GW7F-2M9T
Koneksi terputus, alasan: 428
Memulai ulang sistem...
Baileys version: 2,3000,1017531287 (Latest: true)
Menghasilkan pairing code...
Code: M5HB-ESXW
Koneksi terputus, alasan: 428
Memulai ulang sistem...
Baileys version: 2,3000,1017531287 (Latest: true)
Menghasilkan pairing code...
Code: 28CW-HEQ6
Koneksi terputus, alasan: 405
Memulai ulang sistem...
Baileys version: 2,3000,1017531287 (Latest: true)
Menghasilkan pairing code...
Code: H84S-ZN2N
Koneksi terputus, alasan: 428
Memulai ulang sistem...
Baileys version: 2,3000,1017531287 (Latest: true)
Menghasilkan pairing code...
Koneksi terputus, alasan: 408
Memulai ulang sistem...
Baileys version: 2,3000,1017531287 (Latest: true)
Menghasilkan pairing code...
Error saat menghasilkan pairing code: Error: Connection Closed
    at sendRawMessage (/data/data/com.termux/files/home/chat-ai/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:57:19)
    at sendNode (/data/data/com.termux/files/home/chat-ai/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:76:16)
    at Object.requestPairingCode (/data/data/com.termux/files/home/chat-ai/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:370:15)
    at async run (file:///data/data/com.termux/files/home/chat-ai/index.js:75:20) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 428,
    payload: {
      statusCode: 428,
      error: 'Precondition Required',
      message: 'Connection Closed'
    },
    headers: {}
  }
}
Error saat menghasilkan pairing code: Error: Connection Closed
    at sendRawMessage (/data/data/com.termux/files/home/chat-ai/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:57:19)
    at sendNode (/data/data/com.termux/files/home/chat-ai/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:76:16)
    at Object.requestPairingCode (/data/data/com.termux/files/home/chat-ai/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:370:15)
    at async run (file:///data/data/com.termux/files/home/chat-ai/index.js:75:20) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 428,
    payload: {
      statusCode: 428,
      error: 'Precondition Required',
      message: 'Connection Closed'
    },
    headers: {}
  }
}
^C
~/chat-ai $
```
my code:
```
import alxzym, {
  useMultiFileAuthState,
  Browsers,
  fetchLatestBaileysVersion,
  makeCacheableSignalKeyStore,
  makeInMemoryStore,
  jidNormalizedUser
} from "@whiskeysockets/baileys";
import "./lib/global.js";
import { Boom } from "@hapi/boom";
import Pino from "pino";

const nomor = "6282196729298";
async function run() {
  const { state, saveCreds } = await useMultiFileAuthState("./s");
  const logger = Pino({ timestamp: () => `,"time":"${new Date().toISOString()}"` }).child({ class: "ALXZY" });
  logger.level = "fatal";

  const store = makeInMemoryStore({ logger });

  const { version, isLatest } = await fetchLatestBaileysVersion();
  console.log(`Baileys version: ${version} (Latest: ${isLatest})`);

  const alxzy = alxzym.default({
    logger,
    printQRInTerminal: false,
    auth: {
      creds: state.creds,
      keys: makeCacheableSignalKeyStore(state.keys, logger),
    },
    browser: Browsers.windows("Chrome"),
    getMessage: async key => {
      const jid = jidNormalizedUser(key.remoteJid);
      const msg = await store.loadMessage(jid, key.id);
      return msg?.message || "";
    },
    shouldSyncHistoryMessage: msg => {
      console.log(`\x1b[32mMemuat Chat [${msg.progress}%]\x1b[39m`);
      return !!msg.syncType;
    },
  });

  alxzy.ev.on("connection.update", async update => {
    const { connection, lastDisconnect, isOnline } = update;
    if (connection === "close") {
      const reason = new Boom(lastDisconnect?.error)?.output.statusCode;
      console.error(`Koneksi terputus, alasan: ${reason}`);
      console.log("Memulai ulang sistem...");
      run();
    } else if (connection === "open") {
      console.log(`Sistem berhasil dinyalakan. AV terhubung di ${nomor}`);
    } else if (isOnline) {
      console.log(`Bot online sebagai: ${alxzy.user?.name}`);
    }
  });
 store.bind(alxzy.ev);
  alxzy.ev.on("messages.upsert", async pesan => {
    console.log("Pesan baru:", pesan);
  });

  alxzy.ev.on("creds.update", saveCreds);

  // Generate pairing code
  try {
    if (!alxzy.authState.creds.registered) {
      const nomorBot = nomor.replace(/[^0-9]/g, "");
      console.log("Menghasilkan pairing code...");
      const code = await alxzy.requestPairingCode(nomorBot);
      console.log(`Code: ${code?.match(/.{1,4}/g)?.join("-")}`);
    }
  } catch (error) {
    console.error("Error saat menghasilkan pairing code:", error);
  }
}

run();
```

**Comment by ahlaiptek** [comment]
Coba hapus folder state, lalu ulang

**Comment by alands-offc** [comment]
> Coba hapus folder state, lalu ulang

sama aja

**Comment by Akkun3704** [comment]
> Error:
> 
> ```
> ~/chat-ai $ node index
> Baileys version: 2,3000,1017531287 (Latest: true)
> Menghasilkan pairing code...
> Error saat menghasilkan pairing code: Error: Connection Closed
>     at sendRawMessage (/data/data/com.termux/files/home/chat-ai/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:57:19)
>     at sendNode (/data/data/com.termux/files/home/chat-ai/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:76:16)
>     at Object.requestPairingCode (/data/data/com.termux/files/home/chat-ai/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:370:15)
>     at async run (file:///data/data/com.termux/files/home/chat-ai/index.js:75:20) {
>   data: null,
>   isBoom: true,
>   isServer: false,
>   output: {
>     statusCode: 428,
>     payload: {
>       statusCode: 428,
>       error: 'Precondition Required',
>       message: 'Connection Closed'
>     },
>     headers: {}
>   }
> }
> Koneksi terputus, alasan: 405
> Memulai ulang sistem...
> Baileys version: 2,3000,1017531287 (Latest: true)
> Menghasilkan pairing code...
> Code: GW7F-2M9T
> Koneksi terputus, alasan: 428
> Memulai ulang sistem...
> Baileys version: 2,3000,1017531287 (Latest: true)
> Menghasilkan pairing code...
> Code: M5HB-ESXW
> Koneksi terputus, alasan: 428
> Memulai ulang sistem...
> Baileys version: 2,3000,1017531287 (Latest: true)
> Menghasilkan pairing code...
> Code: 28CW-HEQ6
> Koneksi terputus, alasan: 405
> Memulai ulang sistem...
> Baileys version: 2,3000,1017531287 (Latest: true)
> Menghasilkan pairing code...
> Code: H84S-ZN2N
> Koneksi terputus, alasan: 428
> Memulai ulang sistem...
> Baileys version: 2,3000,1017531287 (Latest: true)
> Menghasilkan pairing code...
> Koneksi terputus, alasan: 408
> Memulai ulang sistem...
> Baileys version: 2,3000,1017531287 (Latest: true)
> Menghasilkan pairing code...
> Error saat menghasilkan pairing code: Error: Connection Closed
>     at sendRawMessage (/data/data/com.termux/files/home/chat-ai/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:57:19)
>     at sendNode (/data/data/com.termux/files/home/chat-ai/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:76:16)
>     at Object.requestPairingCode (/data/data/com.termux/files/home/chat-ai/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:370:15)
>     at async run (file:///data/data/com.termux/files/home/chat-ai/index.js:75:20) {
>   data: null,
>   isBoom: true,
>   isServer: false,
>   output: {
>     statusCode: 428,
>     payload: {
>       statusCode: 428,
>       error: 'Precondition Required',
>       message: 'Connection Closed'
>     },
>     headers: {}
>   }
> }
> Error saat menghasilkan pairing code: Error: Connection Closed
>     at sendRawMessage (/data/data/com.termux/files/home/chat-ai/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:57:19)
>     at sendNode (/data/data/com.termux/files/home/chat-ai/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:76:16)
>     at Object.requestPairingCode (/data/data/com.termux/files/home/chat-ai/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:370:15)
>     at async run (file:///data/data/com.termux/files/home/chat-ai/index.js:75:20) {
>   data: null,
>   isBoom: true,
>   isServer: false,
>   output: {
>     statusCode: 428,
>     payload: {
>       statusCode: 428,
>       error: 'Precondition Required',
>       message: 'Connection Closed'
>     },
>     headers: {}
>   }
> }
> ^C
> ~/chat-ai $
> ```
> 
> my code:
> 
> ```
> import alxzym, {
>   useMultiFileAuthState,
>   Browsers,
>   fetchLatestBaileysVersion,
>   makeCacheableSignalKeyStore,
>   makeInMemoryStore,
>   jidNormalizedUser
> } from "@whiskeysockets/baileys";
> import "./lib/global.js";
> import { Boom } from "@hapi/boom";
> import Pino from "pino";
> 
> const nomor = "6282196729298";
> async function run() {
>   const { state, saveCreds } = await useMultiFileAuthState("./s");
>   const logger = Pino({ timestamp: () => `,"time":"${new Date().toISOString()}"` }).child({ class: "ALXZY" });
>   logger.level = "fatal";
> 
>   const store = makeInMemoryStore({ logger });
> 
>   const { version, isLatest } = await fetchLatestBaileysVersion();
>   console.log(`Baileys version: ${version} (Latest: ${isLatest})`);
> 
>   const alxzy = alxzym.default({
>     logger,
>     printQRInTerminal: false,
>     auth: {
>       creds: state.creds,
>       keys: makeCacheableSignalKeyStore(state.keys, logger),
>     },
>     browser: Browsers.windows("Chrome"),
>     getMessage: async key => {
>       const jid = jidNormalizedUser(key.remoteJid);
>       const msg = await store.loadMessage(jid, key.id);
>       return msg?.message || "";
>     },
>     shouldSyncHistoryMessage: msg => {
>       console.log(`\x1b[32mMemuat Chat [${msg.progress}%]\x1b[39m`);
>       return !!msg.syncType;
>     },
>   });
> 
>   alxzy.ev.on("connection.update", async update => {
>     const { connection, lastDisconnect, isOnline } = update;
>     if (connection === "close") {
>       const reason = new Boom(lastDisconnect?.error)?.output.statusCode;
>       console.error(`Koneksi terputus, alasan: ${reason}`);
>       console.log("Memulai ulang sistem...");
>       run();
>     } else if (connection === "open") {
>       console.log(`Sistem berhasil dinyalakan. AV terhubung di ${nomor}`);
>     } else if (isOnline) {
>       console.log(`Bot online sebagai: ${alxzy.user?.name}`);
>     }
>   });
>  store.bind(alxzy.ev);
>   alxzy.ev.on("messages.upsert", async pesan => {
>     console.log("Pesan baru:", pesan);
>   });
> 
>   alxzy.ev.on("creds.update", saveCreds);
> 
>   // Generate pairing code
>   try {
>     if (!alxzy.authState.creds.registered) {
>       const nomorBot = nomor.replace(/[^0-9]/g, "");
>       console.log("Menghasilkan pairing code...");
>       const code = await alxzy.requestPairingCode(nomorBot);
>       console.log(`Code: ${code?.match(/.{1,4}/g)?.join("-")}`);
>     }
>   } catch (error) {
>     console.error("Error saat menghasilkan pairing code:", error);
>   }
> }
> 
> run();
> ```

Hmm... maybe you must wait until baileys connection is fully open before request pairing code.

Try this
```js
// Generate pairing code
try {
  if (!alxzy.authState.creds.registered) {
    await alxzy.waitForConnectionUpdate((update) => !!update.qr)
    const nomorBot = nomor.replace(/[^0-9]/g, "");
    console.log("Menghasilkan pairing code...");
    const code = await alxzy.requestPairingCode(nomorBot);
    console.log(`Code: ${code?.match(/.{1,4}/g)?.join("-")}`);
  }
} catch (error) {
  console.error("Error saat menghasilkan pairing code:", error);
}
```

**Comment by alands-offc** [comment]
> > Error:
> > ```
> > ~/chat-ai $ node index
> > Baileys version: 2,3000,1017531287 (Latest: true)
> > Menghasilkan pairing code...
> > Error saat menghasilkan pairing code: Error: Connection Closed
> >     at sendRawMessage (/data/data/com.termux/files/home/chat-ai/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:57:19)
> >     at sendNode (/data/data/com.termux/files/home/chat-ai/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:76:16)
> >     at Object.requestPairingCode (/data/data/com.termux/files/home/chat-ai/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:370:15)
> >     at async run (file:///data/data/com.termux/files/home/chat-ai/index.js:75:20) {
> >   data: null,
> >   isBoom: true,
> >   isServer: false,
> >   output: {
> >     statusCode: 428,
> >     payload: {
> >       statusCode: 428,
> >       error: 'Precondition Required',
> >       message: 'Connection Closed'
> >     },
> >     headers: {}
> >   }
> > }
> > Koneksi terputus, alasan: 405
> > Memulai ulang sistem...
> > Baileys version: 2,3000,1017531287 (Latest: true)
> > Menghasilkan pairing code...
> > Code: GW7F-2M9T
> > Koneksi terputus, alasan: 428
> > Memulai ulang sistem...
> > Baileys version: 2,3000,1017531287 (Latest: true)
> > Menghasilkan pairing code...
> > Code: M5HB-ESXW
> > Koneksi terputus, alasan: 428
> > Memulai ulang sistem...
> > Baileys version: 2,3000,1017531287 (Latest: true)
> > Menghasilkan pairing code...
> > Code: 28CW-HEQ6
> > Koneksi terputus, alasan: 405
> > Memulai ulang sistem...
> > Baileys version: 2,3000,1017531287 (Latest: true)
> > Menghasilkan pairing code...
> > Code: H84S-ZN2N
> > Koneksi terputus, alasan: 428
> > Memulai ulang sistem...
> > Baileys version: 2,3000,1017531287 (Latest: true)
> > Menghasilkan pairing code...
> > Koneksi terputus, alasan: 408
> > Memulai ulang sistem...
> > Baileys version: 2,3000,1017531287 (Latest: true)
> > Menghasilkan pairing code...
> > Error saat menghasilkan pairing code: Error: Connection Closed
> >     at sendRawMessage (/data/data/com.termux/files/home/chat-ai/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:57:19)
> >     at sendNode (/data/data/com.termux/files/home/chat-ai/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:76:16)
> >     at Object.requestPairingCode (/data/data/com.termux/files/home/chat-ai/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:370:15)
> >     at async run (file:///data/data/com.termux/files/home/chat-ai/index.js:75:20) {
> >   data: null,
> >   isBoom: true,
> >   isServer: false,
> >   output: {
> >     statusCode: 428,
> >     payload: {
> >       statusCode: 428,
> >       error: 'Precondition Required',
> >       message: 'Connection Closed'
> >     },
> >     headers: {}
> >   }
> > }
> > Error saat menghasilkan pairing code: Error: Connection Closed
> >     at sendRawMessage (/data/data/com.termux/files/home/chat-ai/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:57:19)
> >     at sendNode (/data/data/com.termux/files/home/chat-ai/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:76:16)
> >     at Object.requestPairingCode (/data/data/com.termux/files/home/chat-ai/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:370:15)
> >     at async run (file:///data/data/com.termux/files/home/chat-ai/index.js:75:20) {
> >   data: null,
> >   isBoom: true,
> >   isServer: false,
> >   output: {
> >     statusCode: 428,
> >     payload: {
> >       statusCode: 428,
> >       error: 'Precondition Required',
> >       message: 'Connection Closed'
> >     },
> >     headers: {}
> >   }
> > }
> > ^C
> > ~/chat-ai $
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > my code:
> > ```
> > import alxzym, {
> >   useMultiFileAuthState,
> >   Browsers,
> >   fetchLatestBaileysVersion,
> >   makeCacheableSignalKeyStore,
> >   makeInMemoryStore,
> >   jidNormalizedUser
> > } from "@whiskeysockets/baileys";
> > import "./lib/global.js";
> > import { Boom } from "@hapi/boom";
> > import Pino from "pino";
> > 
> > const nomor = "6282196729298";
> > async function run() {
> >   const { state, saveCreds } = await useMultiFileAuthState("./s");
> >   const logger = Pino({ timestamp: () => `,"time":"${new Date().toISOString()}"` }).child({ class: "ALXZY" });
> >   logger.level = "fatal";
> > 
> >   const store = makeInMemoryStore({ logger });
> > 
> >   const { version, isLatest } = await fetchLatestBaileysVersion();
> >   console.log(`Baileys version: ${version} (Latest: ${isLatest})`);
> > 
> >   const alxzy = alxzym.default({
> >     logger,
> >     printQRInTerminal: false,
> >     auth: {
> >       creds: state.creds,
> >       keys: makeCacheableSignalKeyStore(state.keys, logger),
> >     },
> >     browser: Browsers.windows("Chrome"),
> >     getMessage: async key => {
> >       const jid = jidNormalizedUser(key.remoteJid);
> >       const msg = await store.loadMessage(jid, key.id);
> >       return msg?.message || "";
> >     },
> >     shouldSyncHistoryMessage: msg => {
> >       console.log(`\x1b[32mMemuat Chat [${msg.progress}%]\x1b[39m`);
> >       return !!msg.syncType;
> >     },
> >   });
> > 
> >   alxzy.ev.on("connection.update", async update => {
> >     const { connection, lastDisconnect, isOnline } = update;
> >     if (connection === "close") {
> >       const reason = new Boom(lastDisconnect?.error)?.output.statusCode;
> >       console.error(`Koneksi terputus, alasan: ${reason}`);
> >       console.log("Memulai ulang sistem...");
> >       run();
> >     } else if (connection === "open") {
> >       console.log(`Sistem berhasil dinyalakan. AV terhubung di ${nomor}`);
> >     } else if (isOnline) {
> >       console.log(`Bot online sebagai: ${alxzy.user?.name}`);
> >     }
> >   });
> >  store.bind(alxzy.ev);
> >   alxzy.ev.on("messages.upsert", async pesan => {
> >     console.log("Pesan baru:", pesan);
> >   });
> > 
> >   alxzy.ev.on("creds.update", saveCreds);
> > 
> >   // Generate pairing code
> >   try {
> >     if (!alxzy.authState.creds.registered) {
> >       const nomorBot = nomor.replace(/[^0-9]/g, "");
> >       console.log("Menghasilkan pairing code...");
> >       const code = await alxzy.requestPairingCode(nomorBot);
> >       console.log(`Code: ${code?.match(/.{1,4}/g)?.join("-")}`);
> >     }
> >   } catch (error) {
> >     console.error("Error saat menghasilkan pairing code:", error);
> >   }
> > }
> > 
> > run();
> > ```
> 
> Hmm... maybe you must wait until baileys connection is fully open before request pairing code.
> 
> Try this
> 
> ```js
> // Generate pairing code
> try {
>   if (!alxzy.authState.creds.registered) {
>     await alxzy.waitForConnectionUpdate((update) => !!update.qr)
>     const nomorBot = nomor.replace(/[^0-9]/g, "");
>     console.log("Menghasilkan pairing code...");
>     const code = await alxzy.requestPairingCode(nomorBot);
>     console.log(`Code: ${code?.match(/.{1,4}/g)?.join("-")}`);
>   }
> } catch (error) {
>   console.error("Error saat menghasilkan pairing code:", error);
> }
> ```

I found a new problem, namely when I finished linking the device, it could not connect to WhatsApp.
```
~/chat-ai $ node index
Wa version: 2,3000,1017531287 (Latest: true)
/data/data/com.termux/files/home/chat-ai/node_modules/@whiskeysockets/baileys/lib/Utils/generics.js:170
            .then(() => reject(new boom_1.Boom('Timed Out', {
                               ^

Error: Timed Out
    at /data/data/com.termux/files/home/chat-ai/node_modules/@whiskeysockets/baileys/lib/Utils/generics.js:170:32 {
  data: {
    stack: 'Error\n' +
      '    at promiseTimeout (/data/data/com.termux/files/home/chat-ai/node_modules/@whiskeysockets/baileys/lib/Utils/generics.js:165:19)\n' +
      '    at waitForMessage (/data/data/com.termux/files/home/chat-ai/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:117:53)\n' +
      '    at query (/data/data/com.termux/files/home/chat-ai/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:139:22)\n' +
      '    at getAvailablePreKeysOnServer (/data/data/com.termux/files/home/chat-ai/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:179:30)\n' +
      '    at uploadPreKeysToServerIfRequired (/data/data/com.termux/files/home/chat-ai/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:205:35)\n' +
      '    at WebSocketClient.<anonymous> (/data/data/com.termux/files/home/chat-ai/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:509:15)\n' +
      '    at WebSocketClient.emit (node:events:519:28)\n' +
      '    at /data/data/com.termux/files/home/chat-ai/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:236:35\n' +
      '    at Object.decodeFrame (/data/data/com.termux/files/home/chat-ai/node_modules/@whiskeysockets/baileys/lib/Utils/noise-handler.js:144:17)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
  },
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 408,
    payload: {
      statusCode: 408,
      error: 'Request Time-out',
      message: 'Timed Out'
    },
    headers: {}
  }
}

Node.js v20.17.0
~/chat-ai $
```

**Comment by mohammad-montaser** [comment]
Did you find the solution?
