### ISSUE TITLE
[BUG] 428 ERROR CODE When I try to send an image

### ISSUE THREAD

**Issue by andrevitxr** [WhiskeySockets/Baileys#1160]
error: Erro ao enviar imagem para 553499082484@s.whatsapp.net: Error: Connection Closed
    at sendRawMessage (C:\Users\Usuário\Desktop\whatzapp\node_modules\@whiskeysockets\baileys\lib\Socket\socket.js:57:19)
    at sendNode (C:\Users\Usuário\Desktop\whatzapp\node_modules\@whiskeysockets\baileys\lib\Socket\socket.js:76:16)
    at query (C:\Users\Usuário\Desktop\whatzapp\node_modules\@whiskeysockets\baileys\lib\Socket\socket.js:140:15)
    at C:\Users\Usuário\Desktop\whatzapp\node_modules\@whiskeysockets\baileys\lib\Socket\messages-send.js:28:38
    at refreshMediaConn (C:\Users\Usuário\Desktop\whatzapp\node_modules\@whiskeysockets\baileys\lib\Socket\messages-send.js:49:15)    
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.upload (C:\Users\Usuário\Desktop\whatzapp\node_modules\@whiskeysockets\baileys\lib\Utils\messages-media.js:528:26)    at async C:\Users\Usuário\Desktop\whatzapp\node_modules\@whiskeysockets\baileys\lib\Utils\messages.js:122:28
    at async Promise.all (index 0)
    at async prepareWAMessageMedia (C:\Users\Usuário\Desktop\whatzapp\node_modules\@whiskeysockets\baileys\lib\Utils\messages.js:120:40) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 428,
    payload: {
      statusCode: 428,
      error: 'Precondition Required',
      message: 'Connection Closed'
    },
    headers: {}
  }
}

**Comment by purpshell** [comment]
Can you give us more information? Is this reproducible enough? If so can you run the socket in trace mode and send us the logs?

**Comment by mohammad-montaser** [comment]
Do you see an error, error 1006?
