### ISSUE TITLE
[BUG] CONNECTION CLOSE WHEN I TRYING TO SEND A MESSAGE

### ISSUE THREAD

**Issue by Cristopher8049** [WhiskeySockets/Baileys#119]
I have an error when I try to send a message `await sock.sendMessage(id, { text: 'oh hello there' })`

I catch this error

/Users/cristopheroconnor/Documents/projects/endpoint_multipagos/priebas/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:55
            throw new boom_1.Boom('Connection Closed', { statusCode: Types_1.DisconnectReason.connectionClosed });
                  ^

Error: Connection Closed
    at sendRawMessage (/Users/cristopheroconnor/Documents/projects/endpoint_multipagos/priebas/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:55:19)
    at sendNode (/Users/cristopheroconnor/Documents/projects/endpoint_multipagos/priebas/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:74:16)
    at query (/Users/cristopheroconnor/Documents/projects/endpoint_multipagos/priebas/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:140:15)
    at getUSyncDevices (/Users/cristopheroconnor/Documents/projects/endpoint_multipagos/priebas/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:166:30)
    at /Users/cristopheroconnor/Documents/projects/endpoint_multipagos/priebas/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:347:53
    at Object.transaction (/Users/cristopheroconnor/Documents/projects/endpoint_multipagos/priebas/node_modules/@whiskeysockets/baileys/lib/Utils/auth-utils.js:136:32)
    at relayMessage (/Users/cristopheroconnor/Documents/projects/endpoint_multipagos/priebas/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:276:30)
    at Object.sendMessage (/Users/cristopheroconnor/Documents/projects/endpoint_multipagos/priebas/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:637:23)
    at async connect (/Users/cristopheroconnor/Documents/projects/endpoint_multipagos/priebas/index.js:26:3) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 428,
    payload: {
      statusCode: 428,
      error: 'Precondition Required',
      message: 'Connection Closed'
    },
    headers: {}
  }
}

Node.js v18.12.1
"@whiskeysockets/baileys": "^6.2.1"

**Comment by journeyANDloneliness** [comment]
this happened if u didn't save the contact who send messages. any solution?

**Comment by journeyANDloneliness** [comment]
so anonimous number can't send u messages

**Comment by sudomaaz** [comment]
Having this issue and i t occurs in groups with large participants.. Any update on this ?

**Comment by sudomaaz** [comment]
I have raised an MR for this issue. Please check @adiwajshing 

https://github.com/WhiskeySockets/Baileys/pull/233

**Comment by weershft** [comment]
@Cristopher8049 Has your problem been resolved?

Please, help me ->
https://github.com/WhiskeySockets/Baileys/issues/492

**Comment by elMassexy** [comment]
A mi me pasa lo mismo alguien encontro la solucion por favor ayuda

**Comment by clogg74** [comment]
Stil no solution, I m having this problem too.

**Comment by sersawy** [comment]
@Cristopher8049  did you solve this?
