### ISSUE TITLE
[BUG] Connection closed but not catched.

### ISSUE THREAD

**Issue by rbcet** [WhiskeySockets/Baileys#131]
**Describe the bug**
```
Jun 12 22:00:03 raspberrypi node[1022692]: /home/pi/whatsapp-baileys/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:55
Jun 12 22:00:03 raspberrypi node[1022692]:             throw new boom_1.Boom('Connection Closed', { statusCode: Types_1.DisconnectReason.connectionClosed });
Jun 12 22:00:03 raspberrypi node[1022692]:                   ^
Jun 12 22:00:03 raspberrypi node[1022692]: Error: Connection Closed
Jun 12 22:00:03 raspberrypi node[1022692]:     at sendRawMessage (/home/pi/whatsapp-baileys/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:55:19)
Jun 12 22:00:03 raspberrypi node[1022692]:     at sendNode (/home/pi/whatsapp-baileys/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:74:16)
Jun 12 22:00:03 raspberrypi node[1022692]:     at query (/home/pi/whatsapp-baileys/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:140:15)
Jun 12 22:00:03 raspberrypi node[1022692]:     at groupQuery (/home/pi/whatsapp-baileys/node_modules/@whiskeysockets/baileys/lib/Socket/groups.js:12:55)
Jun 12 22:00:03 raspberrypi node[1022692]:     at groupMetadata (/home/pi/whatsapp-baileys/node_modules/@whiskeysockets/baileys/lib/Socket/groups.js:22:30)
Jun 12 22:00:03 raspberrypi node[1022692]:     at /home/pi/whatsapp-baileys/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:286:47
Jun 12 22:00:03 raspberrypi node[1022692]:     at /home/pi/whatsapp-baileys/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:289:23
Jun 12 22:00:03 raspberrypi node[1022692]:     at Object.transaction (/home/pi/whatsapp-baileys/node_modules/@whiskeysockets/baileys/lib/Utils/auth-utils.js:136:32)
Jun 12 22:00:03 raspberrypi node[1022692]:     at relayMessage (/home/pi/whatsapp-baileys/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:276:30)
Jun 12 22:00:03 raspberrypi node[1022692]:     at Object.sendMessage (/home/pi/whatsapp-baileys/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:637:23) {
Jun 12 22:00:03 raspberrypi node[1022692]:   data: null,
Jun 12 22:00:03 raspberrypi node[1022692]:   isBoom: true,
Jun 12 22:00:03 raspberrypi node[1022692]:   isServer: false,
Jun 12 22:00:03 raspberrypi node[1022692]:   output: {
Jun 12 22:00:03 raspberrypi node[1022692]:     statusCode: 428,
Jun 12 22:00:03 raspberrypi node[1022692]:     payload: {
Jun 12 22:00:03 raspberrypi node[1022692]:       statusCode: 428,
Jun 12 22:00:03 raspberrypi node[1022692]:       error: 'Precondition Required',
Jun 12 22:00:03 raspberrypi node[1022692]:       message: 'Connection Closed'
Jun 12 22:00:03 raspberrypi node[1022692]:     },
Jun 12 22:00:03 raspberrypi node[1022692]:     headers: {}
Jun 12 22:00:03 raspberrypi node[1022692]:   }
Jun 12 22:00:03 raspberrypi node[1022692]: }
```

**To Reproduce**
1 - It happens  sometimes when you send a message.

**Expected behavior**
```
        sock.ev.on('connection.update', async (update) => {
            const { connection, lastDisconnect } = update
            if(connection === 'close') {
                let reason = new Boom(lastDisconnect?.error)?.output.statusCode

                if (reason !== DisconnectReason.loggedOut) {
                connectToWhatsApp();
```
I have something like this, which catches almost all connection events except this. So in the end, process exits due to this problem. Expected behaviour is catching this connectionCloseError. 

**Environment (please complete the following information):**
 - Is this on a server? - Raspberrypi running headless as systemctl service.
 - What do your `connectOptions` look like?           ` printQRInTerminal: true, auth: state, shouldSyncHistoryMessage: false`
 - Do you have multiple clients on the same IP? Single whatsapp-baileys instance.
 - Are you using a proxy? No. 

**Additional context**
connection.update is not triggered when this occurs.

**Comment by ChargerMc** [comment]
+1

**Comment by journeyANDloneliness** [comment]
this happened if u didn't save the contact who send messages. any solution?

**Comment by morrisseybr** [comment]
+1, any news?

**Comment by mrodriguezbegueri** [comment]
Hi guys, i had that problem when i tried to send a message. I get the problem solved saving the client in memory with a key ang get it before sending the message.

I hope you find it useful
