### ISSUE TITLE
error in receiving message [BUG]

### ISSUE THREAD

**Issue by techie311** [WhiskeySockets/Baileys#217]
**Describe the bug**
I wrote my code ran it
my script
```
const { Boom } = require('@hapi/boom');
const NodeCache = require('node-cache');
const wa = require('@whiskeysockets/baileys');
const makeWASocket = wa.default;
const {
    AnyMessageContent, 
    delay, 
    DisconnectReason, 
    fetchLatestBaileysVersion, 
    getAggregateVotesInPollMessage, 
    makeCacheableSignalKeyStore, 
    makeInMemoryStore, 
    PHONENUMBER_MCC, 
    proto, 
    useMultiFileAuthState, 
    WAMessageContent, 
    WAMessageKey
  } = wa

const MAIN_LOGGER = require('@whiskeysockets/baileys/lib/Utils/logger').default;


const logger = MAIN_LOGGER;
logger.level = 'trace';

const useStore = !process.argv.includes('--no-store');
const doReplies = !process.argv.includes('--no-reply');

// external map to store retry counts of messages when decryption/encryption fails
// keep this out of the socket itself, so as to prevent a message decryption/encryption loop 
const msgRetryCounterCache = new NodeCache();

// the store maintains the data of the WA connection in memory
// can be written out to a file & read from it
const store = useStore ? makeInMemoryStore({ logger }) : undefined;
if (store) {
    store.readFromFile('baileys_store_multi.json')
};

// save every 10s
setInterval(() => {
	if (store) store.writeToFile('./baileys_store_multi.json');
}, 10_000);

// start a connection
const startSock = async() => {
	const { state, saveCreds } = await useMultiFileAuthState('baileys_auth_info');
    // fetch latest version of WA Web
	const { version, isLatest } = await fetchLatestBaileysVersion();
	console.log(`using WA v${version.join('.')}, isLatest: ${isLatest}`);

	const sock = makeWASocket({
		version,
		printQRInTerminal: true,
		auth: {
			creds: state.creds,
            /** caching makes the store faster to send/recv messages */
			keys: makeCacheableSignalKeyStore(state.keys),
		},
		msgRetryCounterCache,
		generateHighQualityLinkPreview: true,
        // ignore all broadcast messages -- to receive the same
		// comment the line below out
		// shouldIgnoreJid: jid => isJidBroadcast(jid),
		// implement to handle retries & poll updates
		getMessage,
	});

	store && store.bind(sock.ev);

	const sendMessageWTyping = async(msg, jid) => {
		await sock.presenceSubscribe(jid);
		await delay(500);
		await sock.sendPresenceUpdate('composing', jid);
		await delay(2000);
		await sock.sendPresenceUpdate('paused', jid);
		await sock.sendMessage(jid, msg);
	};
    // the process function lets you process all events that just occurred
	// efficiently in a batch
	sock.ev.process(
        // events is a map for event name => event data
		async(events) => {
            // something about the connection changed
			// maybe it closed, or we received all offline message or connection opened
			if(events['connection.update']) {
                console.log(`*********************************************************\nconnection update\n*********************************************************`)
				const update = events['connection.update'];
				const { connection, lastDisconnect } = update;
				if(connection === 'close') {
                    // reconnect if not logged out
					if((lastDisconnect.error.output.statusCode !== DisconnectReason.loggedOut)) {
						startSock();
					} else {
						console.log('Connection closed. You are logged out.');
					}
				}

				console.log('connection update', update);
			}
            // credentials updated -- save them
			if(events['creds.update']) {
				await saveCreds();
			}

			if(events.call) {
                console.log(`*********************************************************\nevents.call\n*********************************************************`)
				console.log('recv call event', events.call);
			}
            // history received
			if(events['messaging-history.set']) {
				const { chats, contacts, messages, isLatest } = events['messaging-history.set'];
                console.log(`*********************************************************\nhistory received\n*********************************************************`)
				console.log(`recv ${chats.length} chats, ${contacts.length} contacts, ${messages.length} msgs (is latest: ${isLatest})`)
			}

			// received a new message
			if (events['messages.upsert']) {
                console.log(`*********************************************************\nnew message received\n*********************************************************`)
                const upsert = events['messages.upsert'];
                console.log('recv messages ', JSON.stringify(`message : ${upsert.messages}\nType:${upsert.type}`, undefined, 2));
            
                if (upsert.type === 'notify') {
                    for (const msg of upsert.messages) {
                        if (!msg.key.fromMe && doReplies) {
                            console.log('replying to', msg.key.remoteJid);
                            await sock.readMessages([msg.key]);
                            await sendMessageWTyping({ text: 'Hello there!' }, msg.key.remoteJid);
                        }
                    }
                }
            }
            // messages updated like status delivered, message deleted etc.
            if (events['messages.update']) {
                console.log(`*********************************************************\nmessage updated\n*********************************************************`)
                console.log(JSON.stringify(events['messages.update'], undefined, 2));
            
                for (const { key, update } of events['messages.update']) {
                    if (update.pollUpdates) {
                        const pollCreation = await getMessage(key);
                        if (pollCreation) {
                            console.log(
                                'got poll update, aggregation: ',
                                getAggregateVotesInPollMessage({
                                    message: pollCreation,
                                    pollUpdates: update.pollUpdates,
                                })
                            );
                        }
                    }
                }
            }
            
            if (events['message-receipt.update']) {
                console.log(`*********************************************************\nReciept update\n*********************************************************`)
                console.log(events['message-receipt.update']);
            }
            
            if (events['messages.reaction']) {
                console.log(`*********************************************************\nReaction\n*********************************************************`)
                console.log(events['messages.reaction']);
            }
            
            if (events['presence.update']) {
                console.log(`*********************************************************\npresence update\n*********************************************************`)
                console.log(events['presence.update']);
            }
            
            if (events['chats.update']) {
                console.log(`*********************************************************\nchat update\n*********************************************************`)
                console.log(events['chats.update']);
            }
            
            if (events['contacts.update']) {
                console.log(`*********************************************************\ncontact update\n*********************************************************`)
                for (const contact of events['contacts.update']) {
                    if (typeof contact.imgUrl !== 'undefined') {
                        const newUrl = contact.imgUrl === null
                            ? null
                            : await sock.profilePictureUrl(contact.id).catch(() => null);
                        console.log(
                            `contact ${contact.id} has a new profile pic: ${newUrl}`,
                        );
                    }
                }
            }
            
            if (events['chats.delete']) {
                console.log(`*********************************************************\nchat deleted\n*********************************************************`)
                console.log('chats deleted ', events['chats.delete']);
            }
		}
	)

	

	async function getMessage(key) {
        console.log(`*********************************************************\ngetting message\n*********************************************************`)
        if (store) {
            const msg = await store.loadMessage(key.remoteJid, key.id);
            return msg?.message || undefined;
        }
    
        // only if store is present
        return proto.Message.fromObject({});
    }
}

startSock();

```

it connected to the whatsapp
sent me qr code scanned
said connection open
then if it gets any message it sends error my whole console
```
{"level":20,"time":"2023-07-02T12:22:25.020Z","pid":21476,"hostname":"DESKTOP-6V6Q0T1","path":"baileys_store_multi.json","msg":"reading from file"}
using WA v2.2325.3, isLatest: true
*********************************************************
connection update
*********************************************************
connection update {
  connection: 'connecting',
  receivedPendingNotifications: false,
  qr: undefined
}
{"level":30,"time":"2023-07-02T12:22:25.806Z","pid":21476,"hostname":"DESKTOP-6V6Q0T1","class":"baileys","browser":["Baileys","Chrome","4.0.0"],"helloMsg":{"clientHello":{"ephemeral":"fbP76PCChjVmQEe95o7VNb/abs1earG6/qDiqLe4O0o="}},"msg":"connected to WA"}
{"level":30,"time":"2023-07-02T12:22:26.061Z","pid":21476,"hostname":"DESKTOP-6V6Q0T1","class":"baileys","node":{"username":"6580480815","passive":true,"userAgent":{"platform":"MACOS","appVersion":{"primary":2,"secondary":2325,"tertiary":3},"mcc":"000","mnc":"000","osVersion":"0.1","manufacturer":"","device":"Desktop","osBuildNumber":"0.1","releaseChannel":"RELEASE","localeLanguageIso6391":"en","localeCountryIso31661Alpha2":"US"},"connectType":"WIFI_UNKNOWN","connectReason":"USER_ACTIVATED","device":83},"msg":"logging in..."}
{"level":30,"time":"2023-07-02T12:22:26.526Z","pid":21476,"hostname":"DESKTOP-6V6Q0T1","class":"baileys","msg":"22 pre-keys found on server"}
{"level":30,"time":"2023-07-02T12:22:26.720Z","pid":21476,"hostname":"DESKTOP-6V6Q0T1","class":"baileys","msg":"opened connection to WA"}
*********************************************************
connection update
*********************************************************
connection update { isOnline: true }
*********************************************************
connection update
*********************************************************
connection update { connection: 'open' }
{"level":30,"time":"2023-07-02T12:22:26.756Z","pid":21476,"hostname":"DESKTOP-6V6Q0T1","class":"baileys","msg":"handled 0 offline messages/notifications"}    
*********************************************************
connection update
*********************************************************
connection update { receivedPendingNotifications: true }
```
above this after i connected to my script i already scanned and stored login
then i tried to send a message in a group called saved messages where i am the only participant 
which is the number i scanned for logging in the message was apple
the below is after i sent the message
```
{"level":50,"time":"2023-07-02T12:22:52.936Z","pid":21476,"hostname":"DESKTOP-6V6Q0T1","class":"baileys","key":{"remoteJid":"120363022528539354@g.us","fromMe":true,"id":"478BE0090B142EA7B7","participant":"6580480815:26@s.whatsapp.net"},"err":{"type":"TypeError","message":"Cannot read properties of undefined (reading 'trace')","stack":"TypeError: Cannot read properties of undefined (reading 'trace')\n    at Object.get (D:\\projects\\Whatsapp_bot\\node_modules\\@whiskeysockets\\baileys\\lib\\Utils\\auth-utils.js:42:24)\n    at Object.get (D:\\projects\\Whatsapp_bot\\node_modules\\@whiskeysockets\\baileys\\lib\\Utils\\auth-utils.js:111:30)\n    at Object.loadSession (D:\\projects\\Whatsapp_bot\\node_modules\\@whiskeysockets\\baileys\\lib\\Signal\\libsignal.js:104:47)\n    at SessionCipher.getRecord (D:\\projects\\Whatsapp_bot\\node_modules\\libsignal\\src\\session_cipher.js:49:43)\n    at 6580480815:26.0 [as awaitable] (D:\\projects\\Whatsapp_bot\\node_modules\\libsignal\\src\\session_cipher.js:196:37)\n    at _asyncQueueExecutor (D:\\projects\\Whatsapp_bot\\node_modules\\libsignal\\src\\queue_job.js:20:39)\n    at module.exports (D:\\projects\\Whatsapp_bot\\node_modules\\libsignal\\src\\queue_job.js:66:9)\n    at SessionCipher.queueJob (D:\\projects\\Whatsapp_bot\\node_modules\\libsignal\\src\\session_cipher.js:62:22)\n    at SessionCipher.decryptPreKeyWhisperMessage (D:\\projects\\Whatsapp_bot\\node_modules\\libsignal\\src\\session_cipher.js:195:27)\n    at Object.decryptMessage (D:\\projects\\Whatsapp_bot\\node_modules\\@whiskeysockets\\baileys\\lib\\Signal\\libsignal.js:54:44)"},"msg":"failed to decrypt message"}
{"level":50,"time":"2023-07-02T12:22:52.943Z","pid":21476,"hostname":"DESKTOP-6V6Q0T1","class":"baileys","key":{"remoteJid":"120363022528539354@g.us","fromMe":true,"id":"478BE0090B142EA7B7","participant":"6580480815:26@s.whatsapp.net"},"err":{"type":"TypeError","message":"Cannot read properties of undefined (reading 'trace')","stack":"TypeError: Cannot read properties of undefined (reading 'trace')\n    at Object.get (D:\\projects\\Whatsapp_bot\\node_modules\\@whiskeysockets\\baileys\\lib\\Utils\\auth-utils.js:42:24)\n    at Object.get (D:\\projects\\Whatsapp_bot\\node_modules\\@whiskeysockets\\baileys\\lib\\Utils\\auth-utils.js:111:30)\n    at Object.loadSenderKey (D:\\projects\\Whatsapp_bot\\node_modules\\@whiskeysockets\\baileys\\lib\\Signal\\libsignal.js:134:49)\n    at GroupCipher.decrypt (D:\\projects\\Whatsapp_bot\\node_modules\\@whiskeysockets\\baileys\\WASignalGroup\\group_cipher.js:38:46)\n    at Object.decryptGroupMessage (D:\\projects\\Whatsapp_bot\\node_modules\\@whiskeysockets\\baileys\\lib\\Signal\\libsignal.js:36:27)\n    at decrypt (D:\\projects\\Whatsapp_bot\\node_modules\\@whiskeysockets\\baileys\\lib\\Utils\\decode-wa-message.js:112:62)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async D:\\projects\\Whatsapp_bot\\node_modules\\@whiskeysockets\\baileys\\lib\\Socket\\messages-recv.js:463:17\n    at async D:\\projects\\Whatsapp_bot\\node_modules\\@whiskeysockets\\baileys\\lib\\Utils\\make-mutex.js:18:36\n    at async Promise.all (index 0)"},"msg":"failed to decrypt message"}
{"level":30,"time":"2023-07-02T12:22:52.959Z","pid":21476,"hostname":"DESKTOP-6V6Q0T1","class":"baileys","msgAttrs":{"from":"120363022528539354@g.us","type":"text","id":"478BE0090B142EA7B7","participant":"6580480815:26@s.whatsapp.net","count":"0","addressing_mode":"pn","notify":"Ahnaan","t":"1688300572"},"retryCount":1,"msg":"sent retry receipt"}
{"level":50,"time":"2023-07-02T12:22:53.445Z","pid":21476,"hostname":"DESKTOP-6V6Q0T1","class":"baileys","key":{"remoteJid":"120363022528539354@g.us","fromMe":true,"id":"478BE0090B142EA7B7","participant":"6580480815:26@s.whatsapp.net"},"err":{"type":"TypeError","message":"Cannot read properties of undefined (reading 'trace')","stack":"TypeError: Cannot read properties of undefined (reading 'trace')\n    at Object.get (D:\\projects\\Whatsapp_bot\\node_modules\\@whiskeysockets\\baileys\\lib\\Utils\\auth-utils.js:42:24)\n    at Object.get (D:\\projects\\Whatsapp_bot\\node_modules\\@whiskeysockets\\baileys\\lib\\Utils\\auth-utils.js:111:30)\n    at Object.loadSession (D:\\projects\\Whatsapp_bot\\node_modules\\@whiskeysockets\\baileys\\lib\\Signal\\libsignal.js:104:47)\n    at SessionCipher.getRecord (D:\\projects\\Whatsapp_bot\\node_modules\\libsignal\\src\\session_cipher.js:49:43)\n    at 6580480815:26.0 [as awaitable] (D:\\projects\\Whatsapp_bot\\node_modules\\libsignal\\src\\session_cipher.js:196:37)\n    at _asyncQueueExecutor (D:\\projects\\Whatsapp_bot\\node_modules\\libsignal\\src\\queue_job.js:20:39)\n    at module.exports (D:\\projects\\Whatsapp_bot\\node_modules\\libsignal\\src\\queue_job.js:66:9)\n    at SessionCipher.queueJob (D:\\projects\\Whatsapp_bot\\node_modules\\libsignal\\src\\session_cipher.js:62:22)\n    at SessionCipher.decryptPreKeyWhisperMessage (D:\\projects\\Whatsapp_bot\\node_modules\\libsignal\\src\\session_cipher.js:195:27)\n    at Object.decryptMessage (D:\\projects\\Whatsapp_bot\\node_modules\\@whiskeysockets\\baileys\\lib\\Signal\\libsignal.js:54:44)"},"msg":"failed to decrypt message"}
{"level":30,"time":"2023-07-02T12:22:53.470Z","pid":21476,"hostname":"DESKTOP-6V6Q0T1","class":"baileys","msgAttrs":{"from":"120363022528539354@g.us","type":"text","id":"478BE0090B142EA7B7","participant":"6580480815:26@s.whatsapp.net","addressing_mode":"pn","notify":"Ahnaan","t":"1688300573"},"retryCount":2,"msg":"sent retry receipt"}
{"level":40,"time":"2023-07-02T12:22:53.472Z","pid":21476,"hostname":"DESKTOP-6V6Q0T1","class":"baileys","msg":"failed to commit 1 mutations, tries left=9"}
{"level":50,"time":"2023-07-02T12:22:54.010Z","pid":21476,"hostname":"DESKTOP-6V6Q0T1","class":"baileys","key":{"remoteJid":"120363022528539354@g.us","fromMe":true,"id":"478BE0090B142EA7B7","participant":"6580480815:26@s.whatsapp.net"},"err":{"type":"TypeError","message":"Cannot read properties of undefined (reading 'trace')","stack":"TypeError: Cannot read properties of undefined (reading 'trace')\n    at Object.get (D:\\projects\\Whatsapp_bot\\node_modules\\@whiskeysockets\\baileys\\lib\\Utils\\auth-utils.js:42:24)\n    at Object.get (D:\\projects\\Whatsapp_bot\\node_modules\\@whiskeysockets\\baileys\\lib\\Utils\\auth-utils.js:97:48)\n    at Object.loadSession (D:\\projects\\Whatsapp_bot\\node_modules\\@whiskeysockets\\baileys\\lib\\Signal\\libsignal.js:104:47)\n    at SessionCipher.getRecord (D:\\projects\\Whatsapp_bot\\node_modules\\libsignal\\src\\session_cipher.js:49:43)\n    at 6580480815:26.0 [as awaitable] (D:\\projects\\Whatsapp_bot\\node_modules\\libsignal\\src\\session_cipher.js:196:37)\n    at _asyncQueueExecutor (D:\\projects\\Whatsapp_bot\\node_modules\\libsignal\\src\\queue_job.js:20:39)\n    at module.exports (D:\\projects\\Whatsapp_bot\\node_modules\\libsignal\\src\\queue_job.js:66:9)\n    at SessionCipher.queueJob (D:\\projects\\Whatsapp_bot\\node_modules\\libsignal\\src\\session_cipher.js:62:22)\n    at SessionCipher.decryptPreKeyWhisperMessage (D:\\projects\\Whatsapp_bot\\node_modules\\libsignal\\src\\session_cipher.js:195:27)\n    at Object.decryptMessage (D:\\projects\\Whatsapp_bot\\node_modules\\@whiskeysockets\\baileys\\lib\\Signal\\libsignal.js:54:44)"},"msg":"failed to decrypt message"}
{"level":40,"time":"2023-07-02T12:22:56.483Z","pid":21476,"hostname":"DESKTOP-6V6Q0T1","class":"baileys","msg":"failed to commit 1 mutations, tries left=8"}
{"level":40,"time":"2023-07-02T12:22:59.489Z","pid":21476,"hostname":"DESKTOP-6V6Q0T1","class":"baileys","msg":"failed to commit 1 mutations, tries left=7"}
{"level":40,"time":"2023-07-02T12:23:02.499Z","pid":21476,"hostname":"DESKTOP-6V6Q0T1","class":"baileys","msg":"failed to commit 1 mutations, tries left=6"}
{"level":40,"time":"2023-07-02T12:23:05.506Z","pid":21476,"hostname":"DESKTOP-6V6Q0T1","class":"baileys","msg":"failed to commit 1 mutations, tries left=5"}
{"level":40,"time":"2023-07-02T12:23:08.514Z","pid":21476,"hostname":"DESKTOP-6V6Q0T1","class":"baileys","msg":"failed to commit 1 mutations, tries left=4"}
{"level":40,"time":"2023-07-02T12:23:11.524Z","pid":21476,"hostname":"DESKTOP-6V6Q0T1","class":"baileys","msg":"failed to commit 1 mutations, tries left=3"}
{"level":40,"time":"2023-07-02T12:23:14.536Z","pid":21476,"hostname":"DESKTOP-6V6Q0T1","class":"baileys","msg":"failed to commit 1 mutations, tries left=2"}
{"level":40,"time":"2023-07-02T12:23:17.552Z","pid":21476,"hostname":"DESKTOP-6V6Q0T1","class":"baileys","msg":"failed to commit 1 mutations, tries left=1"}
{"level":40,"time":"2023-07-02T12:23:20.563Z","pid":21476,"hostname":"DESKTOP-6V6Q0T1","class":"baileys","msg":"failed to commit 1 mutations, tries left=0"}
{"level":30,"time":"2023-07-02T12:23:23.839Z","pid":21476,"hostname":"DESKTOP-6V6Q0T1","class":"baileys","msgAttrs":{"from":"120363022528539354@g.us","type":"text","id":"478BE0090B142EA7B7","participant":"6580480815:26@s.whatsapp.net","addressing_mode":"pn","notify":"Ahnaan","t":"1688300573"},"retryCount":3,"msg":"sent retry receipt"}
{"level":40,"time":"2023-07-02T12:23:23.843Z","pid":21476,"hostname":"DESKTOP-6V6Q0T1","class":"baileys","msg":"failed to commit 1 mutations, tries left=9"}
{"level":50,"time":"2023-07-02T12:23:24.374Z","pid":21476,"hostname":"DESKTOP-6V6Q0T1","class":"baileys","key":{"remoteJid":"120363022528539354@g.us","fromMe":true,"id":"478BE0090B142EA7B7","participant":"6580480815:26@s.whatsapp.net"},"err":{"type":"TypeError","message":"Cannot read properties of undefined (reading 'trace')","stack":"TypeError: Cannot read properties of undefined (reading 'trace')\n    at Object.get (D:\\projects\\Whatsapp_bot\\node_modules\\@whiskeysockets\\baileys\\lib\\Utils\\auth-utils.js:42:24)\n    at Object.get (D:\\projects\\Whatsapp_bot\\node_modules\\@whiskeysockets\\baileys\\lib\\Utils\\auth-utils.js:97:48)\n    at Object.loadSession (D:\\projects\\Whatsapp_bot\\node_modules\\@whiskeysockets\\baileys\\lib\\Signal\\libsignal.js:104:47)\n    at SessionCipher.getRecord (D:\\projects\\Whatsapp_bot\\node_modules\\libsignal\\src\\session_cipher.js:49:43)\n    at 6580480815:26.0 [as awaitable] (D:\\projects\\Whatsapp_bot\\node_modules\\libsignal\\src\\session_cipher.js:196:37)\n    at _asyncQueueExecutor (D:\\projects\\Whatsapp_bot\\node_modules\\libsignal\\src\\queue_job.js:20:39)\n    at module.exports (D:\\projects\\Whatsapp_bot\\node_modules\\libsignal\\src\\queue_job.js:66:9)\n    at SessionCipher.queueJob (D:\\projects\\Whatsapp_bot\\node_modules\\libsignal\\src\\session_cipher.js:62:22)\n    at SessionCipher.decryptPreKeyWhisperMessage (D:\\projects\\Whatsapp_bot\\node_modules\\libsignal\\src\\session_cipher.js:195:27)\n    at Object.decryptMessage (D:\\projects\\Whatsapp_bot\\node_modules\\@whiskeysockets\\baileys\\lib\\Signal\\libsignal.js:54:44)"},"msg":"failed to decrypt message"}
```

**To Reproduce**
1. Created a new connection
2. Closed & used saved credentials to log back in
3. baileys logged in
4. send/recieve a message

**Expected behavior**

**Environment (please complete the following information):**
 - Is this on a server?
      No, I am running on my personal laptop windows 10
 - What do your `connectOptions` look like? 
       I have given my entire code above
 - Do you have multiple clients on the same IP?
       No
 - Are you using a proxy?
       No

**Comment by ikbalardiansah** [comment]
Same error here, whats about now??

**Comment by IsraelXabregas** [comment]
What? Your logger is misconfigured?

Seriously?

Are you kidding?
You didn't even see the error, it's not a log issue, man!

**Comment by enoksaju** [comment]
same here

**Comment by orphancodebr** [comment]
same here

**Comment by jaison-x** [comment]
same here

**Comment by unrealmaow** [comment]
any fix found?

**Comment by usamastr** [comment]
still waiting for fix

**Comment by candidoalbertosilva** [comment]
same here

**Comment by Lucasmm016** [comment]
The same here

**Comment by PurpShell** [comment]
The issue in this case, logger is missing from the socket config
