### ISSUE TITLE
rate-overlimit (Toda mensagem)[BUG]

### ISSUE THREAD

**Issue by tobizinho** [WhiskeySockets/Baileys#222]
rate-overlimit
    at assertNodeErrorFree (C:\Users\Alze\.l\node_modules\@whiskeysockets\baileys\lib\WABinary\generic-utils.js:56:15)
    at query (C:\Users\Alze\.l\node_modules\@whiskeysockets\baileys\lib\Socket\socket.js:144:48)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.groupMetadata (C:\Users\Alze\.l\node_modules\@whiskeysockets\baileys\lib\Socket\groups.js:22:24)
    at async metadata (C:\Users\Alze\.l\db\lib\_ModuFunctions.js:669:17) {
  data: 429,
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 500,
    payload: {
      statusCode: 500,
      error: 'Internal Server Error',
      message: 'An internal server error occurred'
    },
    headers: {}
  }
}

**Comment by FERDIZ-afk** [comment]
> rate-overlimit at assertNodeErrorFree (C:\Users\Alze.l\node_modules@whiskeysockets\baileys\lib\WABinary\generic-utils.js:56:15) at query (C:\Users\Alze.l\node_modules@whiskeysockets\baileys\lib\Socket\socket.js:144:48) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async Object.groupMetadata (C:\Users\Alze.l\node_modules@whiskeysockets\baileys\lib\Socket\groups.js:22:24) at async metadata (C:\Users\Alze.l\db\lib_ModuFunctions.js:669:17) { data: 429, isBoom: true, isServer: true, output: { statusCode: 500, payload: { statusCode: 500, error: 'Internal Server Error', message: 'An internal server error occurred' }, headers: {} } }

What's the error for?

**Comment by SheIITear** [comment]
Rate limit happens because you spam whatsapp server with requests. Doesnt look like a baileys issue.

**Comment by eduardochaves1** [comment]
I'm having this problem when fetching all groups
