### ISSUE TITLE
[BUG] Unable to run example demo

### ISSUE THREAD

**Issue by hbinduni** [WhiskeySockets/Baileys#247]
**Describe the bug**
Unable to run example demo

**To Reproduce**
1. git clone `https://github.com/WhiskeySockets/Baileys.git`
2. cd Baileys
3. yarn install 
4. yarn build:tsc
5. yarn example

**Expected behavior**
Example demo will running

**Environment (please complete the following information):**
 - node v18.16.1
 - yarn v3.5.1
 - sw_vers
ProductName:		macOS
ProductVersion:		13.4.1
ProductVersionExtra:	(c)
BuildVersion:		22F770820d

**Additional context**
Here is the error i got when run example demo:
```
TSError: ⨯ Unable to compile TypeScript:
Example/example.ts:2:30 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("libphonenumber-js")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts', or add the field `"type": "module"` to '/Users/binduni/Baileys/package.json'.

2 import parsePhoneNumber from 'libphonenumber-js'
                               ~~~~~~~~~~~~~~~~~~~

    at createTSError (/Users/binduni/Baileys/node_modules/ts-node/src/index.ts:843:12)
    at reportTSError (/Users/binduni/Baileys/node_modules/ts-node/src/index.ts:847:19)
    at getOutput (/Users/binduni/Baileys/node_modules/ts-node/src/index.ts:1057:36)
    at Object.compile (/Users/binduni/Baileys/node_modules/ts-node/src/index.ts:1411:41)
    at Module.m._compile (/Users/binduni/Baileys/node_modules/ts-node/src/index.ts:1596:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/binduni/Baileys/node_modules/ts-node/src/index.ts:1600:12)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  diagnosticCodes: [ 1479 ]
}
```

**Comment by mkhotib20** [comment]
make sure you have installed `libphonenumber-js`
also make sure you run it with `ts-node`

**Comment by hbinduni** [comment]
i have `libphonenumber-js` installed as part of the git source
```
❯ ls -l node_modules | grep libphonenumber-js
drwxr-xr-x   49 binduni  staff   1568 Jul 15 11:27 libphonenumber-js
```

and run it with `yarn example`. 
`yarn example` has di script in `package.json`
`"example": "node --inspect -r ts-node/register Example/example.ts",`

**Comment by azizramdan** [comment]
replace
`import parsePhoneNumber from 'libphonenumber-js'`

with
`const parsePhoneNumber = require('libphonenumber-js').parsePhoneNumber`

but you will lose the type
