### ISSUE TITLE
[BUG] Error with pairing code

### ISSUE THREAD

**Issue by DavidsonGomes** [WhiskeySockets/Baileys#267]
I'm trying to implement the pairing code but I'm getting this error here

Error: Connection Closed
    at sendRawMessage (/Users/davidson/Projects/atendai-api/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:54:19)
    at sendNode (/Users/davidson/Projects/atendai-api/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:73:16)
    at Object.requestPairingCode (/Users/davidson/Projects/atendai-api/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:370:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 428,
    payload: {
      statusCode: 428,
      error: 'Precondition Required',
      message: 'Connection Closed'
    },
    headers: {}
  }
}

**Comment by DavidsonGomes** [comment]
we added a delay to establish socket creation and then it worked

**Comment by Riders004** [comment]
@DavidsonGomes can you share me your code of pairing code system

**Comment by Jobians** [comment]
I fixed it by adding some delay

```
setTimeout(async () => {
        const code = await socket.requestPairingCode(phoneNumber);
      }, 5000);
```

**Comment by Riders004** [comment]
> we added a delay to establish socket creation and then it worked

Yes
