### ISSUE TITLE
[BUG] Error group accept invite failed

### ISSUE THREAD

**Issue by exallhost** [WhiskeySockets/Baileys#31]
**Describe the bug**

**To Reproduce**
1. Created a new connection
2. Closed & used saved credentials to log back in
3. Execute to function join in group (groupAcceptInvite)

**Expected behavior**
Ao executar apresenta o seguinte erro:

`{"level":50,"time":1682517324847,"pid":5378,"hostname":"send.wp2.exall-host.com.br","err":{"type":"Error","message":"bad-request","stack":"Error: bad-request\n    at assertNodeErrorFree (/root/api-whatsapp-ehost/node_modules/@adiwajshing/baileys/lib/WABinary/generic-utils.js:56:15)\n    at query (/root/api-whatsapp-ehost/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:128:48)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async Object.groupAcceptInvite (/root/api-whatsapp-ehost/node_modules/@adiwajshing/baileys/lib/Socket/groups.js:110:29)\n    at async WhatsAppInstance.groupAcceptInvite (/root/api-whatsapp-ehost/src/api/class/instance.js:1014:25)\n    at async exports.joinGroupViaInviteCode (/root/api-whatsapp-ehost/src/api/controllers/group.controller.js:112:18)","data":400,"isBoom":true,"isServer":true,"output":{"statusCode":500,"payload":{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"},"headers":{}}},"msg":"bad-request"}`

**Comment by DozenLimeStone** [comment]
so they discarded a bug so i cant make the bot join a group
