### ISSUE TITLE
error in request pairing code [BUG]

### ISSUE THREAD

**Issue by HyNO-IR** [WhiskeySockets/Baileys#369]
**error in request pairing code**

when i request for pairing code i got error connection closed

`Error: Connection Closed
    at sendRawMessage (/home/runner/TalkativeBlushingNotifications/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:54:19)
    at sendNode (/home/runner/TalkativeBlushingNotifications/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:73:16)
    at Object.requestPairingCode (/home/runner/TalkativeBlushingNotifications/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:370:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 428,
    payload: {
      statusCode: 428,
      error: 'Precondition Required',
      message: 'Connection Closed'
    },
    headers: {}
  }
}`

**Comment by Arctic-beaver** [comment]
Same

**Comment by moskoweb** [comment]
Estava acontecendo comigo, percebi que era por que estava solicitando o código antes da conexão estabelecer, colocando para solicitar o código quando gera o QR Code resolveu o problema. Agora a questão é que não conecta com o código.

**Comment by arr2504** [comment]
try remove creds.json session file and request again

**Comment by Auties00** [comment]
Duplicate of https://github.com/WhiskeySockets/Baileys/issues/328
