### ISSUE TITLE
[BUG] "Error: Connection Failure" in mobile mode

### ISSUE THREAD

**Issue by xianm-sudo** [WhiskeySockets/Baileys#374]
**Describe the bug**

{"level":30,"time":"2023-09-07T14:22:33.250Z","pid":7672,"hostname":"Admin","trace":"Error: Connection Failure\n    at MobileSocketClient.<anonymous> (C:\\Users\\Administrator\\Desktop\\Baileys\\src\\Socket\\socket.ts:646:7)\n    at MobileSocketClient.emit (node:events:513:28)\n    at MobileSocketClient.emit (node:domain:489:12)\n    at C:\\Users\\Administrator\\Desktop\\Baileys\\src\\Socket\\socket.ts:338:23\n    at Object.decodeFrame (C:\\Users\\Administrator\\Desktop\\Baileys\\src\\Utils\\noise-handler.ts:176:5)\n    at MobileSocketClient.onMessageRecieved (C:\\Users\\Administrator\\Desktop\\Baileys\\src\\Socket\\socket.ts:310:9)\n    at MobileSocketClient.emit (node:events:513:28)\n    at MobileSocketClient.emit (node:domain:489:12)\n    at Socket.<anonymous> (C:\\Users\\Administrator\\Desktop\\Baileys\\src\\Socket\\Client\\mobile-socket-client.ts:43:51)\n    at Socket.emit (node:events:525:35)","msg":"connection errored"}
connection update {
  connection: 'close',
  lastDisconnect: {
    error: Error: Connection Failure
        at MobileSocketClient.<anonymous> (C:\Users\Administrator\Desktop\Baileys\src\Socket\socket.ts:646:7)
        at MobileSocketClient.emit (node:events:513:28)
        at MobileSocketClient.emit (node:domain:489:12)
        at C:\Users\Administrator\Desktop\Baileys\src\Socket\socket.ts:338:23
        at Object.decodeFrame (C:\Users\Administrator\Desktop\Baileys\src\Utils\noise-handler.ts:176:5)
        at MobileSocketClient.onMessageRecieved (C:\Users\Administrator\Desktop\Baileys\src\Socket\socket.ts:310:9)
        at MobileSocketClient.emit (node:events:513:28)
        at MobileSocketClient.emit (node:domain:489:12)
        at Socket.<anonymous> (C:\Users\Administrator\Desktop\Baileys\src\Socket\Client\mobile-socket-client.ts:43:51)
        at Socket.emit (node:events:525:35) {
      data: [Object],
      isBoom: true,
      isServer: false,
      output: [Object]
    },
    date: 2023-09-07T14:22:33.252Z
  }
}

**Comment by Ased2235** [comment]
Same here
