### ISSUE TITLE
[BUG] Connection error

### ISSUE THREAD

**Issue by ricardoapaes** [WhiskeySockets/Baileys#386]
**Describe the bug**
TypeError: Cannot read properties of undefined (reading 'public')
at Object.processHandshake (/usr/src/app/node_modules/@whiskeysockets/baileys/lib/Utils/noise-handler.js:96:45)
at validateConnection (/usr/src/app/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:155:30)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async WebSocketClient.<anonymous> (/usr/src/app/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:429:13)

**Comment by renerlemes** [comment]
I´m the same problemn. I can send 2 or 3 messages, then it stops sending and this error occurs

**Comment by danielantoniobs** [comment]
Same here, I read the qrcode and I get the error. Has anyone managed to solve it?
