### ISSUE TITLE
[BUG] bug status code 404, 408 and 500 when i want to use conn.profilepictureurl 

### ISSUE THREAD

**Issue by AKAZAMD** [WhiskeySockets/Baileys#453]
can you help me, this error occurs when i want to use conn.profilepictureurl
Error: item-not-found
    at assertNodeErrorFree (/home/runner/#HIDDEN#/node_modules/@adiwajshing/baileys/lib/WABinary/generic-utils.js:56:15)
    at query (/home/runner/#HIDDEN#/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:140:48)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.profilePictureUrl (/home/runner/#HIDDEN#/node_modules/@adiwajshing/baileys/lib/Socket/chats.js:442:24)
    at Object.participantsUpdate (file:///home/runner/#HIDDEN#/handler.js?update=1697755371157:1363:14)
    at Object.handler (file:///home/runner/#HIDDEN#/handler.js?update=1697755371157:1166:21) {
  data: 404,
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 500,
    payload: {
      statusCode: 500,
      error: 'Internal Server Error',
      message: 'An internal server error occurred'
    },
    headers: {}
  }
}

**Comment by bobdevfull** [comment]
@adiwajshing/baileys ??? Are you sure your code is up to date?

**Comment by AKAZAMD** [comment]
> @adiwajshing/baileys ??? Apakah Anda yakin kode Anda mutakhir?

I only use the first name adiwajshing but in the contents I use whiskeysockets/baileys because so many of my bots use adiwajshing so I don't want to be difficult so I just name it in package.json as adiwajshing

**Comment by AKAZAMD** [comment]
> @adiwajshing/baileys ??? Apakah Anda yakin kode Anda telah diganti?

    "@adiwajshing/baileys": "npm:@whiskeysockets/baileys",

**Comment by JER-OFC** [comment]
> > @adiwajshing/baileys ??? Apakah Anda yakin kode Anda telah diganti?
> 
> ```
> "@adiwajshing/baileys": "npm:@whiskeysockets/baileys",
> ```

🗿🗿🗿🗿🗿

**Comment by AKAZAMD** [comment]
> > > @adiwajshing/baileys ??? Apakah Anda yakin kode Anda telah diganti?
> > 
> > 
> > ```
> > "@adiwajshing/baileys": "npm:@whiskeysockets/baileys",
> > ```
> 
> 🗿🗿🗿🗿🗿
sama bang🗿

**Comment by dhirennjaypal** [comment]
I am also getting this error, how did you solve it ?
