### ISSUE TITLE
[BUG] Error: Connection closed when sending messages

### ISSUE THREAD

**Issue by weershft** [WhiskeySockets/Baileys#492]
I have several connected instances (MD) in my application, but each instance only lasts a maximum of 3 days connected and then when I try to send a message it gives the connection closed error, as shown in the image.

Try to restore this same connection but it does not send messages again and the closed connection persists.

Does anyone have a solution for this or know how to get around this error?

![error](https://github.com/WhiskeySockets/Baileys/assets/85660339/0736ae1c-5526-4af9-abcd-268407265972)

my socketConfig ->

```
socketConfig = {
        version: [2, 2329, 9],
        defaultQueryTimeoutMs: undefined,
        printQRInTerminal: false,
        logger: pino({
            level: config.log.level,
        }),
    }
```

code verifyId of send message ->

```
async verifyId(id) {
        const justNumber = id
            .replace('@s.whatsapp.net', '')
            .replace('@g.us', '')
        const replaced = removeSpecialCharacters(justNumber)
        if (id.includes('@g.us')) return true
        let [result] = ""
        let isClosed = false;
        try {
            [result] = await this.instance.sock?.onWhatsApp(id)
        } catch(err) {
            console.log(err)
            if (err.output?.statusCode === 428) {
                isClosed = true
                await this.init(true, false).then((i) => console.log('restore...')).catch((err) => console.log('Error: ' + err))
            }
        }
        if (isClosed) {
            throw new Error(
                'Error: Connection Closed'
            )
        }
        if (result?.exists && validateNumber(replaced)) return true
        throw new Error(
            'No number or account, please check the number sent.'
        )
    }
```

**Comment by LucasNF99** [comment]
I have the same problem

**Comment by juandavidGF** [comment]
I have a similar issue. I read the QR code and saved the session. I closed the session to make changes to my code. When I run again the script it doesn't init automatically, and require again the QR code. I didn't have this problem some weeks ago. So maybe It's a new bug.

**Comment by weershft** [comment]
I understand...

 I noticed with testing that this problem happens a lot with WhatsApp Business.

You using WhatsApp Business too ?

**Comment by juandavidGF** [comment]
Yes, WhatsApp business, the strange is it never happened some weeks ago :/

**Comment by weershft** [comment]
Even so, we need to somehow find a solution and open a PR for correction...

**Comment by weershft** [comment]
I testing now, outher socketConfig...

My code ->

socketConfig = {
        version: [2, 2329, 9],
        defaultQueryTimeoutMs: undefined,
        printQRInTerminal: false,
        logger: pino({
            level: config.log.level,
        }),
        keepAliveIntervalMs: 15000,
        markOnlineOnConnect: true,
        mobile: false,
        browser: Browsers.macOS("Desktop"),
        syncFullHistory: false
    }

How is yours?

**Comment by juandavidGF** [comment]
```
const { state, saveCreds } = await useMultiFileAuthState('baileys_auth_info');
logger.level = 'trace';
  
const sock = makeWASocket({
  printQRInTerminal: true,
  auth: state,
});
  
sock.ev.on("creds.update", saveCreds);
```

```
sock.ev.on("connection.update", (update) => {
    console.log('con update')
    const { connection, lastDisconnect } = update;
    if (connection === "close") {
      const shouldReconnect =
        (lastDisconnect?.error as Boom)?.output?.statusCode !==
        DisconnectReason.loggedOut;
      console.log(
        "connection closed due to ",
        lastDisconnect?.error,
        ", reconnecting ",
        shouldReconnect
      );
      // reconnect if not logged out
      if (shouldReconnect) {
        connectToWhatsApp();
      }
    } else if (connection === "open") {
      console.log("opened connection");
      // jobTasks();
    }
  });
```

**Comment by weershft** [comment]
Okay

Search to makeBusinessSocket on baileys...

![image](https://github.com/WhiskeySockets/Baileys/assets/85660339/c122f9d1-aea9-4b4b-b76f-525e7366ce13)

![image](https://github.com/WhiskeySockets/Baileys/assets/85660339/902fceef-53d0-4d72-a883-b67d9440aabc)
****

I noticed that the default value was with makeWASocket, and I changed the value to makeBusinessSocket...

![image](https://github.com/WhiskeySockets/Baileys/assets/85660339/a8dd1181-3868-4822-a6a5-53f2aad44f26)


I also changed it inside inde.d.ts in lib/index.d.ts

**Comment by Hataken999** [comment]
> Okay
> 
> Search makeBusinessSocket on baileys...
> 
> ![image](https://private-user-images.githubusercontent.com/85660339/282787828-c122f9d1-aea9-4b4b-b76f-525e7366ce13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0MTU3NjEsIm5iZiI6MTcwMzQxNTQ2MSwicGF0aCI6Ii84NTY2MDMzOS8yODI3ODc4MjgtYzEyMmY5ZDEtYWVhOS00YjRiLWI3NmYtNTI1ZTczNjZjZTEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDEwNTc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkMDEzNjc5NTRjOGQxZjhkZjFiNDM1MDc4M2VhZjQzNmYwNjFjNWM0NTRmNjRmOTQ2OThjZDQzMWFlMDA1YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YHgaZjbI6XfjSz5BGtoyntCBHZpkIKHgRZfoP_Pg8Xw)
> 
> ![image](https://private-user-images.githubusercontent.com/85660339/282787958-902fceef-53d0-4d72-a883-b67d9440aabc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0MTU3NjEsIm5iZiI6MTcwMzQxNTQ2MSwicGF0aCI6Ii84NTY2MDMzOS8yODI3ODc5NTgtOTAyZmNlZWYtNTNkMC00ZDcyLWE4ODMtYjY3ZDk0NDBhYWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDEwNTc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyNmYyMGEzNWY2NDIzNWEyYzExM2M4M2I5MDU3OGYzMjE5MjBkYzlmZTFiMjMwY2M5MTA1Mzg4YzJlMjg4MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jQmE4VBebk8DYP1s3k1b4OBeQw_vwTUjwxO00mw_ntM)
> 
> I noticed that the default value was with makeWASocket, and I changed the value to makeBusinessSocket...
> 
> ![image](https://private-user-images.githubusercontent.com/85660339/282788424-a8dd1181-3868-4822-a6a5-53f2aad44f26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0MTU3NjEsIm5iZiI6MTcwMzQxNTQ2MSwicGF0aCI6Ii84NTY2MDMzOS8yODI3ODg0MjQtYThkZDExODEtMzg2OC00ODIyLWE2YTUtNTNmMmFhZDQ0ZjI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDEwNTc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjMWMyZTI3ZmZmOWQzN2MyMTg0NGFiMmU5YTZhOGY2MDVjNTJmYTg1MGZhYmFkM2UzZGI1MjEzZmFhMmMxZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YmtJPJsxpVjzOM6JzMlH5x7Rta78Vy19w1573gwL5H0)
> 
> I also changed it inside index.d.ts in lib/index.d.ts
> 
> I'm trying now with these adjustments

and how is it now? solved or not?

**Comment by lomeliDev** [comment]
Could you solve it?

**Comment by david-lev** [comment]
@weershft did you find any solution?

**Comment by david-lev** [comment]
@shanmugaacharan 
What I ended up doing is making sure that the software is restarted every time it crashes, it's possible with `while true; do run_program_cmd; done` or with docker compose (`restart always` or with some condition)

**Comment by mersidev-yusri** [comment]
my config 
```
import {makeBusinessSocket} from '../src/Socket/business'
import { makeLibSignalRepository } from '../src/Signal/libsignal'


const sock = makeBusinessSocket({
		defaultQueryTimeoutMs: undefined,
		version,
		logger,
		printQRInTerminal: true,
		mobile: useMobile,
		auth: {
			creds: state.creds, 
			keys: makeCacheableSignalKeyStore(state.keys, logger),
		},
		msgRetryCounterCache, 
		getMessage,
		syncFullHistory: false,
		browser: Browsers.ubuntu('Desktop'),
		options: {},
		waWebSocketUrl: 'wss://web.whatsapp.com/ws/chat',
		connectTimeoutMs: 0,
		keepAliveIntervalMs: 0,
		emitOwnEvents: false,
		customUploadHosts: [],
		retryRequestDelayMs: 0,
		maxMsgRetryCount: 0,
		shouldSyncHistoryMessage: () => true,
		transactionOpts: {
			maxCommitRetries: 0,
			delayBetweenTriesMs: 0
		},
		markOnlineOnConnect: false,
		linkPreviewImageThumbnailWidth: 0,
		fireInitQueries: false,
		generateHighQualityLinkPreview: false,
		shouldIgnoreJid: () => false,
		patchMessageBeforeSending: msg => msg,
		appStateMacVerification: {
			patch: false,
			snapshot: false
		},
		makeSignalRepository: makeLibSignalRepository
	})
```
and this work for me on my WA business.

**Comment by luispimenta** [comment]
> I also facing this issue will sending the message. Any solution there to resolve Error sending message or file: Error: Connection Closed at sendRawMessage (/home/ubuntu/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:54:19) at sendNode (/home/ubuntu/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:73:16) at query (/home/ubuntu/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:137:15) at getUSyncDevices (/home/ubuntu/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:166:30) at /home/ubuntu/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:357:53 at Object.transaction (/home/ubuntu/node_modules/@whiskeysockets/baileys/lib/Utils/auth-utils.js:136:32) at relayMessage (/home/ubuntu/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:279:30) at Object.sendMessage (/home/ubuntu/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:652:23) at runMicrotasks () at processTicksAndRejections (node:internal/process/task_queues:96:5) { data: null, isBoom: true, isServer: false, output: { statusCode: 428, payload: { statusCode: 428, error: 'Precondition Required', message: 'Connection Closed' }, headers: {} } }

@shanmugaacharan did you solve this?

**Comment by aledc7** [comment]
any news about this bug?

**Comment by edilsonlsouza** [comment]
These ungrateful people are like that, they come looking for help, get it and then after it works out they disappear, they don't answer to anyone anymore. Life takes care of people like that.

**Comment by edilsonlsouza** [comment]
import makeBusinessSocket from './Socket';
export * from '../WAProto';
export * from './Utils';
export * from './Types';
export * from './Store';
export * from './Defaults';
export * from './WABinary';
export type WASocket = ReturnType<typeof makeBusinessSocket>;
export { makeBusinessSocket };
export default makeBusinessSocket;

That solved the problem!
