### ISSUE TITLE
[BUG]  socket.groupParticipantsUpdate("group@g.us", ["phone@s.whatsapp.net"], "add")  Status 500

### ISSUE THREAD

**Issue by GkIgor** [WhiskeySockets/Baileys#520]
Not using proxy;
Not using server;
Saved credentials;
Rest of the code works.

I'm testing a new feature to deploy in a project with the following code:

```typescript
if (message && message.startsWith("$teste")) {

      const numero = message.split(" ")[1] + "@s.whatsapp.net";
      console.log(numero);

      await socket
        .groupParticipantsUpdate('120...81@g.us', ['5519...@s.whatsapp.net'], "add")
        .then((data) => console.log(data))
        .catch((data) => console.log(data));
    }
```

Console output:

```shell
5519...@s.whatsapp.net
Error: bad-request
    at assertNodeErrorFree (/home/gkigor/Development/testes/migrate-baileys-teste/node_modules/.pnpm/@whiskeysockets+baileys@6.5.0_qrcode-terminal@0.12.0/node_modules/@whiskeysockets/baileys/lib/WABinary/generic-utils.js:56:15)
    at query (/home/gkigor/Development/testes/migrate-baileys-teste/node_modules/.pnpm/@whiskeysockets+baileys@6.5.0_qrcode-terminal@0.12.0/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:140:48)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.groupParticipantsUpdate (/home/gkigor/Development/testes/migrate-baileys-teste/node_modules/.pnpm/@whiskeysockets+baileys@6.5.0_qrcode-terminal@0.12.0/node_modules/@whiskeysockets/baileys/lib/Socket/groups.js:142:28) {
  data: 400,
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 500,
    payload: {
      statusCode: 500,
      error: 'Internal Server Error',
      message: 'An internal server error occurred'
    },
    headers: {}
  }
}
``` 

In short, I want to add members to a group, but an internal server error occurred.

**Comment by GkIgor** [comment]
> Have you checked if the number you want to add is allowed for everyone to add to the group?

No, do I need verification? Do you have a code example?

**Comment by AliSot2000** [comment]
Hey

I was testing around with this code.  What I found regarding this. If you have one number that isn't tied to WhatsApp account, it causes the entire request to fail. 

So assuming you have [<valid-number>, <non-whatsapp-number>] as participants the entire request fails. I'd expect it to fail with like 404 for that number but not the entire request.
