### ISSUE TITLE
[BUG] Why error "Unsupported state or unable to authenticate data"

### ISSUE THREAD

**Issue by dammah** [WhiskeySockets/Baileys#527]
for some reason this error appears in the log after a long time

node:internal/crypto/cipher:193
  const ret = this[kHandle].final();
                            ^

Error: Unsupported state or unable to authenticate data
    at CipherBase.final (<anonymous>)
    at Decipheriv.final (node:internal/crypto/cipher:193:29)
    at aesDecryptGCM (/home/topapp/nodevenv/public_html/app/18/lib/node_modules/@adiwajshing/baileys/lib/Utils/crypto.js:93:58)
    at decrypt (/home/topapp/nodevenv/public_html/app/18/lib/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:31:51)
    at Object.decodeFrame (/home/topapp/nodevenv/public_html/app/18/lib/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:132:36)
    at WebSocketClient.onMessageRecieved (/home/topapp/nodevenv/public_html/app/18/lib/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:212:15)
    at WebSocketClient.emit (node:events:513:28)
    at WebSocket.<anonymous> (/home/topapp/nodevenv/public_html/app/18/lib/node_modules/@adiwajshing/baileys/lib/Socket/Client/web-socket-client.js:46:100)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/home/topapp/nodevenv/public_html/app/18/lib/node_modules/@adiwajshing/baileys/node_modules/ws/lib/websocket.js:1184:20)

**Comment by Bruno-10** [comment]
I'm having the same issue, out of nowhere it just started failling

**Comment by ahmedB7r** [comment]
me too here
