### ISSUE TITLE
[BUG] Stream errored out

### ISSUE THREAD

**Issue by asabadyr** [WhiskeySockets/Baileys#537]
**Describe the bug**
From time to time we receive an error (logged below). Right after this error a device gets disconnected.
User is not not doing anything for this disconnect to happen. Moreover the user even has not opened WhatsApp application on the phone for 3 weeks, there was no communication during that time. Only contact updates very rarely.
Our service is running 300 hundred users with their connected devices. And almost each day we get 2-3 disconnects with similar behavior.

`hostname":"whatsapp-node-7964ff4fcf-stbr9", "level":30, "msg":"connection errored", "pid":1, "trace":"Error: Stream Errored (conflict)
    at WebSocketClient.<anonymous> (/usr/src/app/backend/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:501:13)
    at WebSocketClient.emit (node:events:526:28)
    at WebSocketClient.emit (node:domain:475:12)
    at /usr/src/app/backend/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:236:35
    at Object.decodeFrame (/usr/src/app/backend/node_modules/@whiskeysockets/baileys/lib/Utils/noise-handler.js:136:17)
    at WebSocketClient.onMessageRecieved (/usr/src/app/backend/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:212:15)
    at WebSocketClient.emit (node:events:526:28)
    at WebSocketClient.emit (node:domain:475:12)
    at WebSocket.<anonymous> (/usr/src/app/backend/node_modules/@whiskeysockets/baileys/lib/Socket/Client/web-socket-client.js:46:100)
    at WebSocket.emit (node:events:526:28)"}`

**To Reproduce**
1. Created a new connection
2. Let it run for 3-4 weeks without bringing down or stopping
3. Get a random disconnect not motivated by the end user

**Expected behavior**
It should just run fine

**Environment (please complete the following information):**
 - Is this on a server? Yes. Docker container in Kubernetes orchestration.
 - What do your `connectOptions` look like? `makeWASocket({
      version,
      logger,
      printQRInTerminal: false,
      auth: this.authState.getCreds(),
      markOnlineOnConnect: false,
      keepAliveIntervalMs: 30000,
      connectTimeoutMs: 20000,
      browser: Browsers.macOS('Desktop'),
      syncFullHistory: true,`})
 - Do you have multiple clients on the same IP? Yes. 200-300
 - Are you using a proxy? No

**Additional context**

**Comment by ceoagarson** [comment]
same issue for me

 {"level":30,"time":"2023-12-22T16:25:50.481Z","pid":31895,"hostname":"nishu-Vostro-15-3568","class":"baileys","browser":["Baileys","Chrome","4.0.0"],"helloMsg":{"clientHello":{"ephemeral":"uetr8B7XnDgR1aGFlLmHClGooovOeljmmRIjDwN2WRc="}},"msg":"connected to WA"}
[1] {"level":30,"time":"2023-12-22T16:25:50.923Z","pid":31895,"hostname":"nishu-Vostro-15-3568","class":"baileys","node":{"passive":false,"userAgent":{"platform":"MACOS","appVersion":{"primary":2,"secondary":2329,"tertiary":9},"mcc":"000","mnc":"000","osVersion":"0.1","manufacturer":"","device":"Desktop","osBuildNumber":"0.1","releaseChannel":"RELEASE","localeLanguageIso6391":"en","localeCountryIso31661Alpha2":"US"},"connectType":"WIFI_UNKNOWN","connectReason":"USER_ACTIVATED","devicePairingData":{"eRegid":"AAAAlQ==","eKeytype":"BQ==","eIdent":"/TM3rhrzDW8IT7DvpuKKi75b9/W0rJzE0rJr+4BVRnc=","eSkeyId":"AAAB","eSkeyVal":"A/847H6ksUjJ3kDuHBquuJdeLQGGLQ7/a2C5btWJ+ik=","eSkeySig":"n8A9i5N66UQtxBwlRMBIQvAn8vPSP+ZVrohI/DBUKWD0Gvhp4g//A9iBLwONJ3zMsRRZksrs2rT+VJFJsqx8Dw==","buildHash":"CgVgtSpHoPZPkgJcSCwM7A==","deviceProps":"CgdCYWlsZXlzGAcgAA=="}},"msg":"not logged in, attempting registration..."}

**Comment by PeaceX100** [comment]
{"level":30,"time":"2024-03-11T09:21:30.700Z","pid":3405,"hostname":"70e32069b6f6","class":"baileys","me":{"id":"918422830108:13@s.whatsapp.net"},"platform":"android","msg":"pairing configured successfully, expect to restart the connection..."}
{"level":50,"time":"2024-03-11T09:21:30.981Z","pid":3405,"hostname":"70e32069b6f6","class":"baileys","node":{"tag":"stream:error","attrs":{"code":"515"}},"msg":"stream errored out"}
{"level":30,"time":"2024-03-11T09:21:30.982Z","pid":3405,"hostname":"70e32069b6f6","class":"baileys","trace":"Error: Stream Errored (restart required)\n    at WebSocketClient.<anonymous> (/home/runner/Baileys/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:502:13)\n    at WebSocketClient.emit (node:events:514:28)\n    at /home/runner/Baileys/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:236:35\n    at Object.decodeFrame (/home/runner/Baileys/node_modules/@whiskeysockets/baileys/lib/Utils/noise-handler.js:136:17)\n    at WebSocketClient.onMessageRecieved (/home/runner/Baileys/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:212:15)\n    at WebSocketClient.emit (node:events:514:28)\n    at WebSocket.<anonymous> (/home/runner/Baileys/node_modules/@whiskeysockets/baileys/lib/Socket/Client/web-socket-client.js:46:100)\n    at WebSocket.emit (node:events:514:28)\n    at Receiver.receiverOnMessage (/home/runner/Baileys/node_modules/ws/lib/websocket.js:1209:20)\n    at Receiver.emit (node:events:514:28)","msg":"connection errored"}

It happens when I scan the qr. I tried looking for solutions but nothing works

**Comment by vinikjkkj** [comment]
`Stream Errored (restart required)`

you have to restart your session to connect when you receive this message
