### ISSUE TITLE
[BUG] - Logger cannot compile

### ISSUE THREAD

**Issue by luix-guxto** [WhiskeySockets/Baileys#585]
**Describe the bug**
```JS
TSError: ⨯ Unable to compile TypeScript:
index.ts:189:46 - error TS2322: Type 'Logger<{ timestamp: () => string; }>' is not assignable to type 'Logger | undefined'.
  Type 'Logger<{ timestamp: () => string; }>' is not assignable to type 'Logger'.
    Type 'Logger<{ timestamp: () => string; }>' is not assignable to type 'LoggerExtras<LoggerOptions>'.
      The types returned by 'child(...)' are incompatible between these types.
        Type 'Logger<{ timestamp: () => string; } & ChildOptions>' is not assignable to type 'Logger<LoggerOptions & ChildOptions>'.
          Type 'Logger<{ timestamp: () => string; } & ChildOptions>' is not assignable to type 'LoggerExtras<LoggerOptions & ChildOptions>'.
            The types returned by 'flush(...)' are incompatible between these types.
              Type 'void' is not assignable to type '() => void'.

189 const store = useStore ? makeInMemoryStore({ logger }) : undefined
                                                 ~~~~~~

  node_modules/@whiskeysockets/baileys/lib/Store/make-in-memory-store.d.ts:20:5
    20     logger?: Logger;
           ~~~~~~
    The expected type comes from property 'logger' which is declared here on type 'BaileysInMemoryStoreConfig'
index.ts:210:7 - error TS2322: Type 'Logger<{ timestamp: () => string; }>' is not assignable to type 'Logger | undefined'.

210       logger,
          ~~~~~~

  node_modules/@whiskeysockets/baileys/lib/Types/Socket.d.ts:37:5
    37     logger: Logger;
           ~~~~~~
    The expected type comes from property 'logger' which is declared here on type 'UserFacingSocketConfig'
index.ts:216:55 - error TS2345: Argument of type 'Logger<{ timestamp: () => string; }>' is not assignable to parameter of type 'Logger'.

216         keys: makeCacheableSignalKeyStore(state.keys, logger),
                                                          ~~~~~~
index.ts:353:21 - error TS2322: Type 'Logger<{ timestamp: () => string; }>' is not assignable to type 'Logger'.

353                     logger,
                        ~~~~~~

    at createTSError (C:\Users\Vendas\Documents\ApanBot\node_modules\ts-node\src\index.ts:859:12)
    at reportTSError (C:\Users\Vendas\Documents\ApanBot\node_modules\ts-node\src\index.ts:863:19)
    at getOutput (C:\Users\Vendas\Documents\ApanBot\node_modules\ts-node\src\index.ts:1077:36)
    at Object.compile (C:\Users\Vendas\Documents\ApanBot\node_modules\ts-node\src\index.ts:1433:41)
    at transformSource (C:\Users\Vendas\Documents\ApanBot\node_modules\ts-node\src\esm.ts:400:37)
    at C:\Users\Vendas\Documents\ApanBot\node_modules\ts-node\src\esm.ts:278:53
    at async addShortCircuitFlag (C:\Users\Vendas\Documents\ApanBot\node_modules\ts-node\src\esm.ts:409:15)
    at async nextLoad (node:internal/modules/esm/loader:163:22)
    at async ESMLoader.load (node:internal/modules/esm/loader:605:20)
    at async ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:11) {
  diagnosticCodes: [ 2322, 2322, 2345, 2322 ]
```
**To Reproduce**

in the code, I use, this way:
```ts
import P from "pino";
const pino = P.default;
export default pino({ timestamp: () => `,"time":"${new Date().toJSON()}"` });

//------------------------//

// @ts-ignore
import MAIN_LOGGER from "./utils/logger.ts";
const logger = MAIN_LOGGER.child({});
logger.level = "trace";
const store = useStore ? makeInMemoryStore({ logger }) : undefined
const socket = makeWASocket.default;
    const sock = socket({
      version,
      logger,
      printQRInTerminal: true,
      browser: ["Apan", "Safari", "3.0"],
      auth: {
        creds: state.creds,
        /** caching makes the store faster to send/recv messages */
        keys: makeCacheableSignalKeyStore(state.keys, logger),  
      },
      getMessage: async (key) => {
        if (store) {
          const msg = await store.loadMessage(
            key.remoteJid!,
            key.id!,
          );
          return msg?.message || undefined;
        }
        return {
          conversation: "hello",
        };
      },
    });
    store?.bind(sock.ev);
```
It's important to say, the code worked previously, however, after mid-December, this error started, and I couldn't solve it anymore.
How can I solve this?

**Comment by reinaldocoelho** [comment]
Hi, I have the same problem, and I can solve it by change pino version to the same of Baileys use.

I change my package.json to :
`"pino": "^7.0.0",`

I hope I was able to help :-)

**Comment by vinikjkkj** [comment]
fixed #1153
