### ISSUE TITLE
[BUG] message.upsert doesn't work any cmd or function doesn't work but sometimes

### ISSUE THREAD

**Issue by prabathLK** [WhiskeySockets/Baileys#602]
Why is this error coming?  message.upsert doesn't work any cmd or function doesn't work but sometimes it works if you scan the qr 10 times it gives about 2 working sessions is there any solution for this?

Error: Timed Out
app[web.1]: at /app/node_modules/@whiskeysockets/baileys/lib/Utils/generics.js:136:32
app[web.1]: data: {
app[web.1]:   stack: 'Error\n' +
app[web.1]:     '    at promiseTimeout (/app/node_modules/@whiskeysockets/baileys/lib/Utils/generics.js:131:19)\n' +
app[web.1]:     '    at waitForMessage (/app/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:114:53)\n' +
app[web.1]:     '    at query (/app/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:136:22)\n' +
app[web.1]:     '    at assertSessions (/app/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:199:34)\n' +
app[web.1]:     '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
app[web.1]:     '    at async /app/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:374:17\n' +
app[web.1]:     '    at async Object.transaction (/app/node_modules/@whiskeysockets/baileys/lib/Utils/auth-utils.js:136:26)\n' +
app[web.1]:     '    at async relayMessage (/app/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:279:9)\n' +
app[web.1]:     '    at async Object.sendMessage (/app/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:652:17)'
app[web.1]: },
app[web.1]: isBoom: true,
app[web.1]: isServer: false,
app[web.1]: output: {
app[web.1]:   statusCode: 408,
app[web.1]:   payload: {
app[web.1]:     statusCode: 408,
app[web.1]:     error: 'Request Time-out',
app[web.1]:     message: 'Timed Out'
app[web.1]:   },
app[web.1]:   headers: {}
app[web.1]: }

**Comment by laxeder** [comment]
This error is resolved in #604

**Comment by Sithum200825** [comment]
PRABATH-MD~UuMh2D7B#oyZIiV4FMDZQMBB-t4Mon484xsL0PKaDjgHq6-2Tqm4

**Comment by Sithum200825** [comment]
Conect
