### ISSUE TITLE
[BUG] messages not visible on device (Bad MAC)

### ISSUE THREAD

**Issue by 4relial** [WhiskeySockets/Baileys#635]
**Describe the bug**
Does anyone have this problem?
This Error make the messages not visible on device whatsapp like we are not sending anything.
I have tried doing a rescan, this problem was fixed for a while but the error returned again after a few hours,

Failed to decrypt message with any known session...
Session error:Error: Bad MAC Error: Bad MAC
    at Object.verifyMAC (/home/container/node_modules/libsignal/src/crypto.js:87:15)
    at SessionCipher.doDecryptWhisperMessage (/home/container/node_modules/libsignal/src/session_cipher.js:250:16)
    at async SessionCipher.decryptWithSessions (/home/container/node_modules/libsignal/src/session_cipher.js:147:29)
    at async Object.6289507840607.0 [as awaitable] (/home/container/node_modules/libsignal/src/session_cipher.js:171:28)
    at async _asyncQueueExecutor (/home/container/node_modules/libsignal/src/queue_job.js:20:29)
Failed to decrypt message with any known session...
Session error:Error: Bad MAC Error: Bad MAC
    at Object.verifyMAC (/home/container/node_modules/libsignal/src/crypto.js:87:15)
    at SessionCipher.doDecryptWhisperMessage (/home/container/node_modules/libsignal/src/session_cipher.js:250:16)
    at async SessionCipher.decryptWithSessions (/home/container/node_modules/libsignal/src/session_cipher.js:147:29)
    at async Object.6289507840607.0 [as awaitable] (/home/container/node_modules/libsignal/src/session_cipher.js:171:28)
    at async _asyncQueueExecutor (/home/container/node_modules/libsignal/src/queue_job.js:20:29)

**Comment by Fonnte** [comment]
Yes, it happen sometime. No idea how to fix, but afaik, this issue will resolved itself in 1-2 days. Rescan help for a while, but bad mac will eventually hit again until it resolve itself. I hope someone knows more about it

**Comment by tonykx** [comment]
Up

**Comment by brianly1003** [comment]
Up

**Comment by Gesualdo14** [comment]
up

**Comment by natanh1** [comment]
up

**Comment by mminfo** [comment]
up

**Comment by edgarcruz7799** [comment]
Up

**Comment by maurilio-vilela** [comment]
Up

**Comment by josealissonbr** [comment]
up

**Comment by jvictorbap** [comment]
up

**Comment by daniel-n-silva** [comment]
The "fixed for a while then comes back" pattern matches what I traced this to — rescanning re-establishes a session under one identity form, but self-sync traffic keeps arriving addressed under the other, so it resurfaces once that path is hit again. Fix in #2763 retries with the identity form WhatsApp pairs to the stanza before failing.
