### ISSUE TITLE
[BUG] Close Session & Mac Error

### ISSUE THREAD

**Issue by Jakquellyn** [WhiskeySockets/Baileys#648]
why when I broadcast it isn't sent to all groups?
why when I broadcast it isn't sent to all groups? here is the log

```javascript
SessionError: No sessions
    at 9170057191585.94 [as awaitable] (/root/calestial/node_modules/libsignal/src/session_cipher.js:71:23)
    at async _asyncQueueExecutor (/root/calestial/node_modules/libsignal/src/queue_job.js:20:29)
```

and why suddenly the message not read error occurred with the Mac Error log

```javascript
Session error:Error: Bad MAC Error: Bad MAC
    at Object.verifyMAC (/root/calestial/node_modules/libsignal/src/crypto.js:87:15)
    at SessionCipher.doDecryptWhisperMessage (/root/calestial/node_modules/libsignal/src/session_cipher.js:250:16)
    at async SessionCipher.decryptWithSessions (/root/calestial/node_modules/libsignal/src/session_cipher.js:147:29)
    at async 62895411171246.0 [as awaitable] (/root/calestial/node_modules/libsignal/src/session_cipher.js:171:28)
    at async _asyncQueueExecutor (/root/calestial/node_modules/libsignal/src/queue_job.js:20:29)
```

**Comment by Todpig** [comment]
I have the same problem

**Comment by joseluna03** [comment]
me to

**Comment by enoksaju** [comment]
me too

**Comment by ecatugy** [comment]
me too

**Comment by PurpShell** [comment]
Make sure your auth state is including sessions. That being said, I will work on making this process less headache-inducing

**Comment by marcosrocha85** [comment]
Any example of how can we handle sessions?

**Comment by eduardochaves1** [comment]
Also with this problem on v6.7.8

**Comment by Sansekai** [comment]
Same ploblem in v 6.7.8

**Comment by eduardochaves1** [comment]
![image](https://github.com/user-attachments/assets/842ef2fc-3d6a-4fbd-8ba7-e6727ef27bc8)

I noticed that when the No Sessions error occurs in the instance, these documents appear in the registry of that mongo instance. Simply removing them does not solve the problem, as they appear again.

**Comment by xxdannilinxx** [comment]
up

**Comment by vitorvk2** [comment]
have any solution about it?

**Comment by AlanMartines** [comment]
I have that same problem too, any solution?

**Comment by tonykx** [comment]
Alguma solução?
