### ISSUE TITLE
Pls help

### ISSUE THREAD

**Issue by Azarela-Vnk** [WhiskeySockets/Baileys#662]
Connection update: { isNewLogin: true, qr: undefined }
Connection update: {
  connection: 'close',
  lastDisconnect: {
    error: Error: Stream Errored (restart required)
        at WebSocketClient.<anonymous> (/root/Baphomate/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:502:13)
        at WebSocketClient.emit (node:events:517:28)
        at /root/Baphomate/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:236:35
        at Object.decodeFrame (/root/Baphomate/node_modules/@whiskeysockets/baileys/lib/Utils/noise-handler.js:136:17)
        at WebSocketClient.onMessageRecieved (/root/Baphomate/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:212:15)
        at WebSocketClient.emit (node:events:517:28)
        at WebSocket.<anonymous> (/root/Baphomate/node_modules/@whiskeysockets/baileys/lib/Socket/Client/web-socket-client.js:46:100)
        at WebSocket.emit (node:events:517:28)
        at Receiver.receiverOnMessage (/root/Baphomate/node_modules/ws/lib/websocket.js:1209:20)
        at Receiver.emit (node:events:517:28) {
      data: [Object],
      isBoom: true,
      isServer: true,
      output: [Object]
    },
    date: 2024-02-28T09:11:40.690Z
  }
}

**Comment by Guru322** [comment]
> Connection update: { isNewLogin: true, qr: undefined } Connection update: { connection: 'close', lastDisconnect: { error: Error: Stream Errored (restart required) at WebSocketClient. (/root/Baphomate/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:502:13) at WebSocketClient.emit (node:events:517:28) at /root/Baphomate/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:236:35 at Object.decodeFrame (/root/Baphomate/node_modules/@whiskeysockets/baileys/lib/Utils/noise-handler.js:136:17) at WebSocketClient.onMessageRecieved (/root/Baphomate/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:212:15) at WebSocketClient.emit (node:events:517:28) at WebSocket. (/root/Baphomate/node_modules/@whiskeysockets/baileys/lib/Socket/Client/web-socket-client.js:46:100) at WebSocket.emit (node:events:517:28) at Receiver.receiverOnMessage (/root/Baphomate/node_modules/ws/lib/websocket.js:1209:20) at Receiver.emit (node:events:517:28) { data: [Object], isBoom: true, isServer: true, output: [Object] }, date: 2024-02-28T09:11:40.690Z } }

just restart the socket
