### ISSUE TITLE
[BUG] Getting disconnected after Scanning QRCode with stream:error ErrorCode:516

### ISSUE THREAD

**Issue by dhirennjaypal** [WhiskeySockets/Baileys#701]
**Describe the bug**
I am using this library from so long but suddenly when I scan QRCode today, it connect and quickly disconnects, also it disconnect from phone but stays connected in PC. I cant receive messages but can send messages, also those messages can only be seen from whatsapp web, they are seen as 'waiting for message' in mobile. Also same code works in other PCs, just doesn't work in my PC.

**To Reproduce**
1. Created a new connection
2. Scan QRCode
3. then suddenly got disconnected.

**Expected behavior**
Should have been connected

**Environment (please complete the following information):**
 - Is this on a server? Yes
 - What do your `connectOptions` look like?
 ```ts
    makeWASocket({
        auth: state,
        printQRInTerminal: true,
    });
```
 - Do you have multiple clients on the same IP? No
 - Are you using a proxy? No

**Additional context**
My Sample code which produces this error.
```ts
import makeWASocket, { DisconnectReason, BufferJSON, useMultiFileAuthState } from '@whiskeysockets/baileys'
import { Boom } from '@hapi/boom'

async function connectToWhatsApp () {
    const { state, saveCreds } = await useMultiFileAuthState('auth_info_baileys')

    const sock = makeWASocket({
	auth: state,
        printQRInTerminal: true,
    });

    sock.ev.on ('creds.update', saveCreds)

    sock.ev.on('connection.update', (update) => {
        const { connection, lastDisconnect } = update
        if(connection === 'close') {
            const shouldReconnect = (lastDisconnect?.error as Boom)?.output?.statusCode !== DisconnectReason.loggedOut
            console.log('connection closed due to ', lastDisconnect?.error, ', reconnecting ', shouldReconnect)
            if(shouldReconnect) {
                connectToWhatsApp()
            }
        } else if(connection === 'open') {
            console.log('opened connection')
        }
    });
    sock.ev.on('messages.upsert', m => {
	console.log("Message Received: "+m.messages[0].key.remoteJid);
    });

}

connectToWhatsApp();

```

Console Output of the error generated from this code:
```
C:\Users\admin\Desktop\the_baileys_test>npx ts-node app1.ts
{"level":30,"time":"2024-03-27T11:13:35.466Z","pid":52552,"hostname":"194-160-178-68","class":"baileys","browser":["Baileys","Chrome","4.0.0"],"helloMsg":{"clientHello":{"ephemeral":"uheawwz7v5jIs5HEvljX30hPhqvCiX84u5AdUuIUBRU="}},"msg":"connected to WA"}
{"level":30,"time":"2024-03-27T11:13:35.758Z","pid":52552,"hostname":"194-160-178-68","class":"baileys","node":{"passive":false,"userAgent":{"platform":"MACOS","appVersion":{"primary":2,"secondary":2403,"tertiary":2},"mcc":"000","mnc":"000","osVersion":"0.1","manufacturer":"","device":"Desktop","osBuildNumber":"0.1","releaseChannel":"RELEASE","localeLanguageIso6391":"en","localeCountryIso31661Alpha2":"US"},"connectType":"WIFI_UNKNOWN","connectReason":"USER_ACTIVATED","devicePairingData":{"eRegid":"AAAAag==","eKeytype":"BQ==","eIdent":"n1EuW23HRHtYlsNOTc0AOOYH3b7uZ7hSjsHe+m86/Xs=","eSkeyId":"AAAB","eSkeyVal":"XlGQcaAty78TMeFOcwf0j/AGe4laU23aE+9obuZXokU=","eSkeySig":"i4jocyiqHcqtgorukwfnGy6dcYmn7byY2FjzFAgoQA8/jmAzSEVOfOv8QDgF+cKA28rQT8wS5OFRFyq0nF+lCw==","buildHash":"ctjRqW1/JS8QL+XWNBTAYg==","deviceProps":"CgdCYWlsZXlzGAEgAA=="}},"msg":"not logged in, attempting registration..."}
[[QRCODE]]
{"level":30,"time":"2024-03-27T11:14:05.797Z","pid":52552,"hostname":"194-160-178-68","class":"baileys","me":{"id":"918000898790:64@s.whatsapp.net","name":"Galaxy Group"},"platform":"smbi","msg":"pairing configured successfully, expect to restart the connection..."}
{"level":50,"time":"2024-03-27T11:14:06.258Z","pid":52552,"hostname":"194-160-178-68","class":"baileys","node":{"tag":"stream:error","attrs":{"code":"516"}},"msg":"stream errored out"}
{"level":30,"time":"2024-03-27T11:14:06.263Z","pid":52552,"hostname":"194-160-178-68","class":"baileys","trace":"Error: Stream Errored (unknown)\n    at WebSocketClient.<anonymous> (C:\\Users\\galaxygroup\\Desktop\\the_baileys_test\\node_modules\\@whiskeysockets\\baileys\\lib\\Socket\\socket.js:502:13)\n    at WebSocketClient.emit (node:events:517:28)\n    at WebSocketClient.emit (node:domain:489:12)\n    at C:\\Users\\galaxygroup\\Desktop\\the_baileys_test\\node_modules\\@whiskeysockets\\baileys\\lib\\Socket\\socket.js:236:35\n    at Object.decodeFrame (C:\\Users\\galaxygroup\\Desktop\\the_baileys_test\\node_modules\\@whiskeysockets\\baileys\\lib\\Utils\\noise-handler.js:136:17)\n    at WebSocketClient.onMessageRecieved (C:\\Users\\galaxygroup\\Desktop\\the_baileys_test\\node_modules\\@whiskeysockets\\baileys\\lib\\Socket\\socket.js:212:15)\n    at WebSocketClient.emit (node:events:517:28)\n    at WebSocketClient.emit (node:domain:489:12)\n    at WebSocket.<anonymous> (C:\\Users\\galaxygroup\\Desktop\\the_baileys_test\\node_modules\\@whiskeysockets\\baileys\\lib\\Socket\\Client\\web-socket-client.js:46:100)\n    at WebSocket.emit (node:events:517:28)","msg":"connection errored"}
connection closed due to  Error: Stream Errored (unknown)
    at WebSocketClient.<anonymous> (C:\Users\galaxygroup\Desktop\the_baileys_test\node_modules\@whiskeysockets\baileys\lib\Socket\socket.js:502:13)
    at WebSocketClient.emit (node:events:517:28)
    at WebSocketClient.emit (node:domain:489:12)
    at C:\Users\galaxygroup\Desktop\the_baileys_test\node_modules\@whiskeysockets\baileys\lib\Socket\socket.js:236:35
    at Object.decodeFrame (C:\Users\galaxygroup\Desktop\the_baileys_test\node_modules\@whiskeysockets\baileys\lib\Utils\noise-handler.js:136:17)
    at WebSocketClient.onMessageRecieved (C:\Users\galaxygroup\Desktop\the_baileys_test\node_modules\@whiskeysockets\baileys\lib\Socket\socket.js:212:15)
    at WebSocketClient.emit (node:events:517:28)
    at WebSocketClient.emit (node:domain:489:12)
    at WebSocket.<anonymous> (C:\Users\galaxygroup\Desktop\the_baileys_test\node_modules\@whiskeysockets\baileys\lib\Socket\Client\web-socket-client.js:46:100)
    at WebSocket.emit (node:events:517:28) {
  data: { tag: 'stream:error', attrs: { code: '516' }, content: undefined },
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 516,
    payload: {
      statusCode: 516,
      error: 'Unknown',
      message: 'Stream Errored (unknown)'
    },
    headers: {}
  }
} , reconnecting  true
{"level":30,"time":"2024-03-27T11:14:06.706Z","pid":52552,"hostname":"194-160-178-68","class":"baileys","browser":["Baileys","Chrome","4.0.0"],"helloMsg":{"clientHello":{"ephemeral":"BLPhM+AbW/VsjWYKgeMTEwEG1mHl7WEiuoa4c+g9yCE="}},"msg":"connected to WA"}
{"level":30,"time":"2024-03-27T11:14:06.977Z","pid":52552,"hostname":"194-160-178-68","class":"baileys","node":{"username":"xxxxxxx","passive":true,"userAgent":{"platform":"MACOS","appVersion":{"primary":2,"secondary":2403,"tertiary":2},"mcc":"000","mnc":"000","osVersion":"0.1","manufacturer":"","device":"Desktop","osBuildNumber":"0.1","releaseChannel":"RELEASE","localeLanguageIso6391":"en","xxxx":"US"},"connectType":"WIFI_UNKNOWN","connectReason":"USER_ACTIVATED","device":64},"msg":"logging in..."}
{"level":30,"time":"2024-03-27T11:14:07.622Z","pid":52552,"hostname":"194-160-178-68","class":"baileys","msg":"0 pre-keys found on server"}
{"level":30,"time":"2024-03-27T11:14:07.627Z","pid":52552,"hostname":"194-160-178-68","class":"baileys","count":30,"msg":"uploading pre-keys"}
{"level":30,"time":"2024-03-27T11:14:08.065Z","pid":52552,"hostname":"194-160-178-68","class":"baileys","count":30,"msg":"uploaded pre-keys"}
{"level":30,"time":"2024-03-27T11:14:08.344Z","pid":52552,"hostname":"194-160-178-68","class":"baileys","msg":"opened connection to WA"}
opened connection
{"level":30,"time":"2024-03-27T11:14:08.362Z","pid":52552,"hostname":"194-160-178-68","class":"baileys","msg":"handled 0 offline messages/notifications"}
```

**Comment by mayankagar360** [comment]
+1

**Comment by AbhishekSuresh2** [comment]
Yes I Have This Same Error Please Fix It Fast

**Comment by vasani-arpit** [comment]
+1

**Comment by dhirennjaypal** [comment]
Working now
