### ISSUE TITLE
Connection Open [BUG]

### ISSUE THREAD

**Issue by shanmugaacharan** [WhiskeySockets/Baileys#723]
**Describe the bug**
{"level":30,"time":"2024-04-10T11:56:11.787Z","pid":24388,"hostname":"SHANMUGAASARAN","class":"baileys","trace":"Error: Connection Failure\n    at WebSocketClient.<anonymous> (D:\\Whatsapp-Automation-Backend\\node_modules\\@whiskeysockets\\baileys\\lib\\Socket\\socket.js:507:13)\n    at WebSocketClient.emit (node:events:518:28)\n    at D:\\Whatsapp-Automation-Backend\\node_modules\\@whiskeysockets\\baileys\\lib\\Socket\\socket.js:236:35\n    at Object.decodeFrame (D:\\Whatsapp-Automation-Backend\\node_modules\\@whiskeysockets\\baileys\\lib\\Utils\\noise-handler.js:136:17)\n    at WebSocketClient.onMessageRecieved (D:\\Whatsapp-Automation-Backend\\node_modules\\@whiskeysockets\\baileys\\lib\\Socket\\socket.js:212:15)\n    at WebSocketClient.emit (node:events:518:28)\n    at WebSocket.<anonymous> (D:\\Whatsapp-Automation-Backend\\node_modules\\@whiskeysockets\\baileys\\lib\\Socket\\Client\\web-socket-client.js:46:100)\n    at WebSocket.emit (node:events:518:28)\n    at Receiver.receiverOnMessage (D:\\Whatsapp-Automation-Backend\\node_modules\\ws\\lib\\websocket.js:1209:20)\n    at Receiver.emit (node:events:518:28)","msg":"connection errored"}
connection closed due to  Error: Connection Failure
    at WebSocketClient.<anonymous> (D:\Whatsapp-Automation-Backend\node_modules\@whiskeysockets\baileys\lib\Socket\socket.js:507:13)
    at WebSocketClient.emit (node:events:518:28)
    at D:\Whatsapp-Automation-Backend\node_modules\@whiskeysockets\baileys\lib\Socket\socket.js:236:35
    at Object.decodeFrame (D:\Whatsapp-Automation-Backend\node_modules\@whiskeysockets\baileys\lib\Utils\noise-handler.js:136:17)
    at WebSocketClient.onMessageRecieved (D:\Whatsapp-Automation-Backend\node_modules\@whiskeysockets\baileys\lib\Socket\socket.js:212:15)
    at WebSocketClient.emit (node:events:518:28)
    at WebSocket.<anonymous> (D:\Whatsapp-Automation-Backend\node_modules\@whiskeysockets\baileys\lib\Socket\Client\web-socket-client.js:46:100)
    at WebSocket.emit (node:events:518:28)
    at Receiver.receiverOnMessage (D:\Whatsapp-Automation-Backend\node_modules\ws\lib\websocket.js:1209:20)
    at Receiver.emit (node:events:518:28) {
  data: { reason: '401', location: 'atn' },
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 401,
    payload: {
      statusCode: 401,
      error: 'Unauthorized',
      message: 'Connection Failure'
    },
    headers: {}
  }
} , reconnecting  false

**Code**
const express = require('express');
const app = express();
const { default: makeWASocket, useMultiFileAuthState, DisconnectReason } = require('@whiskeysockets/baileys');
const fs = require('fs');
const qrcode = require('qrcode-terminal');

async function connectToWhatsApp () {
    const { state, saveCreds } = await useMultiFileAuthState('auth_info_baileys');

    const sock = makeWASocket({
        // can provide additional config here
        printQRInTerminal: true,
        auth: state
    })

    sock.ev.on('creds.update', saveCreds);

    sock.ev.on('connection.update', (update) => {
        const { connection, lastDisconnect } = update
        if(connection === 'close') {
            const shouldReconnect = lastDisconnect.error?.output?.statusCode !== DisconnectReason.loggedOut;
            console.log('connection closed due to ', lastDisconnect.error, ', reconnecting ', shouldReconnect)
            // reconnect if not logged out
            if(shouldReconnect) {
                connectToWhatsApp()
            }
        } else if(connection === 'open') {
            console.log('opened connection')
        }
    })
    sock.ev.on('messages.upsert', async m => {
        console.log(JSON.stringify(m, undefined, 2))

        console.log('replying to', m.messages[0].key.remoteJid)
        await sock.sendMessage(m.messages[0].key.remoteJid, { text: 'Hello there!' });
    })
}
// run in main file
connectToWhatsApp()

const port = 3056;

app.listen(port, () => {
    console.log(`Server running at http://localhost:${port}`);
});

**Expected behavior**
A clear and concise description of what you expected to happen is to connection is open

**Environment (please complete the following information):**
 - OS Windows
 -  Node js v20

**Additional context**

**Comment by PurpShell** [comment]
You were logged out, will make a better effort to document these errors and make more differing errors for different cases

**Comment by deriknyvo** [comment]
@purpshell From time to time, I experience disconnections for no apparent reason. I’m not sure whether it’s something related to the Baileys project or if it’s caused by WhatsApp itself, as I’ve also noticed the issue on the web version, even without using Baileys

sorry for reviving the issue
