### ISSUE TITLE
[BUG] makeInMemoryStore

### ISSUE THREAD

**Issue by hyung27** [WhiskeySockets/Baileys#747]
/storage/emulated/0/Download/bot/node_modules/@whiskeysockets/baileys/lib/Store/make-in-memory-store.js:157
                Object.assign(contacts[update.id], contact);
                       ^

TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at EventEmitter.<anonymous> (/storage/emulated/0/Download/bot/node_modules/@whiskeysockets/baileys/lib/Store/make-in-memory-store.js:157:24)

Node.js v20.11.1

I use the latest version v6.7.0

**Comment by unknownncat** [comment]
```js
sock.ev.process(async (update) => {
    const obj = {};
    for(const contact of update) {
        obj[contact.id] = obj[contact.id] || {}; // Ensures that the property exists
        Object.assign(obj[contact.id], contact); // Merges contact data into the property
    }
});
```

To troubleshoot this issue, you should check the context in which update.id is used and ensure that it always points to a valid object in your code. It's likely that update.id is undefined or null at some point during the execution of your program, causing the TypeError when trying to assign properties to it using Object.assign.

**Comment by R4ptor44** [comment]
I have a problem :
makeInMemoryStore is not a function

**Comment by ferianss** [comment]
const store = makeInMemoryStore({
              ^

TypeError: makeInMemoryStore is not a function
    at Object.<anonymous> (/root/zops/index.js:91:15)
    at Module._compile (node:internal/modules/cjs/loader:1529:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1613:10)
    at Module.load (node:internal/modules/cjs/loader:1275:32)
    at Module._load (node:internal/modules/cjs/loader:1096:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)
    at node:internal/main/run_main_module:28:49

Node.js v20.19.2

**Comment by LuisPerezcx** [comment]
> I have a problem : makeInMemoryStore is not a function

did you resolve that?
