### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Code-seven123** [WhiskeySockets/Baileys#764]
Is there a solution available for fixing this error? The solution is fireInitQueries: false. But is it really important?

```bash
[15:20:18.169] ERROR (9816): unexpected error in 'init queries'
    err: {
      "type": "Error",
      "message": "bad-request",
      "stack":
          Error: bad-request
              at assertNodeErrorFree (/data/data/com.termux/files/home/ITwZY-DEV/node_modules/@whiskeysockets/baileys/lib/WABinary/generic-utils.js:56:15)
              at query (/data/data/com.termux/files/home/ITwZY-DEV/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:140:48)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async fetchProps (/data/data/com.termux/files/home/ITwZY-DEV/node_modules/@whiskeysockets/baileys/lib/Socket/chats.js:623:28)
              at async Promise.all (index 1)
              at async executeInitQueries (/data/data/com.termux/files/home/ITwZY-DEV/node_modules/@whiskeysockets/baileys/lib/Socket/chats.js:709:9)
      "data": 400,
      "isBoom": true,
      "isServer": true,
      "output": {
        "statusCode": 500,
        "payload": {
          "statusCode": 500,
          "error": "Internal Server Error",
          "message": "An internal server error occurred"
        },
        "headers": {}
      }
    }
```

**Comment by PurpShell** [comment]
fixed in latest
