### ISSUE TITLE
[BUG] Stream errored out after QR scan

### ISSUE THREAD

**Issue by oscarguindzberg** [WhiskeySockets/Baileys#765]
**Describe the bug**
Running example.ts I get a "Stream errored out" right after QR scan. Connection is automatically restarted and everything works fine.

**To Reproduce**
- yarn example
- scan the QR code

**Expected behavior**
- "Stream errored out" not shown after QR scan. No need for connection restart.

**Environment (please complete the following information):**
 - Is this on a server? No
 - What do your `connectOptions` look like? I am running example.ts as is.
 - Do you have multiple clients on the same IP? No
 - Are you using a proxy? No

**Additional context**
- Commit 3ba86c155
- MacOS monterrey
- Node v20.11.1
- yarn v1.22.22

**More info**
- Tried this with 3 different phones, same behaviour.
- Maybe related to https://github.com/WhiskeySockets/Baileys/issues/537

**Console**
```
myPrompt$ yarn example
yarn run v1.22.22
$ node --inspect -r ts-node/register Example/example.ts
Debugger listening on ws://127.0.0.1:9229/e7ee....
For help, see: https://nodejs.org/en/docs/inspector
using WA v2.2403.2, isLatest: true
connection update {
  connection: 'connecting',
  receivedPendingNotifications: false,
  qr: undefined
}
connection update {
  qr: '2@/l16WrtJM79....'
}
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ ██▄▄█ ▀▄ ▄▄ █ ▀▄▀▄█  ▄ ▄▀▄█ ▀ ▀▄▄   ▀██ ▄▄▄▄▄ █
█ █   █ █▀▀▀ ▄▀  ▀ ▀ ▀▄▀▀▄ ▀▀▄█▀▄ ▄▄   ▄  █▀▄▀█ █   █ █
....

connection update { isNewLogin: true, qr: undefined }
{"level":50,"time":"2024-05-06T16:17:55.330Z","pid":94665,"hostname":"myHost","node":{"tag":"stream:error","attrs":{"code":"515"}},"msg":"stream errored out"}
connection update {
  connection: 'close',
  lastDisconnect: {
    error: Error: Stream Errored (restart required)
        at WebSocketClient.<anonymous> (/path/Baileys/src/Socket/socket.ts:662:7)
        at WebSocketClient.emit (node:events:518:28)
        at WebSocketClient.emit (node:domain:488:12)
        at /path/Baileys/src/Socket/socket.ts:338:23
        at Object.decodeFrame (/path/Baileys/src/Utils/noise-handler.ts:176:5)
        at WebSocketClient.onMessageReceived (/path/Baileys/src/Socket/socket.ts:310:9)
        at WebSocketClient.emit (node:events:518:28)
        at WebSocketClient.emit (node:domain:488:12)
        at WebSocket.<anonymous> (/path/Baileys/src/Socket/Client/web-socket-client.ts:40:52)
        at WebSocket.emit (node:events:518:28) {
      data: [Object],
      isBoom: true,
      isServer: true,
      output: [Object]
    },
    date: 2024-05-06T16:17:55.332Z
  }
}
using WA v2.2403.2, isLatest: true
connection update {
  connection: 'connecting',
  receivedPendingNotifications: false,
  qr: undefined
}
{"level":40,"time":"2024-05-06T16:17:58.009Z","pid":94665,"hostname":"myHost","msg":"no name present, ignoring presence update request..."}
connection update { connection: 'open' }
connection update { receivedPendingNotifications: true }
recv 4 chats, 4 contacts, 34 msgs (is latest: true)
recv messages  {
....
```

**Comment by oscarguindzberg** [comment]
@SheIITear why was this issue closed?

**Comment by SheIITear** [comment]
This is not a bug.

**Comment by oscarguindzberg** [comment]
Is this the expected way of using Baileys to connect a new whatsapp number? i.e. call makeWASocket(), scan the QR code, receive a `connection.update` event with a `connection: 'close'` and the error described above, then call makeWASocket() again?

**Comment by vinaybadola** [comment]
Details :

1. Running locally on my device (Ubuntu 24.04.1 LTS)
2. using PM2 
3. baileys version @whiskeysockets/baileys": "^6.7.9"
4. node version 18.19
5.  bull: "^4.16.5"

I still get this error and the other one of  **"job failed Cannot read properties of undefined (reading 'match')"** ,  when i try to send message using bull (redis queue system) . So i add the job of sending message to user through bull and it gives me error 


TypeError: Cannot read properties of undefined (reading 'match')
    at extractUrlFromText (/home/vinay/Desktop/main-app/whatsapp-automation/node_modules/@whiskeysockets/baileys/lib/Utils/messages.js:38:66)
    at generateLinkPreviewIfRequired (/home/vinay/Desktop/main-app/whatsapp-automation/node_modules/@whiskeysockets/baileys/lib/Utils/messages.js:41:48)
    at generateWAMessageContent (/home/vinay/Desktop/main-app/whatsapp-automation/node_modules/@whiskeysockets/baileys/lib/Utils/messages.js:246:71)
    at generateWAMessage (/home/vinay/Desktop/main-app/whatsapp-automation/node_modules/@whiskeysockets/baileys/lib/Utils/messages.js:507:102)
    at Object.sendMessage (/home/vinay/Desktop/main-app/whatsapp-automation/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:626:69)
    at Queue.<anonymous> (file:///home/vinay/Desktop/main-app/whatsapp-automation/config/process-message.js:24:18)


and this one 

class":"baileys","node":{"tag":"stream:error","attrs":{},"content":[{"tag":"conflict","attrs":{"type":"replaced"}}]},"msg":"stream errored out"}


here is my code for sending message using queue 


```
import messageQueue from './queue.js';
import Message from '../src/messages/models/message-data-model.js';
import ConnectServices from '../src/devices/services/connectServices.js';
import mongoose from 'mongoose';

const connectServices = new ConnectServices();


messageQueue.process('sendMessage', 5, async (job) => {
  const { sessionId, phoneNumber, message, messageId, userId, mode } = job.data;
  console.log('have you reached here');
  try {
    console.log("job data>>>>", job.data);
     const io = mode === 'qr' ? getIoContextSomehow() : null;
     const client = await connectServices.getClient(sessionId, io, userId, mode);

    console.log('Client during message-processing:',client);

    console.log('sending message to');
    if (!client) {
      throw new Error('Session not found');
    }
    const formattedNumber = `${(phoneNumber)}@s.whatsapp.net`;
    await client.sendMessage(formattedNumber , { text: message });
    console.log("job processed ");
    // Update the message status to 'sent'
    await Message.findByIdAndUpdate(messageId, { status: 'sent' });
  } catch (error) {
    // Update the message status to 'failed'
    console.log("job failed", error.message);
    // await Message.findByIdAndUpdate(messageId, { status: 'failed', reasonForFailure: error.message });
    throw error; // Re-throw the error to mark the job as failed
  }
});
```


the job data is 

{
  "jobData": {
    "sessionId": "WE3u641lObDAFsTlAAXX",
    "phoneNumber": "91745781XXXX",
    "messageContent": "have you completed your work",
    "messageId": "678a34589dc3a555ad4c3e6c",
    "mode": "message-processing"
  },
  "returnValue": null
}
