### ISSUE TITLE
[BUG] You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection

### ISSUE THREAD

**Issue by aniakg** [WhiskeySockets/Baileys#769]
Hello,

I keep getting this error message

You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection

TypeError: Cannot read properties of undefined (reading 'user')
    at /home/app1waghl/public_html/server/whatsapp.js:213:36
    at EventEmitter.listener (/home/app1waghl/public_html/node_modules/@whiskeysockets/baileys/lib/Utils/event-buffer.js:82:17)
    at EventEmitter.emit (node:events:526:35)
    at Object.emit (/home/app1waghl/public_html/node_modules/@whiskeysockets/baileys/lib/Utils/event-buffer.js:94:23)
    at WebSocket.<anonymous> (/home/app1waghl/public_html/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:430:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by SatganzDevs** [comment]
same problem
