### ISSUE TITLE
[BUG] lastDisconnect Connection Terminated

### ISSUE THREAD

**Issue by Laminhdatau** [WhiskeySockets/Baileys#778]
# the status code always displays the disconnection reason 428

{"level":30,"time":"2024-05-11T02:04:01.032Z","pid":14442,"hostname":"sadfrwrfffsd","class":"baileys","trace":"Error: Connection Terminated\n    at WebSocketClient.<anonymous> (/home/sadfrwrfffsd/waweb/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:454:30)\n    at WebSocketClient.emit (node:events:518:28)\n    at WebSocketClient.emit (node:domain:488:12)\n    at WebSocket.<anonymous> (/home/sadfrwrfffsd/waweb/node_modules/@whiskeysockets/baileys/lib/Socket/Client/web-socket-client.js:46:100)\n    at WebSocket.emit (node:events:518:28)\n    at WebSocket.emit (node:domain:488:12)\n    at WebSocket.emitClose (/home/sadfrwrfffsd/waweb/node_modules/ws/lib/websocket.js:265:10)\n    at TLSSocket.socketOnClose (/home/sadfrwrfffsd/waweb/node_modules/ws/lib/websocket.js:1289:15)\n    at TLSSocket.emit (node:events:530:35)\n    at TLSSocket.emit (node:domain:488:12)","msg":"connection errored"}
{
  lastDisconnect: Error: Connection Terminated
      at WebSocketClient.<anonymous> (/home/sadfrwrfffsd/waweb/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:454:30)
      at WebSocketClient.emit (node:events:518:28)
      at WebSocketClient.emit (node:domain:488:12)
      at WebSocket.<anonymous> (/home/sadfrwrfffsd/waweb/node_modules/@whiskeysockets/baileys/lib/Socket/Client/web-socket-client.js:46:100)
      at WebSocket.emit (node:events:518:28)
      at WebSocket.emit (node:domain:488:12)
      at WebSocket.emitClose (/home/sadfrwrfffsd/waweb/node_modules/ws/lib/websocket.js:265:10)
      at TLSSocket.socketOnClose (/home/sadfrwrfffsd/waweb/node_modules/ws/lib/websocket.js:1289:15)
      at TLSSocket.emit (node:events:530:35)
      at TLSSocket.emit (node:domain:488:12) {
    data: null,
    isBoom: true,
    isServer: false,
    output: { statusCode: 428, payload: [Object], headers: {} }
  }
}

**Comment by spacesoft321** [comment]
Same problem at my website : **FastWSapi.com**

**Comment by postguruji** [comment]
we facing the same issues as yesterday

**Comment by sairmali** [comment]
1+

**Comment by tuin007** [comment]
Did anyone manage to solve it?

**Comment by tuin007** [comment]
Does anyone have any idea how to resolve it?
I'm in Brazil, with a server in Brazil and I'm facing this problem

**Comment by mayankagar360** [comment]
Any one please can help here

**Comment by tuin007** [comment]
+1

**Comment by tuin007** [comment]
Please suggest me any solution to solve this error

**Comment by ElielsonU** [comment]
same here.

**Comment by jonhy751** [comment]
i need solution 😭

**Comment by OKEBiling** [comment]
same,  keep connect to socket ,

**Comment by spacesoft321** [comment]
first install proxy server software on your vps or dedicated server 

after it all connection work 

more info login FastWSapi.com

![image](https://github.com/WhiskeySockets/Baileys/assets/6949772/031821ff-9d1c-42a2-b035-b045e53bf85d)

**Comment by JPabloVM** [comment]
It keeps happening here, any solution?

**Comment by aacassandra** [comment]
{"level":30,"time":"2025-09-18T14:07:20.217Z","pid":1220978,"hostname":"AmanahWorks","class":"baileys","trace":"Error: WebSocket Error ()\n    at WebSocketClient.<anonymous> (/var/www/html/smart-school/server_wa/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:620:17)\n    at WebSocketClient.emit (node:events:518:28)\n    at WebSocket.<anonymous> (/var/www/html/smart-school/server_wa/node_modules/@whiskeysockets/baileys/lib/Socket/Client/websocket.js:46:100)\n    at WebSocket.emit (node:events:518:28)\n    at emitErrorAndClose (/var/www/html/smart-school/server_wa/node_modules/ws/lib/websocket.js:1041:13)\n    at ClientRequest.<anonymous> (/var/www/html/smart-school/server_wa/node_modules/ws/lib/websocket.js:881:5)\n    at ClientRequest.emit (node:events:518:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:518:28)","msg":"connection errored"}

any one know this?
