### ISSUE TITLE
[BUG]Bug Connection Closed Immediately After Scanning QR Code

### ISSUE THREAD

**Issue by AbhishekSuresh2** [WhiskeySockets/Baileys#783]
**Description:**
When attempting to log in to WhatsApp using Baileys library, the connection is immediately closed after scanning the QR code. This issue prevents new connections from being established, while old connections continue to work as expected.

**Sample Code Of Qr:**

```javascript
import makeWASocket, { DisconnectReason, BufferJSON, useMultiFileAuthState } from '@whiskeysockets/baileys'
import { Boom } from '@hapi/boom'

async function connectToWhatsApp () {
    const { state, saveCreds } = await useMultiFileAuthState('auth_info_baileys')

    const sock = makeWASocket({
        auth: state,
        printQRInTerminal: true, 
    });

    sock.ev.on('creds.update', saveCreds)

    sock.ev.on('connection.update', (update) => {
        const { connection, lastDisconnect } = update
        if (connection === 'close') {
            const shouldReconnect = (lastDisconnect?.error as Boom)?.output?.statusCode !== DisconnectReason.loggedOut
            console.log('Connection closed due to', lastDisconnect?.error, ', reconnecting', shouldReconnect)
            if (shouldReconnect) {
                connectToWhatsApp() // Reconnect if necessary
            }
        } else if (connection === 'open') {
            console.log('Opened connection')
        }
    });

    sock.ev.on('messages.upsert', m => {
        console.log("Message Received: " + m.messages[0].key.remoteJid);
    });

}

connectToWhatsApp()
```

**Error Message:**
Connection closed. You are logged out.
3|WaunofficialNode3007 | updateInstanceStatus 339 | Changing instance status to :: false
3|WaunofficialNode3007 | startsock :: connection update {
3|WaunofficialNode3007 | connection: 'close',
3|WaunofficialNode3007 | lastDisconnect: {
3|WaunofficialNode3007 | error: Error: Stream Errored (conflict)
3|WaunofficialNode3007 | at WebSocket. (/opt/NodeJs/WAMultiDevice3007/whatsappmultipledevice/Baileys-master/src/Socket/socket.ts:514:7)
3|WaunofficialNode3007 | at WebSocket.emit (events.js:400:28)
3|WaunofficialNode3007 | at WebSocket.emit (domain.js:475:12)
3|WaunofficialNode3007 | at /opt/NodeJs/WAMultiDevice3007/whatsappmultipledevice/Baileys-master/src/Socket/socket.ts:278:23
3|WaunofficialNode3007 | at Object.decodeFrame (/opt/NodeJs/WAMultiDevice3007/whatsappmultipledevice/Baileys-master/src/Utils/noise-handler.ts:164:5)

**To Reproduce:**
1. Create a new connection.
2. Scan the QR code.
3. Observe the connection failure.

**Expected Behavior:**
After scanning the QR code, the connection should be established successfully, allowing communication with WhatsApp.

**Environment:**
- Running on a local machine.
- `connectOptions`:
  -    makeWASocket({
       auth: state,
       printQRInTerminal: true,
   });
- No multiple clients on the same IP.
- Not using a proxy.

**Additional Context:**
This issue affects new connections only, while existing connections continue to function properly. Any insights or workaround solutions would be appreciated.

**Comment by I-N-R-L** [comment]
Iam happy to know Baileys have this type of issue's 😂 team zuck✅

**Comment by sahilbrandwala** [comment]
+1

**Comment by ABHINAV-321** [comment]
Same issue

**Comment by magicgodsir** [comment]
Same issue 😭😞

**Comment by spacesoft321** [comment]
if he is use Selenium WebDriver ChromeDriver then all application can run 

if you want any update, i can help you ( FastWSapi.com )

**Comment by han755** [comment]
After pairing code entered one vibrate and not connecting just vibrate

**Comment by meetshamee** [comment]
Same issue

**Comment by Rohan658** [comment]
Sir please solve auto logout issue

**Comment by Thee-clipse** [comment]
Same here

**Comment by hiran6** [comment]
Please solve my problem

**Comment by johncolins21** [comment]
Same to me here

**Comment by mayankagar360** [comment]
Please help @whiskeysockets-bot it is very urgent for us

**Comment by Dennomeni** [comment]
[Uploading xbugbotv4 (1) (1).zip…]()

**Comment by Dennomeni** [comment]
[Discord-bot-V13-main.zip](https://github.com/WhiskeySockets/Baileys/files/15312058/Discord-bot-V13-main.zip)

**Comment by EasyTech23** [comment]
It's not downloading anything except videos

**Comment by zororiju** [comment]
Same to me here

**Comment by 44102** [comment]
Same issue

**Comment by badboybackagain** [comment]
I am also facing the same issue.

**Comment by tasinJodhpur** [comment]
🥹💯

**Comment by Tohidkhan6332** [comment]
❤️❤️

**Comment by Alien-Alfa** [comment]
I have the same issue but, The same code is working when on my local terminal. I scanned and got the session file the connection is still open and I am able to use it.

Please try the same code in a linux terminal rather than termux or other platforms (Just an assumption)

**Comment by I-N-R-L** [comment]
> I have the same issue but, The same code is working when on my local terminal. I scanned and got the session file the connection is still open and I am able to use it.
> 
> Please try the same code in a linux terminal rather than termux or other platforms (Just an assumption)

Who asked🫵

**Comment by DAVIAMERICO242** [comment]
whatsapp has updated about 19hours ago, I think now baileysAPI is broken

**Comment by sairmali** [comment]
1+

**Comment by enoksaju** [comment]
+1

**Comment by sahilbrandwala** [comment]
trying to block cloud servers from accessing whatsapp web as a way to try prevent people from using libraries like Baileys.
Soon all will end

**Comment by Alien-Alfa** [comment]
> trying to block cloud servers from accessing whatsapp web as a way to try prevent people from using libraries like Baileys. Soon all will end

I think whatsapp was trying to fix a bug. The Lock Bot which used baileys in the wrong way to block user from registering. WhatsApp actually fixed the issue but at the same time this happened. Maybe it’s all connected

**Comment by Alien-Alfa** [comment]
For the time being we have to use local host for sessions generation until we get a proper update.

**Comment by Alien-Alfa** [comment]
> > I have the same issue but, The same code is working when on my local terminal. I scanned and got the session file the connection is still open and I am able to use it.
> > Please try the same code in a linux terminal rather than termux or other platforms (Just an assumption)
> 
> Who asked🫵

Thank you for this useless comment 👍🏻 it really resembles you

**Comment by AbhishekSuresh2** [comment]
> > > I have the same issue but, The same code is working when on my local terminal. I scanned and got the session file the connection is still open and I am able to use it.
> > > Please try the same code in a linux terminal rather than termux or other platforms (Just an assumption)
> > 
> > 
> > Who asked🫵
> 
> Thank you for this useless comment 👍🏻 it really resembles you

Hi alfa

**Comment by Alien-Alfa** [comment]
> > > > I have the same issue but, The same code is working when on my local terminal. I scanned and got the session file the connection is still open and I am able to use it.
> > > > Please try the same code in a linux terminal rather than termux or other platforms (Just an assumption)
> > > 
> > > 
> > > Who asked🫵
> > 
> > 
> > Thank you for this useless comment 👍🏻 it really resembles you
> 
> Hi alfa

Hey 👋

**Comment by allburov** [comment]
>https://github.com/WhiskeySockets/Baileys/issues/779#issuecomment-2112887056

@PurpShell here we also have "conflicted", but usual restart doesn't help - the session automaticly loged out from the phone itself or show "scan QR code again"
As you can notice there's additional message:

>Connection closed. You are logged out.

![image](https://github.com/WhiskeySockets/Baileys/assets/4376814/df903ae7-1ef8-406d-9649-6fcd8c74c2d5)

**Comment by allburov** [comment]
btw, the similar start happening with webjs about a week ago as well, just at the same time as with Baileys - it could be related.
Let me know if you need some test phone numbers or additional logs, I can give your more!

**Comment by meetshamee** [comment]
The previously connected is working
QR is showing successfully.
Sync failed

I think it is logging out due to sync problem.

**Comment by Diluhch** [comment]
I m also facing this issue from few days please fix this problem soon as possible

**Comment by Diluhch** [comment]
I m also facing this issue from few days please fix this problem soon as possible

**Comment by souravkl11** [comment]
The problem is with the WhatsApp Web itself. Try to connect an Indian WhatsApp account with the official WhatsApp Web using an RDP hosted in some other region. It won't work. Lizard boy did something fishy!

**Comment by Alien-Alfa** [comment]
> btw, the similar start happening with webjs about a week ago as well, just at the same time as with Baileys - it could be related.
> Let me know if you need some test phone numbers or additional logs, I can give your more!

Seems like its a common issue. Most probably Whatsapp Updated its connection protocol and preference

**Comment by allanlisboa** [comment]
I downgraded to version 6.5.0 and it solved the problem!

**Comment by mayankagar360** [comment]
I have tried downgrading the version but it did not work @allanlisboa

**Comment by allanlisboa** [comment]
> I have tried downgrading the version but it did not work @allanlisboa

Here the problem has been resolved

**Comment by Alien-Alfa** [comment]
### Temporary Solution

Hey guys, I have found a temporary solution for the issue. 

my qr is hosted in joyed free account, so its in German server thus it have a German ip so I tried connecting with a German vpn and it actually worked.

So, try connecting to the same VPN as the server and it should work This is my Theory 

I'm Using "@whiskeysockets/baileys": "6.6.0"

Don't forget to comment Your Ideas

**Comment by pandiarajanvp** [comment]
Same issue. Please fix it

**Comment by meetshamee** [comment]
> ### Temporary Solution
> Hey everyone,
> 
> I've found a temporary fix for the issue we're facing. Since my QR code is hosted on Koyeb's free account, it runs on a German server, thus it should have a German IP address. I experimented by connecting through a German VPN, and and it managed to connect successfully. I tried it several time and it works! **In my case it won't work with any other VPN than German**
> 
> So, my theory is to try connecting through a VPN located in the same region as the server. This might just do the trick.
> 
> I'm currently using "@whiskeysockets/baileys" version 6.6.0.
> 
> Feel free to share your insights!

Not Working

**Comment by pra021** [comment]
> ### Temporary Solution
> Hey everyone,
> 
> I've found a temporary fix for the issue we're facing. Since my QR code is hosted on Koyeb's free account, it runs on a German server, thus it should have a German IP address. I experimented by connecting through a German VPN, and and it managed to connect successfully. I tried it several time and it works! **In my case it won't work with any other VPN than German**
> 
> So, my theory is to try connecting through a VPN located in the same region as the server. This might just do the trick.
> 
> I'm currently using "@whiskeysockets/baileys" version 6.6.0.
> 
> Feel free to share your insights!

Working perfectly

**Comment by pra021** [comment]
> ### Temporary Solution
> Hey everyone,
> 
> I've found a temporary fix for the issue we're facing. Since my QR code is hosted on Koyeb's free account, it runs on a German server, thus it should have a German IP address. I experimented by connecting through a German VPN, and and it managed to connect successfully. I tried it several time and it works! **In my case it won't work with any other VPN than German**
> 
> So, my theory is to try connecting through a VPN located in the same region as the server. This might just do the trick.
> 
> I'm currently using "@whiskeysockets/baileys" version 6.6.0.
> 
> Feel free to share your insights!

Used same location VPN on mobile
Working perfectly

**Comment by manojsitapara** [comment]
> > ### Temporary Solution
> > Hey everyone,
> > I've found a temporary fix for the issue we're facing. Since my QR code is hosted on Koyeb's free account, it runs on a German server, thus it should have a German IP address. I experimented by connecting through a German VPN, and and it managed to connect successfully. I tried it several time and it works! **In my case it won't work with any other VPN than German**
> > So, my theory is to try connecting through a VPN located in the same region as the server. This might just do the trick.
> > I'm currently using "@whiskeysockets/baileys" version 6.6.0.
> > Feel free to share your insights!
> 
> Used same location VPN on mobile Working perfectly

location means country of whatsapp phone number or same city where data center located?

**Comment by pra021** [comment]
> > > ### Temporary Solution
> > > Hey everyone,
> > > I've found a temporary fix for the issue we're facing. Since my QR code is hosted on Koyeb's free account, it runs on a German server, thus it should have a German IP address. I experimented by connecting through a German VPN, and and it managed to connect successfully. I tried it several time and it works! **In my case it won't work with any other VPN than German**
> > > So, my theory is to try connecting through a VPN located in the same region as the server. This might just do the trick.
> > > I'm currently using "@whiskeysockets/baileys" version 6.6.0.
> > > Feel free to share your insights!
> > 
> > 
> > Used same location VPN on mobile Working perfectly
> 
> location means country of whatsapp phone number or same city where data center located?

Use VPN on your whatsapp installed mobile phone and set same location in mobile vpn where your web application hosted

**Comment by Alien-Alfa** [comment]
> > ### Temporary Solution
> > Hey everyone,
> > I've found a temporary fix for the issue we're facing. Since my QR code is hosted on Koyeb's free account, it runs on a German server, thus it should have a German IP address. I experimented by connecting through a German VPN, and and it managed to connect successfully. I tried it several time and it works! **In my case it won't work with any other VPN than German**
> > So, my theory is to try connecting through a VPN located in the same region as the server. This might just do the trick.
> > I'm currently using "@whiskeysockets/baileys" version 6.6.0.
> > Feel free to share your insights!
> 
> Not Working

What I said was, Set up a VPN on the mobile, where the WhatsApp is installed and connect to a server, which is in the same country as the QR code hosted. 

In my case, my QR was hosted on koyeb on a German server, so on my phone, I used a German server for my VPN

what happened was My WhatsApp and the QR had the same german IP because I am using the German VPN and the server is On Germany 


Try this again it should work

**Comment by meetshamee** [comment]
> > > ### Temporary Solution
> > > Hey everyone,
> > > I've found a temporary fix for the issue we're facing. Since my QR code is hosted on Koyeb's free account, it runs on a German server, thus it should have a German IP address. I experimented by connecting through a German VPN, and and it managed to connect successfully. I tried it several time and it works! **In my case it won't work with any other VPN than German**
> > > So, my theory is to try connecting through a VPN located in the same region as the server. This might just do the trick.
> > > I'm currently using "@whiskeysockets/baileys" version 6.6.0.
> > > Feel free to share your insights!
> > 
> > 
> > Not Working
> 
> What I said was, Set up a VPN on the mobile, where the WhatsApp is installed and connect to a server, which is in the same country as the QR code hosted.
> 
> In my case, my QR was hosted on koyeb on a German server, so on my phone, I used a German server for my VPN
> 
> what happened was My WhatsApp and the QR had the same german IP because I am using the German VPN and the server is On Germany
> 
> Try this again it should work

I tried to connect Indian cloud server (GCP), using Indian IP, But Not Working

**Comment by Alien-Alfa** [comment]
> Somehow, Indian IPs are not working. I tried with German IP and installing VPN and connecting to german servers and then scanning the code. It works.

Where was the code hosted?

**Comment by meetshamee** [comment]
I tried to connect German cloud server (Contabo), using German VPN, its Working. Thanks @Alien-Alfa

**Comment by sairmali** [comment]
its is working fine just change your server location

**Comment by 7kXTQsyhnySpko6n** [comment]
> > > > ### Temporary Solution
> > > > Hey everyone,
> > > > I've found a temporary fix for the issue we're facing. Since my QR code is hosted on Koyeb's free account, it runs on a German server, thus it should have a German IP address. I experimented by connecting through a German VPN, and and it managed to connect successfully. I tried it several time and it works! **In my case it won't work with any other VPN than German**
> > > > So, my theory is to try connecting through a VPN located in the same region as the server. This might just do the trick.
> > > > I'm currently using "@whiskeysockets/baileys" version 6.6.0.
> > > > Feel free to share your insights!
> > > 
> > > 
> > > Used same location VPN on mobile Working perfectly
> > 
> > 
> > location means country of whatsapp phone number or same city where data center located?
> 
> Use VPN on your whatsapp installed mobile phone and set same location in mobile vpn where your web application hosted

Which country's phone number are you logging in to

**Comment by meetshamee** [comment]
also connected Singapore VPS, with VPN,  Working....

**Comment by pra021** [comment]
> > > > > ### Temporary Solution
> > > > > Hey everyone,
> > > > > I've found a temporary fix for the issue we're facing. Since my QR code is hosted on Koyeb's free account, it runs on a German server, thus it should have a German IP address. I experimented by connecting through a German VPN, and and it managed to connect successfully. I tried it several time and it works! **In my case it won't work with any other VPN than German**
> > > > > So, my theory is to try connecting through a VPN located in the same region as the server. This might just do the trick.
> > > > > I'm currently using "@whiskeysockets/baileys" version 6.6.0.
> > > > > Feel free to share your insights!
> > > > 
> > > > 
> > > > Used same location VPN on mobile Working perfectly
> > > 
> > > 
> > > location means country of whatsapp phone number or same city where data center located?
> > 
> > 
> > Use VPN on your whatsapp installed mobile phone and set same location in mobile vpn where your web application hosted
> 
> Which country's phone number are you logging in to

Indian number

**Comment by 7kXTQsyhnySpko6n** [comment]
> > > > > > ### Temporary Solution
> > > > > > Hey everyone,
> > > > > > I've found a temporary fix for the issue we're facing. Since my QR code is hosted on Koyeb's free account, it runs on a German server, thus it should have a German IP address. I experimented by connecting through a German VPN, and and it managed to connect successfully. I tried it several time and it works! **In my case it won't work with any other VPN than German**
> > > > > > So, my theory is to try connecting through a VPN located in the same region as the server. This might just do the trick.
> > > > > > I'm currently using "@whiskeysockets/baileys" version 6.6.0.
> > > > > > Feel free to share your insights!
> > > > > 
> > > > > 
> > > > > Used same location VPN on mobile Working perfectly
> > > > 
> > > > 
> > > > location means country of whatsapp phone number or same city where data center located?
> > > 
> > > 
> > > Use VPN on your whatsapp installed mobile phone and set same location in mobile vpn where your web application hosted
> > 
> > 
> > Which country's phone number are you logging in to
> 
> Indian number

Can I leave a contact information to communicate with you

**Comment by kj2222** [comment]
> For the time being we have to use local host for sessions generation until we get a proper update.

@Alien-Alfa Is this working for you: using local machine only for session generation and then using this session in cloud as usual?

**Comment by manojsitapara** [comment]
> > For the time being we have to use local host for sessions generation until we get a proper update.
> 
> @Alien-Alfa Is this working for you: using local machine only for session generation and then using this session in cloud as usual?

Yes it will

**Comment by kj2222** [comment]
> > > For the time being we have to use local host for sessions generation until we get a proper update.
> > 
> > 
> > @Alien-Alfa Is this working for you: using local machine only for session generation and then using this session in cloud as usual?
> 
> Yes it will

Not working for us. Gets connected on local machine, but when we try to use same session in cloud, it switches from connected to "connecting" mode and doesn't connect

**Comment by sou6av** [comment]
> ### Temporary Solution
> Hey everyone,
> 
> I've found a temporary fix for the issue we're facing. Since my QR code is hosted on Koyeb's free account, it runs on a German server, thus it should have a German IP address. I experimented by connecting through a German VPN, and and it managed to connect successfully. I tried it several time and it works! **In my case it won't work with any other VPN than German**
> 
> So, my theory is to try connecting through a VPN located in the same region as the server. This might just do the trick.
> 
> I'm currently using "@whiskeysockets/baileys" version 6.6.0.
> 
> Feel free to share your insights!

Edit: Doesn't work on the Beta version

**Comment by dsusoftech** [comment]
Phasing an issue in indian number connecting

**Comment by manojsitapara** [comment]
> > > > For the time being we have to use local host for sessions generation until we get a proper update.
> > > 
> > > 
> > > @Alien-Alfa Is this working for you: using local machine only for session generation and then using this session in cloud as usual?
> > 
> > 
> > Yes it will
> 
> Not working for us. Gets connected on local machine, but when we try to use same session in cloud, it switches from connected to "connecting" mode and doesn't connect

It works for me, for you I suspect due to [https://github.com/WhiskeySockets/Baileys/issues/794](794)

**Comment by badboybackagain** [comment]
> > Somehow, Indian IPs are not working. I tried with German IP and installing VPN and connecting to german servers and then scanning the code. It works.
> 
> Where was the code hosted?

I tried hosting it on indian server initially, but it did not work. Then hosted on german server and it worked with VPN.

**Comment by 7kXTQsyhnySpko6n** [comment]
> > > Somehow, Indian IPs are not working. I tried with German IP and installing VPN and connecting to german servers and then scanning the code. It works.
> > 
> > 
> > Where was the code hosted?
> 
> I tried hosting it on indian server initially, but it did not work. Then hosted on german server and it worked with VPN.

Did you set up a VPN service on a German server and connect to it using your phone? At this point, you can scan the code to log in?

**Comment by spacesoft321** [comment]
hi , i use **urbanvpn** on my google browse and set vpn random, after it we open google chrome and open web.whatsapp.com , qr code scaned on my pc / browser , so can we use urbanvpn in this application and set proxy server as per user requirement, 


maybe all qr code problem solved by urbanvpn type application ,  active this type application in your library file or waziper


**its possible or not**

**Comment by UchihaObito786** [comment]
I'm facing the same issue. 
Please fix it as soon as possible 🙏

**Comment by dsusoftech** [comment]
From last 6+ Hours device shows connecting in existing device and message stopped working in india.
any solution?

**Comment by dsusoftech** [comment]
My all whatsapp stopped working

**Comment by tallw** [comment]
Resolved #805

**Comment by kj2222** [comment]
Same, even after updating Baileys version doesn't work for Indian numbers

**Comment by dsusoftech** [comment]
On waziper script still working perfectly anyone know which library they are using?

**Comment by DAVIAMERICO242** [comment]
You'll need to use Evolution-API instead baileys directly, it's baileys based and have endpoints supporting proxy etc

**Comment by meetshamee** [comment]
> On waziper script still working perfectly anyone know which library they are using?

I think its 6.6

**Comment by Dryrtan** [comment]
> > On waziper script still working perfectly anyone know which library they are using?
> 
> I think its 6.6

I believe it is not the same problem that was happening to me, when upgrading to v6.7.2 the "Connection Failure" error occurred, when Downgrading to v6.6.0 the problem was resolved, thank you.

[11:41:45.106] INFO (72420): connection errored
    trace: "Error: Connection Failure
    at WebSocketClient.<anonymous> (D:\Projetos\whatsapp-api\node_modules\@whiskeysockets\baileys\lib\Socket\socket.js:524:13)
    at WebSocketClient.emit (node:events:518:28)\n    at WebS
ocketClient.emit (node:domain:488:12)
    at D:\Projetos\whatsapp-api\node_modules\@whiskeysockets\baileys\lib\Socket\socket.js:236:35
    at Object.decodeFrame (D:\Projetos\whatsapp-api\node_modules\@whiskeysockets\baileys\li
b\Utils\noise-handler.js:136:17)
    at WebSocketClient.onMessageReceived (D:\Projetos\whatsapp-api\node_modules\@whiskeysockets\baileys\lib\Socket\socket.js:212:15)
    at WebSocketClient.emit (node:events:518:28)\n    at WebSocketClient.emit (node:domain:488:12)
    at WebSocket.<anonymous> (D:\Projetos\whatsapp-api\node_modules\@whiskeysockets\baileys\lib\Socket\Client\web-socket-client.js:46:100)
    at WebSocket.emit (node:events:518:28)"

**Comment by tallw** [comment]
if you just updated baileys then it will work.
now if you messed with wbot.ts on your system, then you will have a version problem

**Comment by athilasb** [comment]
temp solution that work for me
sock = makeWASocket({
version: [2, 2413, 1],

**Comment by Riders004** [comment]
> I have the same issue but, The same code is working when on my local terminal. I scanned and got the session file the connection is still open and I am able to use it.
> 
> Please try the same code in a linux terminal rather than termux or other platforms (Just an assumption)

It's working on local machine or local pc or termux but not working on cloud server 

For termux I tried with my own real Indian number it's got linked but with cloud server hosted it's got linked and  logout automatic immediately
