### ISSUE TITLE
[BUG] Connection Failure

### ISSUE THREAD

**Issue by sherrywilly** [WhiskeySockets/Baileys#806]
connection update {
  connection: 'close',
  lastDisconnect: {
    error: Error: Connection Failure
        at WebSocketClient.<anonymous> (/root/tst/src/Socket/socket.ts:672:7)
        at WebSocketClient.emit (node:events:514:28)
        at WebSocketClient.emit (node:domain:489:12)
        at /root/tst/src/Socket/socket.ts:343:23
        at Object.decodeFrame (/root/tst/src/Utils/noise-handler.ts:192:5)
        at WebSocketClient.onMessageReceived (/root/tst/src/Socket/socket.ts:315:9)
        at WebSocketClient.emit (node:events:514:28)
        at WebSocketClient.emit (node:domain:489:12)
        at WebSocket.<anonymous> (/root/tst/src/Socket/Client/web-socket-client.ts:40:52)
        at WebSocket.emit (node:events:514:28) {
      data: [Object],
      isBoom: true,
      isServer: false,
      output: [Object]
    },
    date: 2024-05-20T23:43:44.020Z
  }
}

qr code not showing

**Comment by yogadev1990** [comment]
Same problem, 
App 2301098 output: [APP] 21/05/24 06:49:14 Connection Database has been established Successfully
App 2301098 output: [APP] 21/05/24 06:49:14 Re-Sync Database
App 2301098 output: [APP] 21/05/24 06:49:14 App Listening at http://localhost:8080
App 2301098 output: Socket Disconnect
qr code not showing

**Comment by ScarletEbinger** [comment]
same problem,

 at Receiver.emit (node:events:513:28)","msg":"connection errored"}
connection closed due to  Error: Connection Failure
    at WebSocketClient.<anonymous> (/home/ubuntu/SkayBots/GeminiBot/WhatsApp-Google-Gemini-chatbot/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:524:13)
    at WebSocketClient.emit (node:events:513:28)
    at /home/ubuntu/SkayBots/GeminiBot/WhatsApp-Google-Gemini-chatbot/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:236:35
    at Object.decodeFrame (/home/ubuntu/SkayBots/GeminiBot/WhatsApp-Google-Gemini-chatbot/node_modules/@whiskeysockets/baileys/lib/Utils/noise-handler.js:136:17)
    at WebSocketClient.onMessageReceived (/home/ubuntu/SkayBots/GeminiBot/WhatsApp-Google-Gemini-chatbot/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:212:15)
    at WebSocketClient.emit (node:events:513:28)
    at WebSocket.<anonymous> (/home/ubuntu/SkayBots/GeminiBot/WhatsApp-Google-Gemini-chatbot/node_modules/@whiskeysockets/baileys/lib/Socket/Client/web-socket-client.js:46:100)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/home/ubuntu/SkayBots/GeminiBot/WhatsApp-Google-Gemini-chatbot/node_modules/ws/lib/websocket.js:1209:20)
    at Receiver.emit (node:events:513:28) {
  data: { reason: '405', location: 'rva' },
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 405,
    payload: {
      statusCode: 405,
      error: 'Method Not Allowed',
      message: 'Connection Failure'
    },
    headers: {}
  }
}

**Comment by natanjborba** [comment]
S
![Screenshot_5](https://github.com/WhiskeySockets/Baileys/assets/78612166/fcc5b822-3ca1-4c80-9b88-28466b6be9be)
ame problem

**Comment by SheIITear** [comment]
Fixed in latest commit.
