### ISSUE TITLE
Cannot read property 'trace' of null at Object.get  while calling sock.sendMesssage

### ISSUE THREAD

**Issue by HoshenKadosh** [WhiskeySockets/Baileys#810]
**Describe the bug**
Error while calling `sock.sendMesssage`

**To Reproduce**
1. Created a new connection
2. call `sock.sendMesssage`

**Expected behavior**
message sent

**Environment (please complete the following information):**
 - Windows PC
 -  Conn info`{
      mobile: false,
      version: [2, 2413, 1],
      logger: pino({ level: loggerLevel }, pms.multistream(streams)),
      printQRInTerminal: true,
      auth: {
        creds: state.creds,
        /** caching makes the store faster to send/recv messages */
        keys: makeCacheableSignalKeyStore(state.keys, null),
      },
      mediaCache: mediaCahce,
      markOnlineOnConnect: false,
      browser: Browsers.macOS("Desktop"),
      syncFullHistory: false,
     getMessage: msgRetryHandler.getHandler,
    }`

 - Do you have multiple clients on the same IP? - No
 - Are you using a proxy? - No

**Additional context**
`
Error message
 TypeError: Cannot read property 'trace' of null
    at Object.get (C:\Users\Administrator\Desktop\שימי\node_modules\@whiskeysockets\baileys\lib\Utils\auth-utils.js:42:24)
    at Object.get (C:\Users\Administrator\Desktop\שימי\node_modules\@whiskeysockets\baileys\lib\Utils\auth-utils.js:97:48)
    at assertSessions (C:\Users\Administrator\Desktop\שימי\node_modules\@whiskeysockets\baileys\lib\Socket\messages-send.js:188:51)
    at C:\Users\Administrator\Desktop\שימי\node_modules\@whiskeysockets\baileys\lib\Socket\messages-send.js:374:23
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Object.transaction (C:\Users\Administrator\Desktop\שימי\node_modules\@whiskeysockets\baileys\lib\Utils\auth-utils.js:136:26)
    at async relayMessage (C:\Users\Administrator\Desktop\שימי\node_modules\@whiskeysockets\baileys\lib\Socket\messages-send.js:279:9)
    at async Object.sendMessage (C:\Users\Administrator\Desktop\שימי\node_modules\@whiskeysockets\baileys\lib\Socket\messages-send.js:652:17)
    at async Object.sendMessage (C:\Users\Administrator\Desktop\שימי\src\whatsapp.ts:98:21)
`

**Comment by HoshenKadosh** [comment]
this was caused because i didn't provide a logger at `makeCacheableSignalKeyStore(state.keys, **null**)`
