### ISSUE TITLE
TypeError: Cannot destructure property 'user' of '(0 , WABinary_1.jidDecode)(...)' as it is undefined.

### ISSUE THREAD

**Issue by ghost** [WhiskeySockets/Baileys#848]
@whiskeysockets\baileys\lib\Store\make-in-memory-store.js:104:33
```javascript
const { user } = (0, WABinary_1.jidDecode)(contactId);
```

@whiskeysockets\baileys\lib\Store\make-in-memory-store.js:103:83

```javascript
const contactHashes = await Promise.all(Object.keys(contacts).map(async (contactId
```

@whiskeysockets\baileys\lib\Utils\event-buffer.js:40:16

```javascript
ev.on('event', (map) => {for (const event in map) {ev.emit(event, map[event]);}
```

@whiskeysockets\baileys\lib\Utils\event-buffer.js:73:16)

```javascript
const consolidatedData = consolidateEvents(data);
        if (Object.keys(consolidatedData).length) {
            ev.emit('event', consolidatedData);
        }
        data = newData;
```

**Full Console Error**

```shell
Caught exception:  TypeError: Cannot destructure property 'user' of '(0 , WABinary_1.jidDecode)(...)' as it is undefined.
    at C:\Users\astro\Documents\GitHub\WaCrasher\node_modules\@whiskeysockets\baileys\lib\Store\make-in-memory-store.js:104:33
    at Array.map (<anonymous>)
    at EventEmitter.<anonymous> (C:\Users\astro\Documents\GitHub\WaCrasher\node_modules\@whiskeysockets\baileys\lib\Store\make-in-memory-store.js:103:83)
    at EventEmitter.emit (node:events:530:35)
    at EventEmitter.<anonymous> (C:\Users\astro\Documents\GitHub\WaCrasher\node_modules\@whiskeysockets\baileys\lib\Utils\event-buffer.js:40:16)     
    at EventEmitter.emit (node:events:518:28)
    at Object.flush (C:\Users\astro\Documents\GitHub\WaCrasher\node_modules\@whiskeysockets\baileys\lib\Utils\event-buffer.js:73:16)
    at processNodeWithBuffer (C:\Users\astro\Documents\GitHub\WaCrasher\node_modules\@whiskeysockets\baileys\lib\Socket\messages-recv.js:700:12)     
Caught exception:  TypeError: Cannot destructure property 'user' of '(0 , WABinary_1.jidDecode)(...)' as it is undefined.
    at C:\Users\astro\Documents\GitHub\WaCrasher\node_modules\@whiskeysockets\baileys\lib\Store\make-in-memory-store.js:104:33
    at Array.map (<anonymous>)
    at EventEmitter.<anonymous> (C:\Users\astro\Documents\GitHub\WaCrasher\node_modules\@whiskeysockets\baileys\lib\Store\make-in-memory-store.js:103:83)
    at EventEmitter.emit (node:events:530:35)
    at EventEmitter.<anonymous> (C:\Users\astro\Documents\GitHub\WaCrasher\node_modules\@whiskeysockets\baileys\lib\Utils\event-buffer.js:40:16)     
    at EventEmitter.emit (node:events:518:28)
    at Object.flush (C:\Users\astro\Documents\GitHub\WaCrasher\node_modules\@whiskeysockets\baileys\lib\Utils\event-buffer.js:73:16)
    at processNodeWithBuffer (C:\Users\astro\Documents\GitHub\WaCrasher\node_modules\@whiskeysockets\baileys\lib\Socket\messages-recv.js:700:12)     
 ```

**Comment by bobslavtriev** [comment]
https://github.com/WhiskeySockets/Baileys/pull/878
