### ISSUE TITLE
[BUG]  Error when trying to change profile picture

### ISSUE THREAD

**Issue by taironeAlves** [WhiskeySockets/Baileys#850]
When trying to update the profile image, Bailey returns the following error:
C:\whats-web\node_modules\@whiskeysockets\baileys\lib\Utils\messages-media.js:61
    throw new boom_1.Boom('No image processing library available');
          ^

Error: No image processing library available
    at getImageProcessingLibrary (C:\whats-web\node_modules\@whiskeysockets\baileys\lib\Utils\messages-media.js:61:11)
    at async generateProfilePicture (C:\whats-web\node_modules\@whiskeysockets\baileys\lib\Utils\messages-media.js:156:17)
    at async Object.updateProfilePicture (C:\whats-web\node_modules\@whiskeysockets\baileys\lib\Socket\chats.js:175:25)
    at async EventEmitter.<anonymous> (C:\whats-web\index.js:63:9) {
  data: null,
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 500,
    payload: {
      statusCode: 500,
      error: 'Internal Server Error',
      message: 'An internal server error occurred'
    },
    headers: {}
  }
}

Node.js v18.15.0

Has anyone recently had this problem and managed to resolve it? Thanks

**Comment by Salientekill** [comment]
> Error: No image processing library available
> 
> install with yarn add jimp or npm i jimp
> 
> READ THE DOCUMENTATION
> 
> Not is bug, close this issue

Instalei o jimp e continua: 

Error: No image processing library available
    at generateProfilePicture (/storage/emulated/0/.ESDEATH/ESDEATHBOT10/node_modules/@whiskeysockets/baileys/lib/Utils/messages-media.js:181:15)
    at async Object.updateProfilePicture (/storage/emulated/0/.ESDEATH/ESDEATHBOT10/node_modules/@whiskeysockets/baileys/lib/Socket/chats.js:182:17)
    at async startAle (/storage/emulated/0/.ESDEATH/ESDEATHBOT10/index.js:2661:5) {
  data: null,
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 500,
    payload: {
      statusCode: 500,
      error: 'Internal Server Error',
      message: 'An internal server error occurred'
    },
    headers: {}
  }
}
