### ISSUE TITLE
[BUG] No session found to decrypt message

### ISSUE THREAD

**Issue by oscarguindzberg** [WhiskeySockets/Baileys#886]
**Describe the bug**
I have a server with 15 connected whatsapp users.
I find this on the log from time to time:
```
{
  "level": 50,
  "time": 1718906974900,
  "pid": 41327,
  "hostname": "ip-xxx-xxx-xxx-xxx",
  "key": {
    "remoteJid": "xxx@g.us",
    "fromMe": false,
    "id": "xxx",
    "participant": "xxx@s.whatsapp.net"
  },
  "err": {
    "type": "Error",
    "message": "No session found to decrypt message",
    "stack": "Error: No session found to decrypt message\n at xxx@g.us::xxx::0 [as awaitable]   
     (/baileys/WASignalGroup/group_cipher.js:54:15)
     at async asyncQueueExecutor (/baileys/WASignalGroup/queue_job.js:20:29)"
  },
  "msg": "failed to decrypt message"
}
```

**To Reproduce**
Don't know how to reproduce, it happens from time to time on a server with 15 connected whatsapp users.

**Expected behavior**
No errors on the log

**Environment (please complete the following information):**
 - Is this on a server? yes
 - What do your `connectOptions` look like? 
```
const { version, isLatest } = await fetchLatestBaileysVersion()
const { state, saveCreds } = await useMultiFileAuthState('myPath')
const msgRetryCounterCache = new NodeCache()

        async function getMessage(key)  {
            if(store) {
                const msg = await store.loadMessage(key.remoteJid, key.id)
                return msg?.message || undefined
            }
            // only if store is present
            return proto.Message.fromObject({})
        }

 makeWASocket({
            version,
            logger,
            printQRInTerminal: false,
            mobile: false,
            auth: {
                creds: state.creds,
                keys: makeCacheableSignalKeyStore(state.keys, logger),
            },
            msgRetryCounterCache,
            generateHighQualityLinkPreview: true,
            // ignore broadcast and newsletter messages
            shouldIgnoreJid: jid => !jid || isJidBroadcast(jid) || isJidNewsletter(jid),
            // implement to handle retries & poll updates
            getMessage,
            shouldSyncHistoryMessage: () => true,
            markOnlineOnConnect: false
        })
```
 - Do you have multiple clients on the same IP? yes, 15 clients
 - Are you using a proxy? no

**Additional context**
Using baileys v6.7.5

**Comment by oscarguindzberg** [comment]
maybe related https://github.com/WhiskeySockets/Baileys/issues/885

**Comment by ErgashevAkbarjon** [comment]
I do have the same issue. Also have multiple connected WA numbers.

**Comment by ErgashevAkbarjon** [comment]
Maybe it's all because of using already an old and archived(by ForstaLabs) version of libsignal-node package. Maybe it's better to move to official package from signalapp ?

**Comment by dephea** [comment]
Same issue

**Comment by dcpenteado** [comment]
Same.

**Comment by ramon-victor** [comment]
Same

**Comment by CSFelix** [comment]
+1

**Comment by Xrazik1** [comment]
Same @adiwajshing

**Comment by postguruji** [comment]
+1

**Comment by NiraKain** [comment]
+1

**Comment by PurpShell** [comment]
Hey! The session is missing from your auth state. I hope all of you describe your auth state (multi-file, mysql etc.)

I am working behind the scenes on a revamp to the auth key storage situation since they are getting lost it seems

**Comment by natanjborba** [comment]
+1 I use MySQL

**Comment by DanNisenson** [comment]
Same, using SQL

**Comment by postguruji** [comment]
+ 1 with SQL LITE

**Comment by vguille** [comment]
I'm having the same problem, but only when I try to run inside a container, forcing a MAC address in the container temporarily solved it for me. Example: docker run --mac-address 02:42:ac:11:00:11 ...

**Comment by wis-dev** [comment]
Facing the same issue using Baileys `7.0.0-rc.3` with +5 connections running on Nodejs 24 with MySQL 8.4 and Nginx as proxy.

```
ERROR (1): failed to decrypt message
svc: "baileys"
key: {
  "remoteJid": "status@broadcast",
  "remoteJidAlt": "**************@lid",
  "fromMe": false,
  "id": "1SDFSDFSDFSDFSDF",
  "participant": "**************@s.whatsapp.net"
}
messageType: "skmsg"
sender: "status@broadcast"
author: "**************@s.whatsapp.net"
isSessionRecordError: false
err: {
  "type": "Error",
  "message": "No session found to decrypt message",
  "stack":
    Error: No session found to decrypt message
    at GroupCipher.decrypt (file:///usr/src/app/node_modules/baileys/lib/Signal/Group/group_cipher.js:35:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async executeTransactionWork (file:///usr/src/app/node_modules/baileys/lib/Utils/auth-utils.js:293:24)
    at async Object.transaction (file:///usr/src/app/node_modules/baileys/lib/Utils/auth-utils.js:439:28)
    at async decrypt (file:///usr/src/app/node_modules/baileys/lib/Utils/decode-wa-message.js:194:45)
    at async file:///usr/src/app/node_modules/baileys/lib/Socket/messages-recv.js:965:21
    at async file:///usr/src/app/node_modules/baileys/lib/Utils/make-mutex.js:16:36
    at async Promise.all (index 0)
    at async handleMessage (file:///usr/src/app/node_modules/baileys/lib/Socket/messages-recv.js:963:13)
    at async processNodeWithBuffer (file:///usr/src/app/node_modules/baileys/lib/Socket/messages-recv.js:1140:9)
}
```

This is how my connectOptions looks:

```
async create(storeId: string): Promise<WASocket> {
		const logger = withStore(storeId)
		const s3 = new S3Client()

		const { state, saveCreds, purgeRemote } = await useS3AuthState({
			s3,
			storeId,
			bucket: this.bucketName,
			basePath: this.dataPath
		})

		const keys = makeCacheableSignalKeyStore(state.keys, logger)
		const sock = makeWASocket({
			auth: { creds: state.creds, keys },
			logger,
			msgRetryCounterCache: this.msgRetryCounterCache,
			generateHighQualityLinkPreview: true,
			markOnlineOnConnect: false,
			syncFullHistory: false,
			qrTimeout: 60_000,
			connectTimeoutMs: 30_000,
			keepAliveIntervalMs: 25_000,
			retryRequestDelayMs: 600,
			maxMsgRetryCount: 3,
			defaultQueryTimeoutMs: 60_000,
			transactionOpts: {
				maxCommitRetries: 5,
				delayBetweenTriesMs: 1500
			},
			getMessage: async () => undefined,
			shouldSyncHistoryMessage: () => false
		})

		sock.ev.on('creds.update', saveCreds)
	}
```
