### ISSUE TITLE
[BUG] Connecting sessions to server

### ISSUE THREAD

**Issue by AidanFrencken** [WhiskeySockets/Baileys#910]
**Describe the bug**
When scanning a QR code the server responds with a 500 internal server error. message body is bad-request

**To Reproduce**
1. Created a new connection by scanning the QR code

**Expected behavior**
should respond without 500 error

**Environment (please complete the following information):**
 - Is this on a server? yes
 - What do your `connectOptions` look like?  default settings
 - Do you have multiple clients on the same IP? yes
 - Are you using a proxy? no

**Additional context**
I tested this on multiple servers and get the same outcome on each. If you don't have same problem please tell me so I can test it further if its something on my end

**Comment by bobslavtriev** [comment]
?????????????????

**Comment by AidanFrencken** [comment]
err: {
      "type": "Error",
      "message": "bad-request",
      "stack":
          Error: bad-request
              at assertNodeErrorFree (C:\Users\Administrator\Desktop\baileys-api-main\node_modules\@whiskeysockets\baileys\lib\WABinary\generic-utils.js:56:15)
              at query (C:\Users\Administrator\Desktop\baileys-api-main\node_modules\@whiskeysockets\baileys\lib\Socket\socket.js:140:48)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async fetchProps (C:\Users\Administrator\Desktop\baileys-api-main\node_modules\@whiskeysockets\baileys\lib\Socket\chats.js:623:28)
              at async Promise.all (index 1)
              at async executeInitQueries (C:\Users\Administrator\Desktop\baileys-api-main\node_modules\@whiskeysockets\baileys\lib\Socket\chats.js:709:9)
      "data": 400,
      "isBoom": true,
      "isServer": true,
      "output": {
        "statusCode": 500,
        "payload": {
          "statusCode": 500,
          "error": "Internal Server Error",
          "message": "An internal server error occurred"
        },
        "headers": {}
      }
    }
