### ISSUE TITLE
[BUG] Sending messages and listeners stop working

### ISSUE THREAD

**Issue by evgeniy1243** [WhiskeySockets/Baileys#915]
**Describe the bug**
After some time sending messages and listeners stop working except `connection.update`. After checking some cases, a pattern emerged. This all happens after these errors:

```
{"level":50,"time":1720467242916,"pid":1,"hostname":"1b1145d27714","node":{"tag":"stream:error","attrs":{},"content":[{"tag":"ack","attrs":{"class":"message","type":"poll","id":"1935202FD677240A82B440FBE0826946"}}]},"msg":"stream errored out"}
{"level":30,"time":1720467242916,"pid":1,"hostname":"1b1145d27714","trace":"Error: Stream Errored (ack)\n    at WebSocketClient.<anonymous> (/node_modules/@adiwajshing/baileys-md/lib/Socket/socket.js:524:13)\n    at WebSocketClient.emit (node:events:511:28)\n    at WebSocketClient.emit (node:domain:489:12)\n    at /node_modules/@adiwajshing/baileys-md/lib/Socket/socket.js:241:35\n    at Object.decodeFrame (/node_modules/@adiwajshing/baileys-md/lib/Utils/noise-handler.js:149:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","msg":"connection errored"}
Session 122, ConnectionUpdated {"connection":"close","lastDisconnect":{"error":{"data":{"tag":"stream:error","attrs":{},"content":[{"tag":"ack","attrs":{"class":"message","type":"poll","id":"1935202FD677240A82B440FBE0826946"}}]},"isBoom":true,"isServer":true,"output":{"statusCode":500,"payload":{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"},"headers":{}}},"date":"2024-07-08T19:34:02.916Z"}}
```

These types of errors became more frequent 4 days ago. Restarting sometimes helps, but most of the time nothing changes. Rescanning helps, but sometimes after a few hours the same error may occur again. 

**Environment:**
 - Is this on a server? - yes
 - What do your `connectOptions` look like? 
```
     let waConfig = {
        logger: P({ level: loggerLevel }),
        printQRInTerminal: false,
        auth: state,
        browser: [name, 'Chrome', '4.0.0'],
        msgRetryCounterMap: msgRetryCounterMap[connectionId],
        getMessage: getMessageForResend({ connectionId, db, processingRetryMessagesMutex}),
        treatCiphertextMessagesAsReal: true,
        mediaCache: myCache,
        shouldIgnoreJid: shouldIgnoreJid,
    }
```
 - Do you have multiple clients on the same IP? - Уes
 - Are you using a proxy? - Both. The problem occurs in both cases

**Comment by thereis** [comment]
Hello @evgeniy1243 have you discovered the cause of that or a possible solution?

**Comment by evgeniy1243** [comment]
@thereis Not yet. Do you have similar problems?

Can you provide all information please about your case?
