### ISSUE TITLE
profilePictureUrl bad-request [BUG]

### ISSUE THREAD

**Issue by Tiooxy** [WhiskeySockets/Baileys#934]
![Screenshot_2024-07-21-06-31-12-964_com gbwhatsapp3](https://github.com/user-attachments/assets/297fa1db-82ec-4a34-9fba-0e4e936dc797)

Error: bad-request
    at assertNodeErrorFree (/root/bot/node_modules/@adiwajshing/baileys/lib/WABinary/generic-utils.js:56:15)
    at query (/root/bot/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:145:48)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.profilePictureUrl (/root/bot/node_modules/@adiwajshing/baileys/lib/Socket/chats.js:442:24)
    at Object.handler (file:///root/bot/plugins/own-exec.js:22:15)
    at Object.handler (file:///root/bot/handler.js?update=1721517649386:1267:21) {
  data: 400,
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 500,
    payload: {
      statusCode: 500,
      error: 'Internal Server Error',
      message: 'An internal server error occurred'
    },
    headers: {}
  }
}

**Comment by Rippanteq7** [comment]
Use baileys github version, it was fixed in #901
