### ISSUE TITLE
[BUG] Invalid PreKey ID

### ISSUE THREAD

**Issue by vitorvk2** [WhiskeySockets/Baileys#936]
**Describe the bug**
When the application is restarted, an error is generated within the 'messages.upsert' events when the contact already has an open conversation with the host number.

**To Reproduce**
1. Created a new connection
2. Create event listener for events['messages.upsert']
3. Send message to server number
4. Some messages have Invalid PreKey ID

**Expected behavior**
I hope it will be possible to receive complete message data without errors, so that it can create contact data automatically.

**Environment (please complete the following information):**
 - Is this on a server? 
Yes.

 - What do your `connectOptions` look like? 
     mobile: false,
    logger: logger,
    qrTimeout: 180000,
    version: [2, 2413, 1],
    syncFullHistory: false,
    printQRInTerminal: true,
    defaultQueryTimeoutMs: undefined,
    receivedPendingNotifications: true,
    generateHighQualityLinkPreview: false,

 - Do you have multiple clients on the same IP?
Not.

 - Are you using a proxy?
Not.

**Additional context**
Log Erros:

```
{
  key: {
    remoteJid: '5544PHONE_NUMBER@s.whatsapp.net',
    fromMe: false,
    id: '70471D39BDBAA688A942695F7EB1586C',
    participant: undefined
  },
  err: SessionError: No session record
      at 554499094874.0 [as awaitable] (/usr/src/app/node_modules/libsignal/src/session_cipher.js:169:23)
      at async _asyncQueueExecutor (/usr/src/app/node_modules/libsignal/src/queue_job.js:20:29)
}


{
    "msgAttrs": {
        "from": "5544PHONE_NUMBER@s.whatsapp.net",
        "type": "text",
        "id": "5979C683E7F03C894C98F953AC7CB1C3",
        "sender_lid": "205218033758393@lid",
        "verified_level": "low",
        "notify": "Cleiton",
        "verified_name": "1176886696524636048",
        "t": "1721663353"
    },
    "retryCount": 1
}

{
  key: {
    remoteJid: '5544PHONE_NUMBER@s.whatsapp.net',
    fromMe: false,
    id: 'C7CBE3FDABE32C06F7F40339D7944A81',
    participant: undefined
  },
  err: PreKeyError: Invalid PreKey ID
      at SessionBuilder.initIncoming (/usr/src/app/node_modules/libsignal/src/session_builder.js:66:19)
      at async 554499890261.0 [as awaitable] (/usr/src/app/node_modules/libsignal/src/session_cipher.js:205:30)
      at async _asyncQueueExecutor (/usr/src/app/node_modules/libsignal/src/queue_job.js:20:29)
}
```

**Comment by vitorvk2** [comment]
@vitorvk2

**Comment by manfe** [comment]
@vitorvk2 did you have any clues about this?

I also noticed it.

```
{
  "level": 50,
  "time": "2024-05-23T13:30:11.515Z",
  "pid": 289771,
  "hostname": "ip-...",
  "key": {
    "remoteJid": "55......@s.whatsapp.net",
    "fromMe": false,
    "id": "4274D03BA49..."
  },
  "err": {
    "type": "PreKeyError",
    "message": "Invalid PreKey ID",
    "stack": "PreKeyError: Invalid PreKey ID\n    at SessionBuilder.initIncoming (.../source/node_modules/libsignal/src/session_builder.js:66:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async 554799386922.0 [as awaitable] (.../source/node_modules/libsignal/src/session_cipher.js:205:30)\n    at async _asyncQueueExecutor (.../source/node_modules/libsignal/src/queue_job.js:20:29)",
    "name": "PreKeyError"
  },
  "msg": "failed to decrypt message"
}

```

**Comment by hacxk** [comment]
Yeah it will fixed 80% in This **PR**: https://github.com/WhiskeySockets/Baileys/pull/732  Also Sync history as you can

**Comment by PurpShell** [comment]
#54
