### ISSUE TITLE
[BUG] Error: error:1C800064:Provider routines::bad decrypt / ERR_OSSL_BAD_DECRYPT

### ISSUE THREAD

**Issue by leroyanders** [WhiskeySockets/Baileys#989]
**Describe the bug**

```
Error: error:1C800064:Provider routines::bad decrypt
    at Decipheriv.final (node:internal/crypto/cipher:184:29)
    at Transform.final [as _final] (/Users/leroyanders/WebstormProjects/thrivestate-whatsapp-service/node_modules/@whiskeysockets/baileys/lib/Utils/messages-media.js:501:31)
    at prefinish (node:internal/streams/writable:914:14)
    at finishMaybe (node:internal/streams/writable:928:5)
    at Transform.Writable.end (node:internal/streams/writable:843:5)
    at IncomingMessage.onend (node:internal/streams/readable:946:10)
    at Object.onceWrapper (node:events:634:28)
    at IncomingMessage.emit (node:events:532:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
Error: error:1C800064:Provider routines::bad decrypt
    at Decipheriv.final (node:internal/crypto/cipher:184:29)
    at Transform.final [as _final] (/Users/leroyanders/WebstormProjects/thrivestate-whatsapp-service/node_modules/@whiskeysockets/baileys/lib/Utils/messages-media.js:501:31)
    at prefinish (node:internal/streams/writable:914:14)
    at finishMaybe (node:internal/streams/writable:928:5)
    at Transform.Writable.end (node:internal/streams/writable:843:5)
    at IncomingMessage.onend (node:internal/streams/readable:946:10)
    at Object.onceWrapper (node:events:634:28)
    at IncomingMessage.emit (node:events:532:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  library: 'Provider routines',
  reason: 'bad decrypt',
  code: 'ERR_OSSL_BAD_DECRYPT'
}

```

**To Reproduce**
1. Fix decryption

**Expected behavior**
Decryption should work.

**Environment (please complete the following information):**
 - Is this on a server? no
 - What do your `connectOptions` look like? 
 - Do you have multiple clients on the same IP? yes
 - Are you using a proxy? no

**Additional context**
 My code:

```
async setAttachment(
    cloudStorage: CloudStorageService,
    message: ExtendedWebMessageInfo,
  ): Promise<MessageBuilder> {
    const documentWithCaptionMessage =
      message.message?.documentWithCaptionMessage;
    const messageContent =
      message.message?.imageMessage ||
      message.message?.videoMessage ||
      message.message?.documentMessage ||
      documentWithCaptionMessage?.message?.documentMessage;

    let uploadedMessageMedia: FileDto | null = null;

    try {
      if (messageContent) {
        // Step 1: Decrypt the media using the decryptMedia function
        const buffer = await downloadMediaMessage(message, 'buffer', {});

        // Step 2: Upload the decrypted media to cloud storage
        uploadedMessageMedia = await cloudStorage.createMessageAttachment(
          message.key.id,
          {
            mimetype: messageContent.mimetype,
            data: buffer,
          },
        );
      }
    } catch (error) {
      if (error instanceof ApiError && error.code === 409) {
        return this;
      }
      throw error;
    }

    this.message = {
      ...this.message,
      attachment: uploadedMessageMedia,
    };

    return this;
  }
```

**Comment by CrazyPrince** [comment]
Try this one 
`async setAttachment(
    cloudStorage: CloudStorageService,
    message: ExtendedWebMessageInfo,
): Promise<MessageBuilder> {
    const documentWithCaptionMessage = message.message?.documentWithCaptionMessage;
    const messageContent = message.message?.imageMessage ||
        message.message?.videoMessage ||
        message.message?.documentMessage ||
        documentWithCaptionMessage?.message?.documentMessage;

    let uploadedMessageMedia: FileDto | null = null;

    try {
        if (messageContent) {
            // Step 1: Decrypt the media using the downloadMediaMessage function
            console.log("Attempting to decrypt media for message:", message.key.id);
            const buffer = await downloadMediaMessage(message, 'buffer', {});
            
            if (!buffer) {
                throw new Error("Decryption failed: buffer is empty or null.");
            }

            console.log("Media decrypted successfully for message:", message.key.id);

            // Step 2: Upload the decrypted media to cloud storage
            uploadedMessageMedia = await cloudStorage.createMessageAttachment(
                message.key.id,
                {
                    mimetype: messageContent.mimetype,
                    data: buffer,
                },
            );
            console.log("Media uploaded successfully for message:", message.key.id);
        }
    } catch (error) {
        console.error("Error during media processing for message:", message.key.id, error);

        if (error instanceof ApiError && error.code === 409) {
            console.warn("Conflict error (409): Resource already exists, skipping upload.");
            return this;
        }

        console.error("An unexpected error occurred:", error);
        throw error;
    }

    this.message = {
        ...this.message,
        attachment: uploadedMessageMedia,
    };

    return this;
} `

**Comment by Korretdesigns** [comment]
Simply redeploy, i face this some times and all i have to do is to redeploy or turn off your vpn

**Comment by leroyanders** [comment]
> use node lts and this should be fixed

whats you mean?

**Comment by bentacos** [comment]
> > use node lts and this should be fixed
> 
> whats you mean?

please ignore that reply. this is indeed a bug in the **downloadEncryptedContent** of messages-media.ts

**Comment by marlonlimaserra** [comment]
up

**Comment by leroyanders** [comment]
@PurpShell any suggestions?

**Comment by vitorvk2** [comment]
up

**Comment by vitorvk2** [comment]
same error.

**Comment by IIDUIIz** [comment]
Mesmo erro

**Comment by jeffersonfelixdev** [comment]
up

**Comment by missonganesh** [comment]
up

**Comment by purpshell** [comment]
For this issue specifically, there needs to be either more data to reproduce adequately or reporting on the client to WA servers that decryption failed. There could be other reasons why things like this happen, but I'll look into it later

**Comment by sachin-plunes** [comment]
@leroyanders   did you find the solution ?
